### ISSUE TITLE
UX issue, trying to "update an existing image"

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#1048]
Stepping outside of our own experience a user is finding it challenging to see how to "update an image" using Alloy Editor. When an image is added and linked it's not so easy to figure out how to replace that image with a new one and indeed replacing the image removes the link that was on the image.

When adding an image this is easy the user uses the "plus button" to activate a bar that contains an image icon. When trying to update that image file with a new one it's not in the users mind to "add" an image, they want to replace it and don't think the plus button would be of use.

Clicking an existing image brings up a bar that is without an image icon. They must click the plus button to open up a different bar to the one that appears when they click the existing image. Additionally actually selecting a new image file wipes off the original link so the user must replace their link too.

See GIF.

![ux-difficult-1](https://user-images.githubusercontent.com/18121278/52012923-743cff80-24a1-11e9-845f-e0f4c1f23141.gif)

**Comment by jbalsas** [comment]
Hey @duracell80, this is certainly a very valid concern. What would you expect... an additional button in the toolbar, maybe with the image or pencil icon? Thinking about this, I assume it might be just as unintuitive to remove the image?

**Comment by duracell80** [comment]
Honestly ... the ideal solution would be to rethink the UX in DXP and have a static toolbar that didn't move or jump or have three separate parts to it (unless the user was live editing).

On this issue though, an icon in the toolbar that appears when a user clicks the existing image would be a good solution. Keeping it the same icon that's in the plus menu would help users identify. The perfect solution would be a right click context menu, that would then have "image properties", "remove image", "update image", "cut/copy/paste".

I think most users if shown CKEditor would be of the opinion ... why can't we have those features? We had those features in 6.1 why did the editor get harder to use?
