### ISSUE TITLE
Tags for recent alphas are missing for recent releases

### ISSUE THREAD

**Issue by wincent** [liferay/alloy-editor#1073]
We need a `git push --tags` to get these tags in the repo:

- 2.0.0-alpha.1
- 2.0.0-alpha.2
- 2.0.0-alpha.3
- 2.0.0-alpha.4
- 2.0.0-alpha.5

cc @julien

**Comment by julien** [comment]
@wincent done!

**Comment by wincent** [comment]
Thanks @julien!
