### ISSUE TITLE
Update branch structure after 2.0.0 release

### ISSUE THREAD

**Issue by wincent** [liferay/alloy-editor#1074]
Similar to what we did with the Clay repo preparing for the next major version (described [here](https://github.com/liferay/clay/pull/1485#issuecomment-459255258)), we probably want to update our branch structure after release.

Current:

- `master`: stable, updates after every 1.x release.
- `develop`: active, used to prepare next 1.x release.
- `2.x-develop`: active, used to prepare next 2.x release.
- `1.x`: not sure — I figure this is some kind of maintenance branch but it hasn't been updated since mid-2018.

Post-release:

- `master`: stable, updates after every 2.x release.
- `develop`: active, used to prepare next 2.x release.
- `2.x-develop`: effectively becomes a legacy branch that we don't touch any more.
- `1.x`: most likely untouched.

So I think we basically need to:

1. Merge `2.x-develop` into `develop`.
2. Merge `develop` into `master`.
3. Stop using `2.x-develop`, start using `develop`.

Does that sound about right @julien?

**Comment by jbalsas** [comment]
Hey @wincent, in a conversation we had, you brought up that based on how we use branches, we might as well just merge to `master`... that and the fact that issues will only auto-close when merged into `master` got me thinking...

It might be more convenient to use `master` as our moving target and say, `2.x` as our release branch (I think some models would call this `stable` or `stable-1.x`...)

With that, we'd have:
- `master`: active, used to prepare next 2.x release
- `stable`: sable, updates after every 2.x release
- 1.x: effectively becomes a legacy branch that we only touch for maintenance fixes
- 1.x-stable: most likely untouched unless we have to make maintenance fixes

What do you think, @julien, @wincent?

**Comment by wincent** [comment]
I think developing on master would make things a bit simpler, which would be nice. The other main difference that you pointed out is the auto-close behavior:

* Working on `develop`, we effectively don't see anything close until we cut a release and merge to master. This means that people looking at the issues will know that "closed" issues are released, and "open" issues are either unfixed or fixed-and-pending-release (you need to look inside to figure out, unless we add a label).
* Working on `master` means that "open" issues are unfixed, but "closed" issues are either released or fixed-and-pending-release (again, you need to look inside to figure out).

I think that the `master` approach makes it easier for us as developers to see what needs to be done at a glance, and we can mitigate possible confusion about what is fixed and what is released by just keeping up a regular cadence of releases (ie. if we have pending fixes to go out, we should be cutting a release every week, and if releasing is too hard, we should work on making it easy).

**Comment by julien** [comment]
@jbalsas I also think working on `master` would make things more simple.
