### ISSUE TITLE
Automate and Improve CKEditor update process

### ISSUE THREAD

**Issue by jbalsas** [liferay/alloy-editor#1124]
The current process of updating our bundled version of CKEditor is currently manual and involves a series of [custom manual steps](https://github.com/liferay/alloy-editor/blob/master/CONTRIBUTING.md#updating-ckeditor) as describe in the [CONTRIBUTING guidelines](https://github.com/liferay/alloy-editor/blob/master/CONTRIBUTING.md)

CKEditor 4.x is currently being released as the [ckeditor npm package](https://www.npmjs.com/package/ckeditor), so that could be an option. If some of their [releases](https://github.com/ckeditor/ckeditor-releases/tree/standard/4.11.x#releases-code) matches our needs, we could simply pick from there.

A more custom version could be achieved by using the proper [release branch](https://github.com/ckeditor/ckeditor-dev/tree/release/4.11.x) and running the build process with our predefined `config.json` settings.

Doing a quick cost-benefit analysis, I think we could just pick one of the official releases probably taking a bit of a hit on bundle size so we can avoid a overly complex update process.

**Comment by julien** [comment]
Seems like a good idea 👍

**Comment by blzaugg** [comment]
I remember looking into trying to use their [online builder](https://ckeditor.com/cke4/builder) to programmatically (using `build-config.js`) build a custom build that fit Portal's needs. But I couldn't identify an established API to do that. It seemed any hacked solution could break at any time in the future.

**Comment by jbalsas** [comment]
The best way is to simply use their own packaging strategy -> https://github.com/ckeditor/ckeditor-dev/tree/major/dev/builder
