### ISSUE TITLE
feat: Use yarn instead of npm

### ISSUE THREAD

**Issue by wincent** [liferay/alloy-editor#1143]
As we start to use Yarn in more projects at Liferay, it might make sense to do the same for AlloyEditor, especially because some of the nice features that Yarn has like `yarn upgrade-interactive`.

Disclaimer: obviously need to make sure that this is compatible with the portal build process, which may assume `package-lock.json` etc.

**Comment by julien** [comment]
Would it makes even more sense since we're using this in the `website` branch?

**Comment by wincent** [comment]
I think so. In practice both NPM and Yarn provide quite good experiences, but the workspaces feature of Yarn is very useful and is one of the main motivations for using it in certain places (eg. monorepos like Clay). I also think there's value in consistently, which means if we use it in those places (like the "website" branch) then it'd be a good move to use it consistently everywhere if we can.

**Comment by julien** [comment]
As a follow up, concerning yarn workspaces, what are your thoughts on having the editor and website in separate packages?

**Comment by wincent** [comment]
Seems they are and should be separate, living on separate branches. What were you thinking about here?
