### ISSUE TITLE
Make it possible to run with non-minified CKEDITOR build

### ISSUE THREAD

**Issue by wincent** [liferay/alloy-editor#1150]
While working on #1148 some of the tests would end up throwing exceptions deep inside the minified CKEDITOR source. You can get the debugger to "pretty print", but it's still super hard to find your way around because all the variable names are minified, like in this sample snippet:

```
    function a(a) {
      var f = d(this);
      return f[a] || (f[a] = new b(a))
    }
    var d = function (a) {
      a = a.getPrivate && a.getPrivate() || a._ || (a._ = {
      });
      return a.events || (a.events = {
      })
    },
    b = function (a) {
      this.name = a;
      this.listeners = [
      ]
    };
    b.prototype = {
      getListenerIndex: function (a) {
        for (var b = 0, d = this.listeners; b < d.length; b++) if (d[b].fn == a) return b;
        return - 1
      }
    };
```

So, the idea would be to make a debug build that we use in `npm run test:debug` to make the debug experience better.

**Comment by blzaugg** [comment]
I would want do be a able to run a non-minified distribution as well. For example, in Portal.

**Comment by wincent** [comment]
@blzaugg: I think that would be doable. At the moment the portal requires CKEDITOR
and then uses the `alloy-editor-no-ckeditor-min.js` build [here](https://github.com/liferay/liferay-portal/blob/37e20bd0e38350e56a2de1aaacc507895d9e2202/modules/apps/frontend-editor/frontend-editor-alloyeditor-web/src/main/resources/META-INF/resources/resources.jsp#L38).

So to be able to use a non-minified CKEDITOR in portal two things would be required:

1. Teach webpack to make a non-minified build for us; should be relatively straightforward and similar to what is visible in this #1155 and #1156.
2. Update 
[this line in the portal repo](https://github.com/liferay/liferay-portal/blob/37e20bd0e38350e56a2de1aaacc507895d9e2202/modules/apps/frontend-editor/frontend-editor-alloyeditor-web/src/main/resources/META-INF/resources/resources.jsp#L36) to conditionally require the minified build instead when debugging. I'm new to that code base so I don't know exactly how you'd do that; might be by setting a property in the `bundles/portal-ext.properties` file alongside your portal checkout.

I guess if you were running with non-minified CKEDITOR, you'd probably also want to run non-minified AlloyEditor at the same time too.

I created an internal ticket to track this: https://issues.liferay.com/browse/IFI-488
