### ISSUE TITLE
.eslintrc gets created each time we install dependencies

### ISSUE THREAD

**Issue by julien** [liferay/alloy-editor#1167]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

Currently in the `master` branch, each time we install dependencies with `npm i` or `yarn install` an `.eslintrc` file is created in the root of the repo.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1) Run `yarn install` on the `master` branch and wait till it terminates correctly.
2) Run `git status` and you should see an untracked file named `.eslintrc`

**What is the expected behavior?**

The expected behaviour is that this file should not be created.

The reason for which it's created is pretty simple, we're using [eslint-config-liferay](https://github.com/eduardolundgren/eslint-config-liferay/) as a dependency and it uses a `postinstall` npm script which [creates the file if it isn't present](https://github.com/eduardolundgren/eslint-config-liferay/blob/master/scripts/postinstall.js#L8-L16).

We can either remove this dependency because it's looks more related to liferay-portal than to this project or send a pull request and disable the postinstall script.

**Which versions of alloy-editor, and which browser / OS are affected by this issue? Did this work in previous versions?**

I beleive this happened in [37d5e9ba](https://github.com/liferay/alloy-editor/commit/37d5e9ba) when we added the `eslint-config-liferay` dependency, previously in [f191f15a](https://github.com/liferay/alloy-editor/commit/f191f15a) the `.eslintrc.js` file add been created
(which is also a valid eslint configuration file, and it could also be .json)

**Comment by wincent** [comment]
See the internal ticket https://issues.liferay.com/browse/IFI-482 which is about getting "eslint-config-liferay" into the "liferay" GitHub org so that we can make the changes there. It's arguably a bug in the preset and so should be dealt with there.

**Comment by jbalsas** [comment]
That behaviour is actually a feature :D

The goal being that by installing the dependency, it would create the proper `.eslintrc` file, which could in turn even be `.gitignored` to avoid deviations.

I think an option could be to move to https://github.com/liferay/liferay-npm-tools/tree/master/packages/liferay-npm-scripts instead and use the `lint` script?

**Comment by wincent** [comment]
@jbalsas: But shouldn't it be checking for either `.eslintrc` or `.eslintrc.js` or `.eslintrc.json`?

**Comment by jbalsas** [comment]
Ah, yeah, that's a valid point, yes :)

**Comment by julien** [comment]
@jbalsas thanks for that explanation, I imagined this was done to prevent using an invalid config, but I was thinking the same as @wincent: we could update it to check for "all valid" eslint configuration files.

As for using the `liferay-npm-scripts` that might be a good option too, whatever fits our needs

**Comment by wincent** [comment]
Fix for this is up at: https://github.com/liferay/eslint-config-liferay/pull/15

There are a few more things to update in eslint-config-liferay before we cut a new release, but when we do, we should be able to switch to the new version here and then we'll be able to close this issue.
