### ISSUE TITLE
How disable image button when i want?

### ISSUE THREAD

**Issue by vncsms** [liferay/alloy-editor#1178]
Hi,
I'm developing a text editor like Medium or Wikipedia in AngularJS. But during the project i decide to not permit the user insert a image wherever he wants. Like Medium i will only enable the user insert an image in an empty `<p>`. But i don't know how do this, or even if is possible. Is there an way to add rules to buttons not appear?

Thanks.

**Comment by julien** [comment]
Hi @vncsms, 

Unfortunately, this feature is not implemented and doesn't seem very trivial to add, at the moment we don't have this planned on our roadmap.
