### ISSUE TITLE
Can't add content (images, video...) on Firefox.

### ISSUE THREAD

**Issue by 4lejandrito** [liferay/alloy-editor#1191]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When clicking on the plus button the different buttons to add content don't work on Firefox.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Click inside the editor.
2. Click +.
3. Click on the image button.

**What is the expected behavior?**
An image can be added. But nothing happens.
**Which versions of alloy-editor, and which browser / OS are affected by this issue? Did this work in previous versions?**
Firefox.

**Comment by julien** [comment]
Closed by #1193

**Comment by 4lejandrito** [comment]
Thanks @julien!
