### ISSUE TITLE
Add autocomplete to links

### ISSUE THREAD

**Issue by ipeychev** [liferay/alloy-editor#120]

**Comment by kushal** [comment]
Do you meant from a server provided list of links? FWIW, I have a local fork that does this which I'd be happy to try to merge, but I'm not sure how exactly you'd want me to inject the completions. If you had an outline of how you wanted this to work, I could try to move in that direction.

**Comment by ipeychev** [comment]
Well, currently there is an input field where the user can type the link URL.
One option is to make this a standard autocomplete component which supports server and client datasource. The buttons accept configurations, so the user will be able to configure the datasource via ButtonLinkEdit's configuration. In most cases, this will be the URL, which will return the results, or just an array with the data to be filtered in the client.
