### ISSUE TITLE
Migrate website away from WeDeploy

### ISSUE THREAD

**Issue by wincent** [liferay/alloy-editor#1212]
Right now I can't remember whether there were technical reasons why we can't host the website on GitHub pages — maybe there are, maybe there aren't — but just going to document the need to migrate away here within the next few weeks (WeDeploy will be [shutting down on 22 April 2019](https://wedeploy.com/blog/discontinuing-wedeploy/)).

If we move to GitHub pages, we probably have to enable it in the settings (sample screenshot from a repo of mine):

![Options](https://user-images.githubusercontent.com/7074/55333352-69015280-5497-11e9-8430-033204e49e6f.png)

In theory, we should be able to continue using the custom domain, [according to these docs](https://help.github.com/en/articles/using-a-custom-domain-with-github-pages). Failing that, the site would be available at https://liferay.github.io/alloy-editor/.

cc @jbalsas @julien

**Comment by blzaugg** [comment]
>  technical reasons why we can't host the website on GitHub pages — maybe there are, maybe there aren't 

I assumed it was to "drink your own champagne".

**Comment by wincent** [comment]
https://github.com/liferay/alloy-editor/pull/1233 is the last change required here. Going to close this now because it won't autoclose (only stuff merged to "master" will autoclose issues, and that PR is going to the "website" branch).
