### ISSUE TITLE
Toolbar for images is located at the top of the image but higher

### ISSUE THREAD

**Issue by ricardocousolr** [liferay/alloy-editor#1213]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After adding an image, selecting it will show the tool well above the image instead of just above it. This only happens is alloy-editor is loaded inside a portlet in POPUP mode.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
This can be reproduced using a Liferay 7.0 or 7.1 and adding a new web content (with html fields) via a Web Content Display.

**What is the expected behavior?**
The toolbar after selecting the image appears just on top of the image.

**Which versions of alloy-editor, and which browser / OS are affected by this issue? Did this work in previous versions?**
This should be reproducible in both 1.x and master branches.

**Comment by ricardocousolr** [comment]
See pr https://github.com/liferay/alloy-editor/pull/1218

**Comment by wincent** [comment]
That PR is in [v1.5.23](https://github.com/liferay/alloy-editor/releases/tag/v1.5.23) which is now up [on NPM](https://www.npmjs.com/package/alloyeditor), but this didn't autoclose because autoclosing only works on the "master" branch.
