### ISSUE TITLE
Advanced Editing Demo fails with console errors in IE11

### ISSUE THREAD

**Issue by blzaugg** [liferay/alloy-editor#1228]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Demo doesn't work and console errors in browser
```
SCRIPT1002: Syntax error
File: alloy-editor-all.js, Line: 36086, Column: 21
SCRIPT5009: 'AlloyEditor' is undefined
File: localhost:9000, Line: 109, Column: 13
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Following the steps from [Build it](https://www.alloyeditor.com/docs/develop/how-to-build-it.html) 
```
$ yarn install
$ yarn build
$ yarn start
```
2. Open http://localhost:9000/ in IE 11

**What is the expected behavior?**
Demo works with no console errors.

**Which versions of alloy-editor, and which browser / OS are affected by this issue? Did this work in previous versions?**
Windows 7 Internet Explorer 11

**Comment by blzaugg** [comment]
![Advanced Editing Demo IE 11](https://user-images.githubusercontent.com/1626739/56399014-8a38a180-6200-11e9-84af-9be72ec57b9a.gif)

**Comment by blzaugg** [comment]
The syntax error is from an arrow function that isn't transpiled to ES5:
```js
module.exports = () => {
	return {
		code: `module.exports = ${JSON.stringify(version)};`,
	};
};
```

**Comment by wincent** [comment]
Thanks for reporting this @blzaugg!

> The syntax error is from an arrow function that isn't transpiled to ES5:

I'm not sure if that's the function though; that file should only be evaluated as part of the build process, and should never wind up in the browser. We'll dig into it further though.

**Comment by wincent** [comment]
I'm afraid I can't repro this on IE 11 @blzaugg. Any ideas what might be needed to trigger? (I'm using IE 11 in a VirtualBox VM, hitting the webpack dev server that you get with `yarn start` on port 9000.

![Screen Shot 2019-04-23 at 16 53 42](https://user-images.githubusercontent.com/7074/56591209-95b50f80-65e8-11e9-861d-ec4309fa4549.png)

**Comment by gregory-bretall** [comment]
@wincent I was able to reproduce this on the most up to date master branch from today of alloy-editor, just by using yarn start. Not quite sure what the difference here is unless it's testing IE11 on Windows 10 potentially?

**Comment by wincent** [comment]
Ok, thanks for that @gregory-bretall. I tested on a Windows machine here and I see the fix that is required. It's a build-time fix and not a run-time fix — on Windows the build produces a bad result.

The reason I couldn't repro in the VM is that I wasn't running the build in Windows; I was running the build on Mac and hitting that from Windows.

**Comment by gregory-bretall** [comment]
That makes sense then, thanks for looking into it @wincent!

**Comment by blzaugg** [comment]
Thanks @gregory-bretall
