### ISSUE TITLE
Drag and Drop Handle is Difficult to See Against Text in IE11

### ISSUE THREAD

**Issue by gregory-bretall** [liferay/alloy-editor#1255]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The current behavior is that the drag and drop handle in IE11 can be difficult to see against text in IE11 due to it being having low opacity and also being positioned directly above the image, allowing it to overlap on text

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Start up an AlloyEditor instance in IE11
2. Add a multi-line paragraph of text
3. Add an image into the middle of the paragraph

**What is the expected behavior?**
The drag and drop handle is clearly visible again the text

**Which versions of alloy-editor, and which browser / OS are affected by this issue? Did this work in previous versions?**
It only affects IE11 as it's specific to the different drag resizer we use in IE11.

**Comment by julien** [comment]
Hi @gregory-bretall,

Thanks for reporting this issue.

I tried reproducing the issue but wasn't able to see what was wrong, and although there are some changes in pr #1256 I don't see any difference in alloy-editor's behaviour compared to master.

Could you possibly send a .gif or a screenshot of this issue to help me understand.

Thanks!

**Comment by gregory-bretall** [comment]
@julien I have gathered 2 sets of before and after screenshots displaying the difference in visibility before and after my change for both default AlloyEditor and AlloyEditor in Liferay (the use in Liferay is why I chose white instead of the default gray but I can change back) 
[before_and_after_drag_handles_ie11.zip](https://github.com/liferay/alloy-editor/files/3133320/before_and_after_drag_handles_ie11.zip)
