### ISSUE TITLE
Alloy Editor doesn't work

### ISSUE THREAD

**Issue by febrynas** [liferay/alloy-editor#1260]
Hi,

I have followed all steps to install and use alloy-editor but no luck
It would be appreciated if somebody can take a look my code (Please find attachment)

Thanks in advance
Febry
[PageBuilder.zip](https://github.com/liferay/alloy-editor/files/3144521/PageBuilder.zip)

**Comment by julien** [comment]
Hi @febrynas,

Thanks for reporting this issue. 

I just checked the code in the attached .zip file and you're right: it "doesn't work".

I made a simple change to make it working, in your `Index.html` file I added a `script` tag with the following content:

```javascript
<script>
  var CKEDITOR_BASEPATH = '/alloy-editor/';
</script>
```

As you can see in this screenshot that should fix it.

![2019-05-05-134618_1920x1080_scrot](https://user-images.githubusercontent.com/5572/57193590-e27bdd00-6f3c-11e9-87c7-04b6c1804d7b.png)

I also saw that this was missing in the "use" [page](https://alloyeditor.com/docs/use/use.html) so we'll make an update to this.

**Comment by febrynas** [comment]
Hi Julien

Cool... it works now

Thanks
