### ISSUE TITLE
Clean CKEditor plugin dependencies

### ISSUE THREAD

**Issue by jbalsas** [liferay/alloy-editor#127]
Right now, AlloyEditor uses a bundled version of CKEditor and incorporates some of its plugins. It currently is importing Paste From Word > Clipboard > Dialog

Would be good if we can get rid of the last two dependencies, or at least dialog, since we're not using the UI.

**Comment by jbalsas** [comment]
Hey @ipeychev, I've marked this issue for the `1.0.0` milestone, not so much to work on it but to discuss about it.

I'll look into it, but maybe it's not so bad that we bundle the `Dialog` plugin by default? It makes it simpler to bring new plugins into your CKEditor distribution since you don't have to download it separately as well, and most of the plugins out there require it.

What do you think?

**Comment by ipeychev** [comment]
It depends, how big it is?

**Comment by jbalsas** [comment]
Too much, I guess :cry: 

However, the alternatives to keeping it by default would be:
- Patch or fork the `Clipboard` plugin without the `Dialog` dependency
- Patch or fork the `Paste from Word` plugin without the `Clipboard` dependency
- Remove the `Paste from Word` plugin from our default build

I really don't want to keep any more duplicated plugins, so I'd vote for either keeping the dependencies in, for now, or not bundling any features that depend on them for now.

What do you think?

**Comment by jbalsas** [comment]
Removing the `1.0.0` milestone for now... will have to take a closer look again in later versions...

**Comment by wincent** [comment]
Doing some "spring cleaning" by closing issues that were opened in 2015 — much has changed since then and there have been many releases, so there is a risk that these older issues have grown very stale and are very unlikely to be acted upon. Please feel free to commend and we can look at re-opening on a case-by-case basis.
