### ISSUE TITLE
IE11 does not interpret/strips other browser's sizing via style attribute

### ISSUE THREAD

**Issue by SpencerWoo** [liferay/alloy-editor#1275]
https://issues.liferay.com/browse/LPS-96076

introduced with https://github.com/liferay/alloy-editor/issues/898 https://github.com/liferay/alloy-editor/commit/18ac73d6f065ab0c68919b8e58247aee222e3f1a

**Current behavior**

IE removes styles from images.  The size utilizes the style in other browsers.  IE doesn't interpret/strips other browser's sizing.

**Expected behavior**

IE interprets other browser's sizing.

**Comment by wincent** [comment]
Seems like this one can be closed now (thanks to #1276).
