### ISSUE TITLE
React UI Edit Link should move cursor after link creation

### ISSUE THREAD

**Issue by jbalsas** [liferay/alloy-editor#128]
In the ReactUI, after creating a link, the selection is retained and the link button shows. It would be better if the selection was moved after the created/updated link so the user can keep writing.

**Comment by jbalsas** [comment]
Hey @ipeychev,

Now that we've changed the link selection, it could make sense to rethink this. This is the current state:

- After creating a new link, we change the selection to get all the element. This now causes the text selection buttons to show in the styles toolbar. (this looks good to me)
- After updating an existing link, we keep the empty selection, so the edit UI doesn't go away. 

The way I see it, we could either select the link on update to match the create behaviour, or advance the cursor to the next position after the link as suggested in #387 to dismiss the styles toolbar.

What do you think?

**Comment by ipeychev** [comment]
Hey Chema,

I would expect the toolbar to disappear in both cases. After all, the primary operation - creation/editing the link has been completed. After creation, it is quite unusual to modify the style, so despite it is convenient that the toolbar stays there, I feel that most of the users won't touch it, so probably this will only force them to click one more time.
On editing, is the same logic. The goal - link editing has been completed, so I would expect the toolbar to disappear.

Thanks,

**Comment by jbalsas** [comment]
Hey Iliyan,

Makes sense, it's also aligned with what was being asked in #387.

Will work on that direction then :blush:
