### ISSUE TITLE
Missing tooltips for the Video and Audio icons in the toolbar

### ISSUE THREAD

**Issue by rolandpakai** [liferay/alloy-editor#1281]
https://issues.liferay.com/browse/LPS-97988

**Current behavior**
After installing Xuggler in Liferay the Video and Audio buttons appearing in the toolbar,
but without any tooltip.

**Expected behavior**
Show tooltip for the Video and Audio buttons.

**Affected version**
It is affected by the latest 2.0.7 version

**Affected browser**
It is affected by all the browsers

**Comment by wincent** [comment]
Closed by https://github.com/liferay/alloy-editor/pull/1282
