### ISSUE TITLE
Table toolbar is broken in Firefox

### ISSUE THREAD

**Issue by rolandpakai** [liferay/alloy-editor#1283]
https://issues.liferay.com/browse/LPS-97492

Current behavior
The tabe toolbar is not working on Firefox: can not click on the button's drop down list items

Expected behavior
Tooltip button's drop down list is usable

Affected version
1.5.24

Affected browser
Only Firefox

**Comment by wincent** [comment]
Fixed by: https://github.com/liferay/alloy-editor/pull/1293
