### ISSUE TITLE
Alloy Editor Demo possibly not working in IE11

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#1287]
Not sure if it's my browser at this stage or the demo itself but no toolbars come up when clicking or selecting text in IE11.

**Comment by wincent** [comment]
Thanks for the report @duracell80. Just testing it in IE 11 (11.885.17134.0) on our trusty Lenovo laptop here, toolbars are working in the demo.

I'm going to close this for now but if you come up with a reliable repro please comment and we'll re-open.
