### ISSUE TITLE
IE11 Image wrong alignment after center alignment

### ISSUE THREAD

**Issue by fortunatomaldonado** [liferay/alloy-editor#1315]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Image is not able to be inline with text after setting and then removing center alignment on an image in IE11
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Start Demo
2. Add a line of text and then add an image
3. Center align the image and then remove the alignment
4. Now drag and drop the image in the middle of the text

**What is the expected behavior?**
Expected Result: Image is inline with the text
Actual Result: The image is now left aligned

**Which versions of alloy-editor, and which browser / OS are affected by this issue? Did this work in previous versions?**
IE11
I believe this could be a start into looking at the way different browsers deals with alignment and styling from https://github.com/liferay/alloy-editor/pull/1298

**Comment by markocikos** [comment]
I'm closing this, as we no longer support IE11.
