### ISSUE TITLE
IE11 Drag Resizer Not Working on Top Line

### ISSUE THREAD

**Issue by gregory-bretall** [liferay/alloy-editor#1316]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When adding an image in IE11, the drag resizer is placed above the image, making it so that the drag handler appears outside of the editor when placed on the top line.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Most easily reproducible in Liferay, see steps on https://issues.liferay.com/browse/LPP-34775.

**What is the expected behavior?**
Drag handler is visible and accessible from any point in the editor.

**Which versions of alloy-editor, and which browser / OS are affected by this issue? Did this work in previous versions?**
Affects IE11 only.

**Comment by markocikos** [comment]
Closing, we no longer support IE.
