### ISSUE TITLE
Necessary files are not being loaded correctly in the demo page

### ISSUE THREAD

**Issue by cleydyr** [liferay/alloy-editor#1337]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
Files needed to use Alloy Editor correctly are not being loaded. Among them, config.js, editor.css and pt-br.js.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Install `alloyeditor` via npm or yarn
2. open node_modules/alloyeditor/dist/index.html in your browser

**What is the expected behavior?**
The demo page with an editor will work properly as in the site demo. You can select a text and see that the popup toolbar appears.

**Which versions of alloy-editor, and which browser / OS are affected by this issue? Did this work in previous versions?**
* Chrome version 77.0.3865.120
* MacOS X Catalina 10.15 (19A602)
Couldn't test if it worked in previous versions yet.

**Comment by wincent** [comment]
My understanding is that the demo is working as intended.

You can either:

- Use the built-in demo on the front page of [alloyeditor.com](https://alloyeditor.com/); this is the one that is [linked to from the project README.md](https://github.com/liferay/alloy-editor/blob/master/README.md#demo); or:
- You can run the demo yourself from the repo with `yarn start`, as documented here: https://alloyeditor.com/docs/develop/how-to-build-it.html

I don't know if we've ever supported running it directly out of the index.html file in node_modules, but I don't think we want to at this time.
