### ISSUE TITLE
Alloy on Angular?

### ISSUE THREAD

**Issue by danbatistar4** [liferay/alloy-editor#1353]
Is there any possibility this editor could be used on Angular 8? I really liked the editor's features, but it isn't compatible with the framework I'm using.

**Comment by julien** [comment]
Hi @danbatistar4, 

Unfortunately, we aren't planning to implement anything related to angular, that said you might find this project interesting: https://github.com/thiagogarbazza/angular-alloyeditor although it seems that it was developed for AngularJS (1.x)
