### ISSUE TITLE
Readme states Works on IE9+

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#1357]
This editor doesn't yet work in IE period. Particularly in regards to images.

**Comment by wincent** [comment]
Thanks for pointing that out @duracell80. I removed the references to IE9 from the website back in April last year (https://github.com/liferay/alloy-editor/pull/1244) as part of https://github.com/liferay/alloy-editor/issues/1243, but I missed this one in the README.

Let's remove that from the README, and deal with the image problems (and any others that might come up) in the related specific issues ([these are the issues currently tagged with the IE label](https://github.com/liferay/alloy-editor/issues?q=is%3Aissue+is%3Aopen+label%3A%22browser%3A+ie%22)).
