### ISSUE TITLE
Demo doesn't contain all features

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#1364]
Demo on alloyeditor.com doesn't provide enough features to evaluate the editor for fitness for use.

Missing from on site demo:
- Blockquote
- Text Alignment
- Code
- Strike
- Sup and Sub
- Bullet list
- Numbered list
- Twitter
- Can't add an image

Much needed features
- Text size (even based on rem)
- Text color (allow dev to set colors from CSS vars in a limited swatch palate)

CSS Vars
https://stackoverflow.com/questions/1875852/how-can-i-define-colors-as-variables-in-css
https://www.w3schools.com/css/css3_variables.asp

Missing features in general
- Can't resize image via text input of dimensions
- Can't update alt text in demo (known to exist)
- Can't link an image in demo (known to exist)

Demo is almost useless

**Comment by wincent** [comment]
Thanks for opening the issue @duracell80.

The demo on alloyeditor.com isn't intended to showcase every feature of the editor, but rather offer a quick "test drive" experience. To evaluate it more fully, we'd recommend using the much more comprehensive demo page that you can see when you clone the repo and run `yarn start`.

I'm going to close this issue because we don't have any plans to change the online demo.

**Comment by duracell80** [comment]
That's crazy. How would non technical people like product analysts without development experience get all features working?

Perhaps it's a sign that this edit lacks features required.

**Comment by wincent** [comment]
No, not crazy; just fruit of the fact that our goal in embedding a demo version of the was not to provide a platform for exhaustively evaluating every aspect of the project.

I definitely wouldn't recommend choosing a developer-facing package like AlloyEditor without the involvement of technical people.

As far as whether the feature set is adequate, that seems an orthogonal question to the issue of what functionality should be enabled in the demo. Please open issues if there are specific features that you would find useful and which aren't already being tracked.

Thanks once again!
