### ISSUE TITLE
Editor doesn't live up to promise of creating gorgeous content

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#1365]
So many formatting issues and missing features hold back the editor from achieving its stated goal. Only basic paragraphs can be manipulated. Difference between the editing mode and what is seen in the actual content, attributed to lack of style functionality in the editor itself.

Beautiful content can't be created and the experience is not peaceful.

![this-is-basic](https://user-images.githubusercontent.com/18121278/73202129-07823280-4100-11ea-8ee5-feefdd1933cc.jpg)

**Comment by duracell80** [comment]
Lack of padding around images is just the start of the problems with this editor ...

![lack-of-padding](https://user-images.githubusercontent.com/18121278/73202261-47491a00-4100-11ea-9c62-2758f702b86a.jpg)

**Comment by wincent** [comment]
Thanks for your ongoing input @duracell80 highlighting the limitations and problems with the editor. We want to keep the issue tracker for well-defined, actionable issues, so, while an issue like "Editor doesn't live up to promise of creating gorgeous content" is an accurate description of how the editor falls short, it isn't sufficiently specific for us schedule and prioritize work related to it.

If you wanted, we could split the specific problems off into more concrete issues (one for padding around images, for example). In the meantime, however, I'm going to close this one.

**Comment by duracell80** [comment]
No, you guys need to get real about Quality Assurance.

**Comment by wincent** [comment]
I get that you're frustrated with the quality and completeness of the project, @duracell80. As you know, however, real products developed by real companies are built within constraints: we have finite resources and an almost infinite list of things that we could be working on — we have to direct our efforts where we believe they'll be most useful. One of the necessary inputs into that decision-making and prioritizing process is having specific, actionable requests (bug reports and feature requests); you've already provided us with many such requests over the years, and we're thankful for that, but with respect to this specific issue, I can only repeat what I said above:

> We want to keep the issue tracker for well-defined, actionable issues, [this] isn't sufficiently specific for us schedule and prioritize work related to it.

Please feel free to create one or more specific issues for the things that you consider most important. Thanks once again Lee.
