### ISSUE TITLE
Dev Documentation Contradicts UI Frameworks

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#1366]
Contraction in
https://alloyeditor.com/docs/develop/about.html

"It should be easy to create a new UI. The default one uses React. However, if a developer wants to use another Framework, or to create UI using vanilla JavaScript and CSS, that should be possible.

Currently, AlloyEditor supports only one UI: React. Please feel free to contact us if you want to contribute another UI."

_Also_

"Although AlloyEditor uses the CKEditor core, its dependency is quite small. If there is a better base or we reach the point when creation of a new core would be easier, nothing prevents us from replacing the CKEditor core with our own."

Yet TinyMCE hasn't been implemented as the superior base editor.

**Comment by wincent** [comment]
Thanks again @duracell80 for pointing out where the editor falls short of the bar.

With respect to the documentation, I seems it has given you the impression that we're claiming that AlloyEditor, right now, can be used with other UI frameworks, and with a different editor dependency than CKEditor. However, that's not the intention of the language that you've quoted: it's actually intended to be a description of the design philosophy — ie. that there is nothing in the implementation that would prevent such architectural changes from being made, should we or anybody else decide to make them. But at this time, we definitely haven't made any effort to provide a non-React UI integration, nor have we attempted to plug in a non-CKEditor core.

If you have any ideas for how this could be made clearer in the docs, please feel free to comment with suggestions or an actual PR with a proposed update. Thanks once again.

**Comment by duracell80** [comment]
Isn't that misleading?

**Comment by wincent** [comment]
I don't think so. I believe we're using words like "should" and "possible" consistently with the broadly understood meanings of those words as used in the English language.

If you have concrete ideas for how to improve the docs though, please do share them via a PR like I suggested above. Thanks once again.
