### ISSUE TITLE
React UI RemoveFormat Button does not remove all format

### ISSUE THREAD

**Issue by jbalsas** [liferay/alloy-editor#137]
The RemoveFormat button in the ReactUI does not remove all format elements such as headings. This is caused by the configuration variables

```javascript
CKEDITOR.config.removeFormatTags = 'b,big,cite,code,del,dfn,em,font,i,ins,kbd,q,s,samp,small,span,strike,strong,sub,sup,tt,u,var';
CKEDITOR.config.removeFormatAttributes = 'class,style,lang,width,height,align,hspace,valign';
```

They should be updated to cover a more generic case

**Comment by jbalsas** [comment]
The `removeFormat` command works only on inline elements by design, as stated in the [documentation](http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-removeFormatTags) and in this [issue](http://dev.ckeditor.com/ticket/4675) closed as invalid.

**Comment by jbalsas** [comment]
In google docs, the `RemoveFormat` button does not remove headings neither, so this could actually be closed as invalid too...

**Comment by ipeychev** [comment]
Fixed
