### ISSUE TITLE
Fix: Regression of #1218 toolbar location for image

### ISSUE THREAD

**Issue by rolandpakai** [liferay/alloy-editor#1385]
**Do you want to request a _feature_ or report a _bug_?** 
Bug

**What is the current behavior?**
In a dialog-iframe-modal window the image toolbar is placed wrong: much higher than the top of the image

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
https://issues.liferay.com/browse/LPP-36573
1) Start a Liferay 7.0.x bundle 
2) Add a Web Content Display onto the page and add a new Basic Web Content by clicking on the top-right icon of the portlet
3) In the Content field add few line text 
4) When you have reached ~20 lines, add a new image into the editor
5) Once the image has been added, click on it

**What is the expected behavior?**
The image toolbar is placed top of the image.

**Which versions of alloy-editor, and which browser / OS are affected by this issue? Did this work in previous versions?**
Latest alloy-editor
In all browser

**Comment by julien** [comment]
Fixed by #1386 71cab17923c9ad4e9c322c008977ed7bf02fdf67
