### ISSUE TITLE
Alloyeditor doesnt send value to server on submit

### ISSUE THREAD

**Issue by rahulahoop** [liferay/alloy-editor#1401]
**Do you want to request a _feature_ or report a _bug_?**
bug
**What is the current behavior?**
if i use the liferay-editor tag and specifiy alloyeditor in the attribute, the input i type is not sent in the form.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
create a form in jsp and action command to submit to
then an editor tag and specify a alloyeditor
submit the form and check for the parameter value in the action command. its not there

`    <liferay-editor:editor
            contents="<%=TextEn%>"
            name="text-en"
            editorName="alloyeditor"
            width="100%"
            resizable="true"/>`

**What is the expected behavior?**
That the value inputted in the editor is returned in the form.
**Which versions of alloy-editor, and which browser / OS are affected by this issue? Did this work in previous versions?**
LR 7.3.1

https://issues.liferay.com/browse/LPS-109514

**Comment by wincent** [comment]
I don't think there's anything we can do immediately here on the GitHub project. The right place to investigate this is in the context of DXP, so the discussion should probably take place on that LPS ticket that you linked.

**Comment by jbalsas** [comment]
Editor doesn't submit the contents, everywhere we use WYSWYG editors, someone moves the content to the form on `formSubmit`.

**Comment by rahulahoop** [comment]
> Editor doesn't submit the contents, everywhere we use WYSWYG editors, someone moves the content to the form on `formSubmit`.

how do you get the contents of a alloyeditor in jsp context ?

**Comment by jbalsas** [comment]
` window.<portlet:namespace />bodyEditor.getHTML()` where `bodyEditor` is the `name` you pass if you're using the `liferay-ui:input-editor` tag (which I assume it's what you're doing)

**Comment by jbalsas** [comment]
I'll answer in the LPS since this has nothing to do with AlloyEditor. We can continue over there if you have additional doubts.

Thanks!
