### ISSUE TITLE
dragresize_ie plugin overrides CKEDITOR.plugins.image2

### ISSUE THREAD

**Issue by julien** [liferay/alloy-editor#1420]
**Do you want to request a _feature_ or report a _bug_?**

This is neither a _feature_ request or a bug _report_ it's a question

**What is the current behavior?**

When building [`liferay-ckeditor`](https://github.com/liferay/liferay-ckeditor) with CKEditor's `image2` plugin an error is thrown with the following message

`Uncaught TypeError: helpers.stateShifter is not a function` 

As can been seen in the following screenshot

![error01](https://user-images.githubusercontent.com/5572/90246161-3f4e8e80-de34-11ea-98c5-0cb4c9e9de08.png)

If I put a breakpoint on the the line that is throwing the error, it seems that the problem is that the `helpers` object does not have a `stateShifter` function, which the `image2` plugin is trying to invoke:

![error02](https://user-images.githubusercontent.com/5572/90246351-c3a11180-de34-11ea-830d-ca7e2e01d82e.png)

What's interesting is that this `helpers` object point to the [`dragresize_ie`](https://github.com/liferay/alloy-editor/blob/a4e8d1e9ab4a1c54f7c4858f624610575137e9a3/src/plugins/dragresize_ie.js) plugin:
 
When you look at the source of the `dragresize_ie` plugin, you'll notice that it [overrides](https://github.com/liferay/alloy-editor/blob/a4e8d1e9ab4a1c54f7c4858f624610575137e9a3/src/plugins/dragresize_ie.js#L431) the `CKEDITOR.plugins.image2` object.

I've got several doubts that I'd like to discuss:

1 - Should the `dragresize_ie` plugin be bundled with `alloyeditor` ?

By default `alloyeditor` uses it's `ae_dragresize` plugin, but if the browser is IE or Edge it does something different:  with IE 11 or Edge it will use the `ae_dragresize_ie11` plugin and otherwise (IE < 11) it will use `ae_dragresize_ie`.
This can be seen [here](https://github.com/liferay/alloy-editor/blob/a4e8d1e9ab4a1c54f7c4858f624610575137e9a3/src/adapter/core.js#L83-L95) - As far as I understand we still want `alloyeditor` to support IE<11 but I just want to make sure it's still the case

2 - Is it expected that the `ae_dragresize_ie` plugin overrides `CKEDITOR.plugins.image2`

After looking at the [`dragresize_ie11`](https://github.com/liferay/alloy-editor/blob/a4e8d1e9ab4a1c54f7c4858f624610575137e9a3/src/plugins/dragresize_ie11.js) and more specifically [this](https://github.com/liferay/alloy-editor/blob/a4e8d1e9ab4a1c54f7c4858f624610575137e9a3/src/plugins/dragresize_ie11.js#L581) line and also checking the [`dragresize`](https://github.com/liferay/alloy-editor/blob/a4e8d1e9ab4a1c54f7c4858f624610575137e9a3/src/plugins/dragresize.js) I concluded that overriding `CKEDITOR.plugins.image2` was not expected. I also made a local modification to avoid this override (by renaming `CKEDITOR.plugins.image2` to `CKEDITOR.plugins.ae_dragresize_ie`) and it fixed the error. 
But before submitting any pull request I just wanted to make sure this made sense.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Enable the CKEditor `image2` plugin, by editing [**liferay-ckeditor**](https://github.com/liferay/liferay-ckeditor/)'s [build-config](https://github.com/liferay/liferay-ckeditor/blob/748a32556a9d9fce7eb8be8c57c8c63c6f8b6284/support/build-config.js) and include the `image2` plugin
2. Build **liferay-ckeditor** and use it in a `liferay-portal`
3. Deploy the `frontend-editor-ckeditor-web` module
4. Navigate to **Blogs** and add a new blog entry

**What is the expected behavior?**

CKEDITOR plugins should work whether they are bundled in **liferay-ckeditor** build or used as `extraPlugins`

**Which versions of alloy-editor, and which browser / OS are affected by this issue? Did this work in previous versions?**

So far, I've only observed this error in a `liferay-portal` environment:

A build of `liferay-ckeditor` that includes the `image2` plugin + `alloyeditor` (which ever version is used in `liferay-portal`)  
This does not happen when using the `image2` plugin is used as an `extraPlugin`

**Comment by wincent** [comment]
> As far as I understand we still want `alloyeditor` to support IE<11 but I just want to make sure it's still the case

No way. As noted [here](https://github.com/liferay/alloy-editor/issues/1161), IE11 is our baseline, and we have tried to remove all references to prior versions from our docs ([example](https://github.com/liferay/alloy-editor/pull/1363)).

Feel free to kill anything pre-IE11 with fire.

**Comment by julien** [comment]
@wincent thanks for the heads up. I'll work on that
