### ISSUE TITLE
Where is the react example?

### ISSUE THREAD

**Issue by philmetzger** [liferay/alloy-editor#1437]
At this link for a react component of alloy-editor it says check out the examples: https://alloyeditor.com/docs/use/react_component.html

But where are the examples?

**Comment by kastamas** [comment]
Yeah
Same problem

**Comment by wincent** [comment]
Those docs are very stale now and unlikely to ever be updated again. My guess is that the repo they mention has been archived — I couldn't find any trace of it. Or perhaps they were aspirational and we never published such an example.

Probably the most obvious and current React example is in AlloyEditor's own website, [which you can see in the source here](https://github.com/liferay/alloy-editor/blob/website/src/pages/index.js).
