### ISSUE TITLE
Security issue for ckeditor < 4.15.1

### ISSUE THREAD

**Issue by alk-mandrianarijaona** [liferay/alloy-editor#1484]
**Do you want to request a _feature_ or report a _bug_?**
This is a security enhancement

**What is the current behavior?**
alloyeditor is using ckeditor 4.14.1 and has security vulnerability as described at https://github.com/ckeditor/ckeditor4/blob/major/CHANGES.md#ckeditor-4151

**Comment by jonmak08** [comment]
This issue has been fixed as https://github.com/liferay/alloy-editor/releases/tag/v2.13.0.

Please let me know if you have any questions. Thanks!
