### ISSUE TITLE
The attribute "rel" is not automatically added to the generated links

### ISSUE THREAD

**Issue by orsolyaDekany** [liferay/alloy-editor#1521]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
When generating links in AlloyEditor, "rel" attribute is not added automatically to the links which may prevent tabnabbing attacks.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. In AlloyEditor, write some text and highlight it to allow the toolbar to appear and click on the Link button
2. Choose any of the target value (eg.: "_blank") and paste a link and approve the change
3. Go to the code/source view of the editor

**What is the expected behavior?**
'rel' attribute is added to the link, eg.: <a href="https://www.liferay.com/en/home" **rel="noopener noreferrer"** target="_blank">Liferay</a>

**Which versions of alloy-editor, and which browser / OS are affected by this issue? Did this work in previous versions?**
All AlloyEditor version
Any Browser/OS

**Comment by markocikos** [comment]
Fixed in https://github.com/liferay/alloy-editor/pull/1522
