### ISSUE TITLE
Border causes a shifted layout when clicking on the plus icon

### ISSUE THREAD

**Issue by orsolyaDekany** [liferay/alloy-editor#1529]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
Border style causes a layout shift when clicking on the plus icon on the first click.
https://issues.liferay.com/browse/LPS-155757

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![issue](https://user-images.githubusercontent.com/69793575/172911967-ac116169-fb6d-40ba-ac93-9ef9be37903d.gif)

**What is the expected behavior?**
Layout is not shifted on click.

**Which versions of alloy-editor, and which browser / OS are affected by this issue? Did this work in previous versions?**
All AlloyEditor version
Any Browser/OS

**Comment by markocikos** [comment]
Fixed in https://github.com/liferay/alloy-editor/pull/1530
