### ISSUE TITLE
Create button for applying color to the text

### ISSUE THREAD

**Issue by ipeychev** [liferay/alloy-editor#215]
Currently there is no button for applying colors to the text.

**Comment by Mcsky17** [comment]
Hey, 
This library work well, but the change text color feature is important. Why don't you implement it ? 
Thank in advance for your response

**Comment by ipeychev** [comment]
Not for any reason, but because after that we implemented the possibility for the user to use (almost) any CKEditor button. You may read how [here](http://alloyeditor.com/guides/how_to_use_ckeditor_plugins/)

Thanks,

**Comment by wincent** [comment]
Closing because this is unlikely to be prioritized at this point.
