### ISSUE TITLE
Publish on NPM/Bower?

### ISSUE THREAD

**Issue by OtaK** [liferay/alloy-editor#217]
Is it possible to publish the project on NPM and Bower at least?

It would be really great, and benefitting the project in all the ways possible. (SemVer, ease of building into app assets, ease of integration with existing React project, and so on)

**Comment by ipeychev** [comment]
Hello,

Yeah, we could, that is a good idea and something we can definitely consider!

Could you please give us some more information about how are you planning to use it if we publish it as Bower component or NPM module?

Thanks,

**Comment by OtaK** [comment]
Hi,

Thanks for answering :)

For my case, depending on where it is integrated : 
* NPM: I would bundle Alloy into my existing React setup with the help of browserify/webpack
* Bower: I would simply add Alloy's dist JS file (the one without React bundled) to my gulpfile's JS build pipeline.

Both cases are fine with me.

Have a great day,

**Comment by tennisonchan** [comment]
Hi there,

By making it accessible in npm and bower, It will definitely help Alloy editor more developers. So a big +1.

**Comment by ipeychev** [comment]
Okay, you convinced me. Will publish it to both of these :)

**Comment by daemonsy** [comment]
:+1: Thanks @ipeychev!

**Comment by OtaK** [comment]
@ipeychev I guess a bower package first would be easier. Just have to create a bower.json and publish it.
I took a look at the source and I think some modifications will be necessary to make it a proper NPM package. (such as moving some depencencies such as gulp* as devDependencies, and modifying module exports)

**Comment by growlsworth** [comment]
Hey @ipeychev, any chance you could still [publish to npm](https://docs.npmjs.com/getting-started/publishing-npm-packages)?

**Comment by ipeychev** [comment]
On Jun 18, 2015 1:32 AM, "Thomas Shafer" <notifications@github.com> wrote:
>
> Hey @ipeychev, any chance you could still publish to npm?

Yes, this is on the roadmap. Bower was easy and for NPM we postponed it.

Could I ask how are you planning to use it if we publish it as an NPM
package?

Thanks,

**Comment by growlsworth** [comment]
Hello @ipeychev 

Thanks for your quick response. I would like to use AlloyEditor like this:

```javascript
AlloyEditor = require('alloy-editor');
// perhaps other formats like:
// AlloyEditor = require('alloy-editor/without-react');

//then in my component
render: function(){
  return (<div contentEditable={true} ref="editableDiv" id="my-div" />)
},
componentDidMount: function(){
    AlloyEditor.editable(React.findDOMNode(this.refs.editableDiv));
    //or AlloyEditor.editable('my-div');
}
```

I personally use [webpack](https://webpack.github.io) for packaging my assets. I think it's a pretty popular asset packaging tool and would make sense to support.

Thanks! I love the mission of AlloyEditor.

**Comment by growlsworth** [comment]
I should note it would also be awesome to have something like:

```javascript
//require a React component to directly use.
AlloyEditorComponent = require('alloy-editor').Component

//then in my component
render: function(){
  return (<AlloyEditorComponent />);
  // then you could just pass options to the component.
}
```

This would need to be isomorphic. But it could hide the previous example code.

Thanks.

**Comment by ipeychev** [comment]
Okay. That should be doable. We already wrap the files in different ways -
for the browser there is one template, when we execute the tests (via Node)
the wrapping is different. We will take look on this.

**Comment by ipeychev** [comment]
I just checked the situation and it is possible to make AlloyEditor core to run in NodeJS environment without many issues.
However, that is only one side of the question. From what I saw, it seems that CKEditor's engine does not work in non-browser environment - they need window and document, they load files via Ajax and so on.
Since AlloyEditor relies on it, on practice this means it cannot run in non-browser environment neither.

Any ideas how to workaround this situation would be very well welcomed.

**Comment by growlsworth** [comment]
Hey @ipeychev,

I think if you follow the design pattern of: https://github.com/liferay/alloy-editor/issues/217#issuecomment-113225634 , that should enable you to only load CKEditor on the client. `componentDidMount` only executes on the client and not on React's [renderToString](https://facebook.github.io/react/docs/top-level-api.html#react.rendertostring).

**Comment by ipeychev** [comment]
Yeah, the point is that the code of AlloyEditor consists from CKEditor plugins and UI. Since these plugins rely on CKEditor's engine, we have to prevent them from executing

**Comment by ipeychev** [comment]
Yeah, however it is not only CKEditor. The code of AlloyEditor consists from CKEditor plugins and UI. Since these plugins rely on CKEditor's engine, we have to prevent them from executing on the server too. This should be doable however so I reopened this issue.

**Comment by matrinox** [comment]
Can you still publish the package for npm for use in client-side apps strictly?

**Comment by ipeychev** [comment]
Yes, will do this today.

**Comment by ipeychev** [comment]
Done

**Comment by nicolasiensen** [comment]
I'm also looking forward to use AlloyEditor as a React component, just like @growlsworth [pointed](https://github.com/liferay/alloy-editor/issues/217#issuecomment-113226178). Any progress on it?

**Comment by ipeychev** [comment]
Not yet, sorry. We would appreciate a pull request too.

**Comment by matiaslarsson** [comment]
+1

**Comment by ipeychev** [comment]
Hey guys,

I created today a [branch](https://github.com/liferay/alloy-editor/tree/react) where AlloyEditor can be rendered on the server and still to work in the browser. The goal is to see if what I did works for you or more work is needed. Here is an example how this could be used:

```javascript
var React = require('react'); // React should be loaded separately for now
var AlloyEditor = require('./alloy-editor-all').AlloyEditor; // here any of AlloyEditor's files can be required

// This class will render an element on the server, but in the browser it will create an instance of
// AlloyEditor (when mounted) and it will destroy it when unmounted. 
var AlloyEditorComponent = React.createClass({
	componentDidMount: function() {
	    this._editor = AlloyEditor.editable(React.findDOMNode(this.refs.editableDiv));
	},

	componentWillUnmount: function() {
		this._editor.destroy();
	},

	render: function(){
		return React.createElement('div', {
			contentEditable: true,
			id: 'myDiv',
			ref: 'myDiv'
		  }
		);
	}
});

module.exports = AlloyEditorComponent;
```


@growlsworth

**Comment by growlsworth** [comment]
@ipeychev this looks great. Is the `id` attribute required when creating the div?

**Comment by dantman** [comment]
@ipeychev My feeling on that are the same as mine on the [issue on velocity.js](https://github.com/julianshapiro/velocity/issues/474#issuecomment-102566684).

**Comment by ipeychev** [comment]
> On Aug 18, 2015, at 18:57, Thomas Shafer <notifications@github.com> wrote:
> 
> @ipeychev <https://github.com/ipeychev> this looks great. Is the id attribute required when creating the div?
> 
> 

Not at all! This is actually your own example <https://github.com/liferay/alloy-editor/issues/217#issuecomment-113225634> :)
> —
> Reply to this email directly or view it on GitHub <https://github.com/liferay/alloy-editor/issues/217#issuecomment-132277685>.
> 

---
Iliyan Peychev
Software Engineer, UI Infrastructure Lead
www.liferay.com <http://www.liferay.com/>
Enterprise. Open Source. For Life


Enterprise. Open Source. For Life.
Síguenos en  <http://www.facebook.com/pages/Liferay/45119213107> <http://www.facebook.com/pages/Liferay/45119213107>  <http://www.twitter.com/%21/liferay_es>  <http://www.liferay.com/about-us/news>

Visit Us: www.liferay.com <http://www.liferay.com/> | Like Us: facebook.com/liferay <http://facebook.com/liferay> | Follow Us: twitter.com/liferay <http://twitter.com/liferay>

Aviso de Confidencialidad: Este mensaje de correo electrónico, incluidos los archivos adjuntos, enviados en nombre de Liferay SL es para el uso exclusivo del destinatario (s) previsto y puede contener información confidencial y privilegiada. Se prohíbe cualquier revisión no autorizada, uso, copia, divulgación o distribución. Si usted no es el destinatario, por favor póngase en contacto con el remitente por correo electrónico de respuesta y destruir todas las copias del mensaje original. Gracias.

Confidentiality Notice: This e-mail message, including any attachments, sent on behalf of Liferay SL is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, copying, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message. Thank you.

**Comment by growlsworth** [comment]
Thanks. :+1:

**Comment by ipeychev** [comment]
@growlsworth (and the other guys) Could you please test and tell us if code in this [branch](https://github.com/liferay/alloy-editor/tree/react) is good enough to go to master? If so, v0.5-alpha1 will be released till the end of the week.

**Comment by ipeychev** [comment]
> On Aug 18, 2015, at 18:57, Daniel Friesen <notifications@github.com> wrote:
>
> @ipeychev My feeling on that are the same as mine on the [issue on velocity.js](https://github.com/julianshapiro/velocity/issues/474#issuecomment-102566684).

@dantman I see your point. Judging by AlloyEditor however, I don't clearly see how exactly that could be done automatically, at least in the editor it wasn't a trivial task. You wrote that comment on May, is there some movement around your idea? Did you suggest this to the loader maintainers?

**Comment by dantman** [comment]
> @dantman I see your point. Judging by AlloyEditor however, I don't clearly see how exactly that could be done automatically, at least in the editor it wasn't a trivial task. You wrote that comment on May, is there some movement around your idea? Did you suggest this to the loader maintainers?

I'm not sure what you mean by automatically. I haven't really talked to anyone. Because, as far as code I've worked with has gone, this is already possible and nothing needs changing (I use Browserify).

((Side note, I think it's probably more important to get AlloyEditor to work with `require` in a browserify context to use react any any other libraries that might be available through npm))

But for me, rather than attempting to make a no-op of AlloyEditor load on the server (resulting in node/io.js parsing and running that will never be used) I simply use a conditional require. There are multiple ways to do this.

A) Moving the require into a browser-only method
```js
var React = require('react');

var AlloyEditorComponent = React.createClass({
    // ...
    componentDidMount: function() {
        var AlloyEditor = require('alloyeditor');
        this._editor = AlloyEditor.editable(React.findDOMNode(this.refs.myDiv));
    },
    // ...
});

module.exports = AlloyEditorComponent;
```

B) Using is-browser (and optionally a browserify transform that turns `require('is-browser')` into `true`)
```js
var React = require('react'),
    isBrowser = require('is-browser'),
    AlloyEditor = isBrowser && require('alloyeditor');

var AlloyEditorComponent = React.createClass({
    // ...
    componentDidMount: function() {
        this._editor = AlloyEditor.editable(React.findDOMNode(this.refs.myDiv));
    },
    // ...
});

module.exports = AlloyEditorComponent;
```

One of these days I'll probably write a module + browserify transform pair to make a third option possible (though with a different name). But that will ultimately just be sugar that works like B.
```js
var React = require('react'),
    browseronlyrequire = require('browserrequire'),
    AlloyEditor = browseronlyrequire('alloyeditor');

var AlloyEditorComponent = React.createClass({
    // ...
    componentDidMount: function() {
        this._editor = AlloyEditor.editable(React.findDOMNode(this.refs.myDiv));
    },
    // ...
});

module.exports = AlloyEditorComponent;
```

I don't use Webpack. So I can't tell you if they've changed code, fixed their issue, or what plugins there are that might do conditional requires.

**Comment by ipeychev** [comment]
I see. I like this approach, it makes sense.
