### ISSUE TITLE
Hide the toolbar when loosing focus

### ISSUE THREAD

**Issue by dpobel** [liferay/alloy-editor#218]
The toolbars stay visible if the editor looses the focus. Shouldn't they be hidden in such case ?

**Comment by ipeychev** [comment]
They should. On the [live demo](http://alloyeditor.com/demo/) when you click with the mouse outside of the editor or press Tab to navigate outside they hide correctly.

Could you please attach a .gif with the issue?

**Comment by dpobel** [comment]
Just retested and indeed it seems to work as expected while I'm pretty sure it was not before but I have no idea why... anyway I guess this can be closed.

**Comment by ipeychev** [comment]
Okay, thanks!
