### ISSUE TITLE
Paste images

### ISSUE THREAD

**Issue by dandv** [liferay/alloy-editor#219]
[Pasting images](https://github.com/quilljs/quill/issues/137) is a super handy feature used at GitHub, StackOverflow, Slack etc.

**Comment by ipeychev** [comment]
Definitely, will take a look on that, thanks for reporting!

**Comment by ipeychev** [comment]
To clarify:
You mean - open a web page, click with the right button on some image, then "Copy Image URL" then Cmd+V to paste it to the editor, don't you?

**Comment by dandv** [comment]
I mean pasting an actual image from clipboard, like this one:

![mary had a little lamb had](https://cloud.githubusercontent.com/assets/33569/7881563/280cc61e-05b9-11e5-9502-609daac925f4.jpg)

Right click on it, *Copy image*, paste in Alloy.

**Comment by ipeychev** [comment]
Okay, will take a look during the weekend, thanks!

**Comment by dandv** [comment]
That was quick! Can't wait for [the demo](http://alloyeditor.com/features/image/#comment-2051268197) to be updated.

**Comment by ipeychev** [comment]
Just updated it, enjoy!

**Comment by chiragmakvana** [comment]
Multiple images copy/paste does not works in it.
Just works for single image copy/paste at a time, does any one have encountered this issue?

**Comment by dandv** [comment]
@chiragmakvana: you'll have to be more specific in the reproduction steps. I can paste the two images from [this Google Doc](https://docs.google.com/document/d/11HIrMPLWsxYjcBlMUIqrE4ELiQWpyYk-mj5nbhjOLrg/edit#) just fine if I select all text and paste in [the Alloy demo](http://alloyeditor.com/demo/).

**Comment by chiragmakvana** [comment]
@dandv : I tired to copy multiple images from Microsoft Word 2013 in the Alloy demo. (see the attached screenshot) 
![alloyeditordemo](https://cloud.githubusercontent.com/assets/6497942/7953458/a2362e80-09e2-11e5-8ec6-8ae1b7ebf624.png)

**Comment by ipeychev** [comment]
I just tried with two images selected using Ctrl+A in MS Word Starter 2010. That is how you selected those, isn't it? The URL to the images provided by MS Word is:

file:///C:/Users/iliyan/AppData/Local/Temp/msohtmlclip1/01/clip_image001.jpg

And the editor of course throws the following erros:

(index):1 Not allowed to load local resource: file:///C:/Users/iliyan/AppData/Local/Temp/msohtmlclip1/01/clip_image001.jpg
2alloy-editor-all-min.js:formatted:796 Not allowed to load local resource: file:///C:/Users/iliyan/AppData/Local/Temp/msohtmlclip1/01/clip_image001.jpg

Looking on this, I don't have it clear what we can do in this case.

**Comment by dandv** [comment]
I suppose @chiragmakvana wants Alloy to somehow [obtain the raw image data and save it as base64](https://github.com/Alex-D/Trumbowyg/issues/135).

**Comment by chiragmakvana** [comment]
@dandv : yes, absolutely as in our application i want our users to paste rich content including images and formatting from any office document.
@ipeychev : thanks for investigating this is details, that is exactly what i faced 
I checked on other similar editors, they have similar issue.. i guess its the limitation of html and javascript.

Please let me know if its feasible or not
Thanks

**Comment by ipeychev** [comment]
Right now I'm not aware of any solution, sorry.

**Comment by duracell80** [comment]
Couldn't it detect file:///C:/Users/iliyan/AppData/Local/Temp/msohtmlclip1/01/clip_image001.jpg and flag the image as broken, convert it to a placeholder and offer a drag to drop image into the placeholder with some user guidance text that the image needs to be "re-selected"?

There's a way.
