### ISSUE TITLE
Table column sizes jump around while typing text

### ISSUE THREAD

**Issue by dandv** [liferay/alloy-editor#223]
Just tested in [the demo](http://alloyeditor.com/demo/). Chrome 43. This is an [upstream issue](http://dev.ckeditor.com/ticket/13340) and might be called a feature, but the behavior in the particular context of the Alloy demo breaks the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) because there's no need to expand the first column with every keystroke, given its width.

![tables expand randomly](https://cloud.githubusercontent.com/assets/33569/7900950/32a18e9c-0727-11e5-8b2d-fd0db5c3f5cc.gif)

Google Docs and [Textbox.io](http://textbox.io/demo/) offer a more consistent table editing experience.

![google doc table behaves normally](https://cloud.githubusercontent.com/assets/33569/7901026/734d1310-0729-11e5-859b-cb97c0b241e1.gif)

**Comment by ipeychev** [comment]
From technical point of view, it is not exactly a bug. On creating the table we don't change the default value of [table-layout](https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout) property (which is "auto").
I've heard that this is unexpected behaviour from other people too, so we will discuss this with the UX team and we will see.

**Comment by dandv** [comment]
Agree. See also Reinmar's reply on the [upstream CKEditor issue](http://dev.ckeditor.com/ticket/13340#comment:3).

**Comment by ipeychev** [comment]
Okay.
Thanks again from pointing this out, this effect is indeed hesitating people, but I don't see how to fix it in a good way neither.

**Comment by NavnathKumbhar** [comment]
Hi,

Is there any fix for this issue in latest version of CKEditor?
Or **table-layout:fixed** CSS is the only solution?

Thank you in advance.
