### ISSUE TITLE
Proofread the text in the editor demo 

### ISSUE THREAD

**Issue by dandv** [liferay/alloy-editor#224]
There are some typos at http://alloyeditor.com/demo/, e.g.

> # Want to help us?
> We are not ready yet.

That could be interpreted as "We are not ready to accept contributions". Not good :) Might explain why this repo has only <60 stars, while Summernote has over 2500!

> There is more work to do and if you are developer, 

are "a"

> We need to create more buttons, more toolbars, and why not to create another UI layer, not based on React?

Emdash after "why not"

> keep in mind this requires IE10+, Chrome, Firefox or Safari)

+ Opera

etc.

**Comment by ipeychev** [comment]
Fixed, thanks!
