### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by dandv** [liferay/alloy-editor#226]
It would be helpful to add some words about mobile/touch support.

In Chrome Beta on Android, it looks like there's no special support, at least in the demo. When I tap, sometimes the browser places the cursor correctly; other times, it zooms in the text:

![image](https://cloud.githubusercontent.com/assets/33569/7906401/4866e6e2-07df-11e5-8f98-e26906c17517.png)

**Comment by ipeychev** [comment]
Currently we don't provide mobile support, however we really would love to. The behaviour you see is the native one on the phone.
We have an [issue](https://github.com/liferay/alloy-editor/issues/22) to add mobile support, we didn't have time so far to to work on this.
Contributions are welcome.

**Comment by ipeychev** [comment]
Duplicates #22

**Comment by sunnykgupta** [comment]
Is this open to pickup?
Willing to start contributions to OSS.

**Comment by ipeychev** [comment]
Hello @sunnykgupta,

Yes, this is open and we would be very happy to see you contributing! This was closed, because it duplicates #22, but they are part from the same big topic.

Thanks,
