### ISSUE TITLE
Implement embedding YouTube videos

### ISSUE THREAD

**Issue by ipeychev** [liferay/alloy-editor#233]
We need to embed YouTube videos on pasting an YouTube URL in the editor

**Comment by trecreat** [comment]
:+1:

**Comment by ColtonProvias** [comment]
How about implementing oEmbed?  Covers YouTube, Vimeo, SoundCloud, Flickr, etc.

**Comment by ipeychev** [comment]
Yes, that is what we were thinking to do.

**Comment by rothanachoun** [comment]
+1

**Comment by sanvuthy** [comment]
:+1:

**Comment by jbalsas** [comment]
This can already be done using CKEditor's `embed` plugins. We'll try to do a simpler implementation that does not need all the dependencies, but in the meantime anyone can download and enable those.

**Comment by beeant** [comment]
+1

**Comment by ipeychev** [comment]
See also https://github.com/liferay/alloy-editor/issues/234
