### ISSUE TITLE
AlloyEditor does not support HTML Nodes as stated in the docs

### ISSUE THREAD

**Issue by OtaK** [liferay/alloy-editor#238]
Hi guys.

I came across a problem when trying to integrate AlloyEditor in my project; 

It is actually stated in the docs that `srcNode` config parameter supports both string ID attribute and actual HTML Node objects.

The problem being, when I tried using HTML Nodes, it didn't work, and I looked at the code, and it seems this line is responsible for the bug.

https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/adapter/alloy-editor.js#L26

Have a great day,
Thanks.

**Comment by ipeychev** [comment]
Hey @OtaK,

Thanks for the report. Will fix that very soon!

**Comment by OtaK** [comment]
Thanks for the bugfix! Can you release the fix on Bower via a version number change?

**Comment by ipeychev** [comment]
Well do it very soon :)

**Comment by ipeychev** [comment]
Done
