### ISSUE TITLE
Configurable editor page format

### ISSUE THREAD

**Issue by cristian-chiric** [liferay/alloy-editor#268]
Create an option to transform the editable area into a nice looking document with pages, for instance an A4 document like [here](http://codepen.io/rafaelcastrocouto/pen/LFAes/).

**Comment by jbalsas** [comment]
Hey @cristian-chiric, could you expand a little bit on what you mean?

Would you like a way to format a given content, let's say, for printing purposes? Or would you rather have a _GoogleDoc-like_ experience while editing so new pages are created and content is moved between them?

**Comment by kkotwal94** [comment]
I think being able to format content would be quite awesome and printing them.

**Comment by jbalsas** [comment]
Hey @kkotwal94 

Could you go into more detail as to what would you expect? We're still trying to clearly figure out what this feature means to you guys.

Thanks!

**Comment by kkotwal94** [comment]
Well for example, I wrote a function that strips the div that I can edit with alloy-editor and try to save it as a pdf, however none of the css is maintained properly. So being able to take the content of what is in that pdf and being able to save it as some kind of document would be really cool while keeping formatting. I tried myself but couldn't get to far as I was just messing with css of my own project rather than the editor itself.

**Comment by jbalsas** [comment]
I'm not sure what you mention is the editor's responsibility. We can keep this open to gather more information. In the meantime, you could check some of this projects:
- [html2canvas](http://html2canvas.hertzen.com/documentation.html)
- [jsPDF](http://mrrio.github.io/jsPDF/)

This also affects **printing**, which we could perhaps improve creating a _print stylesheet_, but again, probably not the editor's responsibility.

**Comment by kkotwal94** [comment]
Yea you are right, I thought so as well which is why I gave it my own attempt, and thanks for the links for the conversion. Just what I needed.

**Comment by cristian-chiric** [comment]
Hey @jbalsas, what I meant is to be able to write the content directly into A4 pages for instance. Set the page format and start writing content into it. When I reach the end of the page, a new page should be created automatically and cursor moved to the start of the next page. I hope it's more clear now.

**Comment by jbalsas** [comment]
Hey @cristian-chiric, thanks for the clarification.

Unfortunately, I don't think this would be possible. CKEditor does not support this and as far as I can tell, they will never do. You can read about the reasons for it in [this forum discussion](http://ckeditor.com/comment/123434#comment-123434) and in this [CKEditor issue](http://dev.ckeditor.com/ticket/9932#comment:1)

**Comment by wincent** [comment]
I believe the discussion on this one has reached its conclusion, so closing this one.
