### ISSUE TITLE
Using alloy editor in modals

### ISSUE THREAD

**Issue by kkotwal94** [liferay/alloy-editor#276]
I'm using alloy editor in a text area, within a modal, I was wondering for advice on how to go about this. Basically when a button is clicked a input modal comes up with a POST form, the ckeditor works fine, but the tools such as "+" or when i highlight the text are appearing under the modal. Any suggestions? Should I do something about the tint?

**Comment by ipeychev** [comment]
If you don't specify where, the UI will render in the body element. In case of modal, the modal will appear on top of it. In this case, you have to render the UI it inside your modal, maybe next to the element you want to edit. You will have to style it probably - at least to set position:relative, but it depends on your markup.

You can specify the element where the UI should be rendered by changing [uiNode](http://alloyeditor.com/api/classes/Core.html#property_uiNode) property, like this:

```
AlloyEditor.editable('editable', {
    uiNode: 'some-id-or-domelement-here'
});
```

Hope that helps!

**Comment by kkotwal94** [comment]
Going to give it a shot thanks!

**Comment by kkotwal94** [comment]
Never mind, I figured it out, you were correct, just edited ocean.css file to get what I wanted, it was set to absolute under toolbar I just set margin's to position it to a static location.

**Comment by ipeychev** [comment]
Okay, great!
