### ISSUE TITLE
Support for HTML/Edit Source

### ISSUE THREAD

**Issue by hajrice** [liferay/alloy-editor#279]
Would love to hear your thoughts if that's even possible with Alloy, or is coming soon?

**Comment by ipeychev** [comment]
Hello,

We discussed this functionality, but we preferred to leave for the implementors just because we didn't discover a good UX.

Do you have a suggestion how editing of HTML in an inline WYSIWYG editor would look like?

Thanks,

**Comment by hajrice** [comment]
Sure!

I think a simple button that either:
a) Reveals a modal to *ADD* HTML/CSS/whatever code
or
b) Reveals a modal that allows you to edit everything that is presented

I think support for a) is much better, UX wise, than the later option.

Regarding this, I'm happy to build this – but I'm curious where I could
read up on this ?

Your API docs are amazing, but unfortunately they're crazy huge, and really
hard to use

On Mon, Jul 6, 2015 at 5:42 PM, Iliyan Peychev <notifications@github.com>
wrote:

> Hello,
>
> We discussed this functionality, but we preferred to leave for the
> implementors just because we didn't discover a good UX.
>
> Do you have a suggestion how editing of HTML in an inline WYSIWYG editor
> would look like?
>
> Thanks,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/liferay/alloy-editor/issues/279#issuecomment-118900927>
> .
>



-- 
Sincerely,
Emil Hajric,
CEO, Helpjuice.com

*Office*: (888) 230-3420
*Cell*: 904-419-3645

Helpjuice, Inc.,
5 W Forsyth,
32202 Jacksonville, FL

**Comment by ipeychev** [comment]
You can create a simple button, which would be a React component. It is quite easy, you may read [here](http://alloyeditor.com/guides/create_buttons) how-to do it.
Then, you will have to attach it probably to the "Add" toolbar (those which appears) on left, with the plus icon.

Let us know if that helps, please!

**Comment by jbalsas** [comment]
Hey @hajrice 

If we were to support CKEditor out of the box plugins as discussed in #280, would that solve this issue for you?

**Comment by hajrice** [comment]
Yep - I already built something similar for the code preview! :)

On Tue, Jul 7, 2015 at 9:35 AM, Chema Balsas <notifications@github.com>
wrote:

> Hey @hajrice <https://github.com/hajrice>
>
> If we were to support CKEditor out of the box plugins as discussed in #280
> <https://github.com/liferay/alloy-editor/issues/280>, would that solve
> this issue for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/liferay/alloy-editor/issues/279#issuecomment-119104724>
> .
>



-- 
Sincerely,
Emil Hajric,
CEO, Helpjuice.com

*Office*: (888) 230-3420
*Cell*: 904-419-3645

Helpjuice, Inc.,
5 W Forsyth,
32202 Jacksonville, FL

**Comment by jbalsas** [comment]
Wow, that's great!

Would you like to contribute your solution to the editor? If it's specific for your case, we can work with you to make it generic enough for everyone to use it.

**Comment by hajrice** [comment]
For sure.

What I did, is, create a solution that initializes another text editor,
then overlaps this one, and adds a HTML source button.

On Tue, Jul 7, 2015 at 9:41 AM, Chema Balsas <notifications@github.com>
wrote:

> Wow, that's great!
>
> Would you like to contribute your solution to the editor? If it's specific
> for your case, we can work with you to make it generic enough for everyone
> to use it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/liferay/alloy-editor/issues/279#issuecomment-119105735>
> .
>



-- 
Sincerely,
Emil Hajric,
CEO, Helpjuice.com

*Office*: (888) 230-3420
*Cell*: 904-419-3645

Helpjuice, Inc.,
5 W Forsyth,
32202 Jacksonville, FL

**Comment by aiphee** [comment]
Is there any possibility how to do that now? 
I successuflly added font color etc. from CKeditor, but i cant get this to work: 
http://ckeditor.com/addon/sourcedialog

**Comment by ipeychev** [comment]
If you specify the error, it would be very helpful :)

In any case, the UX of editing code in this way is bad and I would suggest you to not use this plugin. Instead, create a separate pane, which consists from two parts - code editor on left with syntax highlighter and live preview on right. Once the user is happy, he clicks on the OK button and you replace the code inside AlloyEditor with the new one.

Hope that helps.
