### ISSUE TITLE
Editing content that is dynamically rendered

### ISSUE THREAD

**Issue by kkotwal94** [liferay/alloy-editor#284]
I'm using reactjs for my front end, and the div I edit is in my render state. However I'm sure render is called more than once, every time a prop is changed actually, and once that happens the content is still editable, but the props/values past down are not displayed. Using regular markup in the render state allows it to be editable and displays the mark up correctly however.

So my question is how do I use props, pass it down to my render state and still have it editable with alloy editor?

Here is a example
```javascript
render: function() {

var j = "  " + this.props.forms.body + "  ";
return(


    <div>
	<div id = "content" >
   
	<h3>{this.props.forms.author}</h3>
    <pre>{this.props.forms.title}</pre>
	  
	<div dangerouslySetInnerHTML={{__html : j	}} />
	<div>
	{
		this.props.subforms.map(function(subform){
		var x = " " + subform.body + " ";
		//console.log(x);
	return (

	<div>
	<pre> {subform.title}</pre>
	<div dangerouslySetInnerHTML={{__html : x	}} />
	</div>
	
  )})}
	</div>
   </div>
   </div>
  

 )
 }
 
 });

```

which wouldnt work because of the props i am mapping vs. just filling the div content with normal markup.

**Comment by ipeychev** [comment]
Hey @kkotwal94,

I'm sorry, but reading the post it seems this question is not specific to AlloyEditor. It is more related to your application.
If you have a specific question about the editor however, we will help.

Thanks,

**Comment by kkotwal94** [comment]
Yep, sorry about that was tired and not thinking straight, I figured it out. You can close/trash this.
