### ISSUE TITLE
Alloy Editor on change event

### ISSUE THREAD

**Issue by trecreat** [liferay/alloy-editor#286]
Hi,
How to detect editor changes and get editor's content ?

**Comment by ipeychev** [comment]
You can use the following:
```
var editor = AlloyEditor.editable('editable');
var nativeEditor = editor.get('nativeEditor');
editor.get('nativeEditor').on('change', function(event) {
    var currentContent = nativeEditor.getData();
});
```
where "nativeEditor" is the engine's instance (CKEditor). You can use all of their [API](http://docs.ckeditor.com/), like in this example.

Thanks,

**Comment by trecreat** [comment]
Thank you @ipeychev !
