### ISSUE TITLE
Keep the contenteditable attribute value

### ISSUE THREAD

**Issue by dpobel** [liferay/alloy-editor#290]
In some cases, you don't want the node passed to `AlloyEditor.editable` to be completely editable. Basically instead of forcing `contenteditable` to true, AlloyEditor should only set it if it's not already set. (PR to come shortly)

**Comment by ipeychev** [comment]
Hey @dpobel,

There will be cases when this may cause bad developer experience. What about this scenario:
1. The page loads, the contenteditable is set to false.
2. The user clicks on some button, for example "Edit".
3. In this case the developer creates an instance of AlloyEditor, which currently will automatically set contenteditable attribute to true.

That is the main reason why AlloyEditor explicitly sets it to true when an instance is being created.

With [this PR](https://github.com/ezsystems/alloy-editor/commit/d50c9e52a27a40e3f6c3e287456e583efa70fb66), now the developer should to do both - to set contenteditable to true and to create the instance.

What is the point of creating an instance of AlloyEditor when the content is not editable? The editor won't be able to do anything, so why is that useful? This will be just waste of memory and resources. Why not creating the instance only when it is necessarily?

Thanks,

**Comment by dpobel** [comment]
I see your point but the patch actually has an effect only if contenteditable is explicitly set to false, if the contenteditable attribute is omitted, then AlloyEditor will keep on behaving like before.

My use case for that is the second in https://github.com/liferay/alloy-editor/issues/293#issuecomment-123649947. Basically, in my page I have something like:

```
<div id="alloy" contenteditable="false">
  <section contenteditable="true">
    <p>The real editable thing...</p>
  </section>
  <section class="a-kind-of-static-toolbar-with-links-button-whatever">
     <button>Let's do something in this AlloyEditor</button>
  </section>
</div>

<script>
AlloyEditor.ediablte('alloy');
</script>
```

that way when the user starts to use the button in the *static toolbar*, an `editorInteraction` event is fired and the Alloy is correctly initialized.

**Comment by ipeychev** [comment]
I see. I thought for the following solution:
- We introduce a new boolean config attribute, something like "enableContentEditable". Its default value will be true.
- In your case, when you create an instance of AlloyEditor, you will be able to configure it like this:

```
var editor = new AlloyEditor('editable', {
    enableContentEditable: false
}); 
```

In this case, the editor will not set "contenteditable" attribute of the DOM node to true.

In short, by default the editor will behave like it does currently, but for edge cases like yours, you will be able to achieve what you want.

How does this sound for you?

**Comment by dpobel** [comment]
that seems perfectly fine, I'll update my PR with that tomorrow.

**Comment by ipeychev** [comment]
Great, thanks!
