### ISSUE TITLE
Missing API to add custom CKEditor plugins through AlloyEditor

### ISSUE THREAD

**Issue by dpobel** [liferay/alloy-editor#296]
In my project I need to add one (for now :)) custom plugin to CKEditor. If I want to inject it properly through AlloyEditor, I have to repeat the default plugin list and add mine with something like:

```js
AlloyEditor.editable('editable', {
    extraPlugins: 'uicore,selectionregion,dragresize,addimages,placeholder,tabletools,tableresize,autolink,myplugin'
});
```

which is of course not very nice. Maybe AlloyEditor.Core could have another attribute (`customExtraPlugins` for instance) so I could write something like:

```js
AlloyEditor.editable('editable', {
    customExtraPlugins: 'myplugin'
});
```

to get the same result. (I assume that having to remove a plugin from the current `extraPlugins` default value is not something very usual).

**Comment by ipeychev** [comment]
We were discussing this for a long time and we haven't found a good enough API. The easiest way still is:
```
AlloyEditor.editable('editable', {
    extraPlugins: AlloyEditor.Core.ATTRS.extraPlugins.value + ',myplugin'
});
```

**Comment by dpobel** [comment]
Indeed not very handy but that does the job, thanks for the tip :)
