### ISSUE TITLE
AlloyEditor does not work in CommonJS and AMD environments

### ISSUE THREAD

**Issue by jbalsas** [liferay/alloy-editor#304]
AlloyEditor expects React to be global. Unfortunately, React accounts for `CommonJS` and `amd` environments, so if someone tries to use AlloyEditor in such environment, it will not be able to locate it.

We should at least force our bundled React versions to always load it into the global object.

**Comment by kkotwal94** [comment]
Yea, actually I was just going to open a new issue about it. I've tried it with webpack doing so by adding a alias straight to the path where it exists :  

```
 resolve: {
      extensions: ['', '.react.js', '.js', '.jsx', '.scss', '.css'],
      modulesDirectories: [
        "app", "node_modules"
      ],
      alias: {
      alloyeditor : '../../node_modules/alloyeditor/dist/alloy-editor/alloy-editor-no-react.js'
      }
    }
```

trying so in es6

```
import * from alloyeditor;
import * as alloy from alloyeditor;
require("alloyeditor");
```

always returned

```
ERROR in ./components/NewReport.js
Module not found: Error: Cannot resolve module 'alloy-editor' in /home/karan/Documents/IsoReportProcessor/app/components
 @ ./components/NewReport.js 33:19-42
```

so yea I second this

**Comment by jbalsas** [comment]
Hey @kkotwal94,

I'm not sure the fix we committed for this will help you as well. Would you care to try it? 

As far as I can see, you're already requesting `alloy-editor-no-react.js`. Our case should allow you to request `alloy-editor-all.js` which should still make `React` global.

I'm quite certain your issue should still reproduce, so feel free to open a different issue for that stating clearly what are the minimum set of steps to reproduce. Keep in mind that we don't have those environments set up and in our mind, so it's hard for us to keep track and work on those. As always, any contributions on those areas are greatly appreciated! :)

**Comment by kkotwal94** [comment]
Yes i'll do so in a bit!

**Comment by arpitHub** [comment]
@kkotwal94 - did you manage to fix it?
