### ISSUE TITLE
Alloyeditor and global namespace

### ISSUE THREAD

**Issue by kkotwal94** [liferay/alloy-editor#315]
So I gave it a shot with 4.0 and still couldn't get it to be used globally in my project. For a bundler I use Webpack. 

Here is example of my directory (alloy-editor is in nodemodules)
https://github.com/kkotwal94/IsoReportProcessor

I simply wrote require("alloyeditor") since that is the alias that I chose for it. Here is the code for the webpack config file, look in the resolve.alias portion of it. I set the path and gave it the name alloyeditor. 

We tried this based off the documentation here : http://webpack.github.io/docs/configuration.html#resolve

Also when I installed it via npm it was still version 3.7 (same with bower i think) so I git cloned the repository and just used what was in this repository.
```
var path = require("path");
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var webpack = require("webpack");

var assetsPath = path.join(__dirname, "public", "assets");
var publicPath = "assets/";

var commonLoaders = [
  {
    /*
     * TC39 categorises proposals for babel in 4 stages
     * Read more http://babeljs.io/docs/usage/experimental/
     */
    test: /\.jsx$/, loader: "babel-loader?stage=0"
  },
  {
    test: /\.js$/,
    loader: "babel-loader?stage=0",
    include: path.join(__dirname, "app")
  },
  { test: /\.png$/, loader: "url-loader" },
  { test: /\.jpg$/, loader: "file-loader" },
  { test: /\.html$/, loader: "html-loader" }
];

module.exports = [
  {
    // The configuration for the client
    name: "browser",
    /* The entry point of the bundle
     * Entry points for multi page app could be more complex
     * A good example of entry points would be:
     * entry: {
     *   pageA: "./pageA",
     *   pageB: "./pageB",
     *   pageC: "./pageC",
     *   adminPageA: "./adminPageA",
     *   adminPageB: "./adminPageB",
     *   adminPageC: "./adminPageC"
     * }
     *
     * We can then proceed to optimize what are the common chunks
     * plugins: [
     *  new CommonsChunkPlugin("admin-commons.js", ["adminPageA", "adminPageB"]),
     *  new CommonsChunkPlugin("common.js", ["pageA", "pageB", "admin-commons.js"], 2),
     *  new CommonsChunkPlugin("c-commons.js", ["pageC", "adminPageC"]);
     * ]
     */
    context: path.join(__dirname, "app"),
    entry: {
      app: "./app"
    },
    output: {
      // The output directory as absolute path
      path: assetsPath,
      // The filename of the entry chunk as relative path inside the output.path directory
      filename: "[name].js",
      // The output path from the view of the Javascript
      publicPath: publicPath

    },
    module: {
      preLoaders: [{
        test: /\.js$|.jsx$/,
        exclude: /node_modules/,
        loaders: ["eslint"]
      }],
      loaders: commonLoaders.concat([
        { test: /\.css$/, loader: "style!css" },
        { test: /\.scss$/,
          loader: ExtractTextPlugin.extract("css?sourceMap!sass?sourceMap&outputStyle=expanded" +
            "&includePaths[]=" + (path.resolve(__dirname, "./bower_components")) +
            "&includePaths[]=" + (path.resolve(__dirname, "./node_modules")) +
            '&includePaths[]=' + (path.resolve(__dirname, './node_modules/alloy-editor/dist/alloy-editor/assets')))
        }
      ])
    },
    resolve: {
      extensions: ['', '.react.js', '.js', '.jsx', '.scss', '.css'],
      modulesDirectories: [
        "app", "node_modules"
      ],
      alias: {
      alloyeditor : './node_modules/alloy-editor/dist/alloy-editor/alloy-editor-all.js'
      }
    },
    plugins: [
        // extract inline css from modules into separate files
        new ExtractTextPlugin("styles/main.css")
    ]
  }, {
    // The configuration for the server-side rendering
    name: "server-side rendering",
    context: path.join(__dirname, "app"),
    entry: {
      app: "./app",
      header: "./elements/Header.react"
    },
    target: "node",
    output: {
      // The output directory as absolute path
      path: assetsPath,
      // The filename of the entry chunk as relative path inside the output.path directory
      filename: "[name].server.js",
      // The output path from the view of the Javascript
      publicPath: publicPath,
      libraryTarget: "commonjs2"
    },
    externals: /^[a-z\-0-9]+$/,
    module: {
      loaders: commonLoaders
    },
    resolve: {
      extensions: ['', '.react.js', '.js', '.jsx', '.scss'],
      modulesDirectories: [
        "app", "node_modules"
      ]
    },
    plugins: [
      new webpack.NormalModuleReplacementPlugin(/\.(css|scss)$/, "node-noop")
    ]
  }
];

```

**Comment by jbalsas** [comment]
Hey @kkotwal94, 

It seems that you have missing dependencies in your `package.json` file like `mongoose-deep-populate` and `bluebird`.

I managed to get everything running, but I'm not sure how to move forward since the AlloyEditor integration code seems to be missing. Could you push a branch to your repo with the exact code you currently have? I assume you'd want the editor in `app/components/EditReport.js`. Where did you put the `require("alloyeditor")`?

**Comment by kkotwal94** [comment]
yea the way I was going was like this:

```
require("alloyeditor");
```
in the editReport.js file and in my base.html I just add this in between script tags
```
<script>
$(document).ready(function () {
    AlloyEditor.editable('ckedit', {
    uiNode: 'modal-4',
                toolbars: {

  add: {
        buttons: ['image', 'camera', 'hline', 'table'],
        tabIndex: 2
    },
        styles: {
            selections: [
                {
                    name: 'text',
                    buttons: [{
                        name: 'styles',
                        cfg: {
                            styles: [
                                {
                                    name: 'Head 1',
                                    style: { element: 'h1' }
                                },
                                {
                                    name: 'Head 2',
                                    style: { element: 'h2' }
                                },
                                {
                                    name: 'Big',
                                    style: { element: 'big' }
                                },
                                {
                                    name: 'Small',
                                    style: { element: 'small' }
                                },
        {
            name: 'Formatted',
            style: {element: 'pre'}
        },
                                {
                                    name: 'Code',
                                    style: { element: 'code' }
                                },
                               { name: 'Inline Quotation', style:{element: 'q'} }
                            ]
                        }
                    },'quote','bold', 'italic', 'underline', 'link', 'twitter','subscript','superscript', 'ul', 'ol'],
                    test: AlloyEditor.SelectionTest.text
                }
            ]
        }
    }




});
</script>
```
I also updated my repository

**Comment by jbalsas** [comment]
Hey @kkotwal94 

The require error you're seeing is caused because AlloyEditor is missing a `main` attribute in its `package.json` file. You can edit your local version and set something like:

```json
"main": "dist/alloy-editor/alloy-editor-core.js"
```

This should be enough to fix this issue. However, as mentioned [here](https://github.com/liferay/alloy-editor/issues/240) you would probably be better off not trying to load this on the server-side at all :)

For what it's worth, I've been able to get AlloyEditor up and running just by including the script and css in your `base.html` and then adding the initialization logic, inside the `ReportView.js > componentDidMount` method.

Is there a reason why that wouldn't work for you?

**Comment by kkotwal94** [comment]
I haven't even tried the second method you mentioned, but is it something like this?
```
<script src="./node_modules/alloy-editor/dist/alloy-editor/alloy-editor-core.js"></script>
<link rel="stylesheet" type="text/css" href="./node_modules/alloy-editor/dist/alloy-editor/assets/alloy-editor-ocean-min">
```
in base.html, and then this in ReportView.js > componentDidMount 
```
AlloyEditor.editable('ckedit');
```
?

**Comment by jbalsas** [comment]
Yeah, I went with the first option in your comment above. I just pointed to externally hosted files for the editor, so it must just be an issue with how you're packaging the files in webpack.

For the require version, you should require it as before `require("alloyeditor")` and node will resolve it in its own to the file specified in the `main` attribute.

We discussed this in the office today. We'll try to find time to get it to work in node environments, but I'm not sure when would that be.

**Comment by kkotwal94** [comment]
Sounds great, in a example I did (without webpack,flux,iso, etc) I used just react and node. I was able to use alloy editor to most of its capabillities, in this example (widget may be a bit off because I didnt adjust css):

http://ec2-54-187-2-191.us-west-2.compute.amazonaws.com:3000/ 

If you hit post, and click in the white space under it, most of the functionality works (double click submit to send if logged in). I'm just really looking to be able to send data using alloy-editor. I used the static location of the dependencies for this. So if I manage to require alloyeditor and it resolves it should be able to work and I think that could be a suitable solution for me. Thank you for the help.

**Comment by kkotwal94** [comment]
Is there any chance you can push what you did or show me how you wrote the code that you wrote?

**Comment by ipeychev** [comment]
Hey @kkotwal94, FYI @jbalsas is on vacation, he will return on Monday.

**Comment by kkotwal94** [comment]
Ok thank you
