### ISSUE TITLE
Implement changing the position of image

### ISSUE THREAD

**Issue by u2** [liferay/alloy-editor#321]
What about dragging image and changing the position of it?

**Comment by ipeychev** [comment]
That is an interesting question. Please take a look on the following screencast. In Chrome, Firefox, etc. you already can drag an image and move it wherever you want. Isn't that what you are mentioning?

![img](https://cloud.githubusercontent.com/assets/78014/9315890/313316d6-4532-11e5-96a2-d32c4f9da10d.gif)

**Comment by u2** [comment]
No.I mean I can't move the image if there is only an image in my editor, like absolute position.Look at the following photo, how I can move the image 100px right?
![5ca3b62b-582b-4044-a14e-2bc6aa50d9fd](https://cloud.githubusercontent.com/assets/161756/9320391/2054f7e4-458c-11e5-8b25-5ae56627f631.png)

**Comment by ipeychev** [comment]
I'm not sure how useful such feature will be. Dragging an image on an arbitrary position means that it could easily cover the text, for example when you create the content on a device with one width, but it is displayed on a device with different width. Even in Desktop browser that may happen - when you resize the window.

**Comment by u2** [comment]
Yes, it's very difficult for different devise.But for my situation, we only consider for Desktop and A4 printing.Maybe I can use absolute position to Implement it.

**Comment by ipeychev** [comment]
Okay! Please be free to show us what you did. If that is a plugin, we can include it in the distribution.

**Comment by u2** [comment]
Here is the demo. [ck-arbitrary-dragresize.](http://u2.github.io/ck-arbitrary-dragresize.html).

**Comment by ipeychev** [comment]
Yeah, I would hide temporally the toolbar and the resize handles while dragging.

**Comment by u2** [comment]
Thank your suggestion.
