### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by u2** [liferay/alloy-editor#323]
I am a freshman of Javascript.I want to contribute to alloy-editor, but I don't know how to do.

**Comment by ipeychev** [comment]
Hey @u2,

Welcome on board! You can read [here](http://alloyeditor.com/contributing/) about the different ways to help us. You may write documentation, contribute code, answer question or give us feedback.

Thanks,

**Comment by u2** [comment]
Thank you.
