### ISSUE TITLE
Selection with CKEditor 'widget' plugin 

### ISSUE THREAD

**Issue by trecreat** [liferay/alloy-editor#326]
Hi,
I use `alloy-editor-no-ckeditor.js` and `ckeditor` with `widget` plugin, the plugin & editor works well. But, is there a way to add new selection for the widget ?

I know you do not support OOTB, but please help me with this one.

I checked with `selectionChange`, the return value is `true`

```javascript
editor.on('selectionChange', function(e){
    // console.log(editor.widgets.focused);
    var selection = editor.getSelection();
    var element = selection.getStartElement();
    var selected = selection.getSelectedElement();
    console.log(selection);
    if(element) {
        console.log(element);
    }
    if(selected) {
        console.log(selected);
    }
    console.log(element && element.isReadOnly() && element.getName() == 'div' && element.hasClass('cke_widget_block'));
})
```

But when adding new selection, the toolbar does not appear

```javascript
{
    name: 'block',
    buttons: ['pullLeft','pullRight'],
    test: function(payload) {
        var editor = payload.editor.get('nativeEditor');
        var selection = editor.getSelection();
        var element = selection.getStartElement();
        var selected = selection.getSelectedElement();
        return element && element.isReadOnly() && element.getName() == 'div' && element.hasClass('cke_widget_block');
    }
},
```

**Comment by ipeychev** [comment]
This is out of the scope of the support which we provide, but anyway:
If the selection returns true, look what are the calculated values for the Toolbar position. Probably you should debug starting from [here](https://github.com/liferay/alloy-editor/blob/b5cf353a5c70cbaf86018bcac140e4b6f8fa2b54/src/ui/react/src/components/toolbars/toolbar-styles.jsx#L235).

**Comment by trecreat** [comment]
Many thanks @ipeychev !
