### ISSUE TITLE
Need help. Is it possible to use ckeditor toolbard

### ISSUE THREAD

**Issue by lyapharov** [liferay/alloy-editor#328]
Hello. 
Is it possible to use static toolbar in old ckeditor style instead of new floating toolbar?

**Comment by ipeychev** [comment]
Hey @lyapharov,

Probably yes - AlloyEditor is CKEditor's engine + its own UI (and plugins). So if you disable our UI and include CKEditor's one, that should work. However, this does not make much sense - just use CKEditor as it is if you want their UI.

Btw, why do you want to render the original's CKEditor toolbar in AlloyEditor?

Thanks,

**Comment by jbalsas** [comment]
Hey @lyapharov,

As @ipeychev mentions, not so sure why would you want a static toolbar instead. If you still want to use all of AlloyEditor features but just keep the toolbar in a fixed place, you could maybe initialize your editor with something like this:

```javascript
AlloyEditor.editable('editable', {
    toolbars: {
        styles: {
            selections: [
                {
                    name: 'static',

                    // Set all the buttons you want in your toolbar here
                    buttons: ['bold', 'italic', 'image'],

                    // Force selection toolbar to always show this toolbar
                    test: function(payload) { return true; },      

                    // Don't show arrows for this toolbar                         
                    getArrowBoxClasses: function() { return ''; },

                    // Always position this toolbar on the upper-left corner of your editable node
                    setPosition: function(payload) { 
                        var editableElement = payload.editor.get('nativeEditor').element.$;
                        var toolbarPosition = [editableElement.offsetLeft, editableElement.offsetTop];

                        this.moveToPoint(toolbarPosition, toolbarPosition); 

                        return true; 
                    }
                }
            ]
        }
    }
});
```

**Comment by lyapharov** [comment]
@ipeychev  @jbalsas Thanks everyone. We decided to use alloy because it work better with rich text as i can see on http://socialcompare.com/en/comparison/javascript-online-rich-text-editors and based on react. Maybe in future we'll use your floating toolbar  - because it seems much better than static one - but now we have to implement static according to our degisn.

**Comment by ipeychev** [comment]
@lyapharov Btw, I wouldn't trust much this Socialcompare.com [comparison](http://socialcompare.com/en/comparison/javascript-online-rich-text-editors). Looking on the information about AlloyEditor there, it was outdated, sometimes incorrect and not very accurate. I just updated it, but since they rely on a human to update it regularly, it may become outdated again soon.

**Comment by lyapharov** [comment]
Another one question: @jbalsas your solution works, but we need to keep editor on page even if it lost a focus due to our animation needs. Don't you know if it's possible to configure editor's behavior without some manual changes in UI class?

**Comment by jbalsas** [comment]
Hey @lyapharov 

I'm afraid that we don't support what you ask right now.

An easy hack, however, would be to override the `_setUIHidden` method of the main UI element like this:

```javascript
var editor = AlloyEditor.editable('editable');

editor._mainUI._setUIHidden = function() {};
```

But again, this is like finding loopholes in how AlloyEditor is meant to work to force it to be something that is not :wink:

**Comment by jayeszee** [comment]
Hey I have a question regarding this. How would you make a toolbar appear on initial load?(without having to select the editor.)

**Comment by ipeychev** [comment]
If you want to have the Styles toolbar always visible, please see [here](https://github.com/liferay/alloy-editor/issues/328#issuecomment-134308668).

**Comment by jayeszee** [comment]
Hey thanks for replying. The issue isn't getting the toolbar to always show but its getting the toolbar to show on initial load. I've already gotten it to stay visible always but it won't be visible after i refresh the page until I click into the editor component.

**Comment by Rohan-Doshi** [comment]
Hey @jayeszee , were you able to get the toolbar to always show without clicking on the editor ?
