### ISSUE TITLE
Font Color and Size feature

### ISSUE THREAD

**Issue by u2** [liferay/alloy-editor#335]

**Comment by jbalsas** [comment]
Hey @u2 

We don't currently have our own version of these features.

However, you can use CKEditor's [Font](http://ckeditor.com/addon/font) and [ColorButton](http://ckeditor.com/addon/colorbutton) plugins as explained in [this guide](http://alloyeditor.com/guides/how_to_use_ckeditor_plugins/)

**Comment by u2** [comment]
Thank you.

**Comment by duracell80** [comment]
Any updates on implementing these as defaults for Liferay DXP?
