### ISSUE TITLE
Incorrect domain for requests made when trying to initialize the editor

### ISSUE THREAD

**Issue by aaronjbaptiste** [liferay/alloy-editor#339]
Hi,

I'm brand spanking new to the alloy-editor and i'm looking to replace my tiny mce implementation with it, however i'm running into problems following the getting started guide.

I've downloaded the zip and included the required css and js files: alloy-editor-ocean-min.css and alloy-editor-all-min.js

And then i've initialised the editor with:

```
AlloyEditor.editable('idOfElement');
```

and I get these errors (Chrome console):

```
GET http://www.mydomain.com/lang/alloy-editor/en.js?t=F62B (http 500)
GET http://www.mydomain.com/config.js?t=F62B (http 500)
GET http://www.mydomain.com/skins/moono/editor.css?t=F62B (http 500)
GET http://www.mydomain.com/lang/en.js?t=F62B (http 500)
Uncaught TypeError: Cannot set property 'dir' of undefined
```

If it helps I have a cross domain setup. The alloy-editor root folder is actually hosted from http://static.mydomain.com/libraries/alloy-editor/ (note the static sub domain). So the requested urls won't work. Is there a way to set the base or root url?

I've also tried including the en.js and config.js files manually, but they are still requested a second time from the wrong locations.

Any ideas?

Thanks

**Comment by jbalsas** [comment]
Hey @aaronjbaptiste,

Could you share the `<script src="..." >` part of your code to see how AlloyEditor is being added to the page?

We have two mechanisms that should help with this:

- `window.ALLOYEDITOR_BASEPATH` can be set to specify where AlloyEditor is hosted
- [AlloyEditor.regexBasePath](http://alloyeditor.com/api/classes/AlloyEditor.html#property_regexBasePath) tries to discover this url automatically by analyzing your `script` tags.

**Comment by aaronjbaptiste** [comment]
ah yes, I see it now. Here is how it is being added:

```
<script type="text/javascript" src="http://local-static.samlearning.com/library/_vendor/alloy-editor/alloy-editor-all-min.js/123.alloy-editor-all-min.js"></script>
```
Removing our versioning system and changing it to:

```
<script type="text/javascript" src="http://local-static.samlearning.com/library/_vendor/alloy-editor/alloy-editor-all-min.js"></script>
```

Works fine. I can work around that.
