### ISSUE TITLE
React Component disappears when calling editiable on child

### ISSUE THREAD

**Issue by senguendk** [liferay/alloy-editor#340]
I am rending a React component that has a div, which I would like to make editable via Alloy Editor. When I call editable on that div, the component disappears. Is there something I am doing wrong?

I forgot to mention, that the content that the div receives is passed down from a state value of a parent component as a prop.

**Comment by ipeychev** [comment]
Hey @senguendk,
With "disappear" do you mean it becomes hidden, or it is entirely removed from the DOM? In any case, making a div editable shouldn't cause either of those.
Could you please share some reproducible code (as short as possible)? Otherwise it would be hard to guess the reason.

Thanks,

**Comment by senguendk** [comment]
So, I was able to fix this problem and it had nothing to do with alloy editor. I was loading the content twice in my app and that caused the content to disappear. Sorry about that and thank you for your time!

**Comment by ipeychev** [comment]
It is OK, glad you fixed it!
