### ISSUE TITLE
Target blank

### ISSUE THREAD

**Issue by akaiworld** [liferay/alloy-editor#344]
Did not see the option for links to make them open in a new tab(optionally).

**Comment by jbalsas** [comment]
Hey @akaiworld, this is in our roadmap but we just haven't had the time to work on it. See #119. 

As always, we're more than happy to review and accept contributions :wink:

**Comment by trecreat** [comment]
:+1:

**Comment by jbalsas** [comment]
This is the proposal from our UX team

![9r6_ysnfr32cd3ci0cdcnnarrntqm2wiq9ldr5nkziq](https://cloud.githubusercontent.com/assets/905006/10993791/f3c9e0c0-8471-11e5-9c40-0d886f031b4a.png)

Will get to it asap, hopefully for 0.7.0

**Comment by jbalsas** [comment]
Implemented in #392

**Comment by codeams** [comment]
Is this feature still available? Couldn't find anything about this in the docs

**Comment by julien** [comment]
Hi @codeams,

We're currently working on the new website and in the process of updating the documentation, sorry if it's not up to date.

This feature is still available, if you clone this repo and run the demo you should be able to see it when adding a link as you can see in this screenshot

<img width="653" alt="link-edit" src="https://user-images.githubusercontent.com/5572/53552369-77c4b480-3b3b-11e9-9455-fe1e31a98edf.png">
