### ISSUE TITLE
linkEdit

### ISSUE THREAD

**Issue by akaiworld** [liferay/alloy-editor#348]
When i use linkEdit option it happens to be expanded right in the main toolbar when i hover the text. But in all the examples on the site it is closed and expands only by a click. How to make it work like this? Here is the code i use: 

				AlloyEditor.editable(this, {
					extraPlugins: AlloyEditor.Core.ATTRS.extraPlugins.value+
						',ae_buttonbridge,ae_panelmenubuttonbridge,ae_richcombobridge,ae_uibridge,'
					toolbars: {
						styles: {
							selections:  [{
								name: 'text',
								buttons: [
										'bold', 'italic', 'strike', 'underline', 
										'linkEdit', 
										],
								test: AlloyEditor.SelectionTest.text
							}]
						}
					}
				});

**Comment by jbalsas** [comment]
Hey @akaiworld, that is per design. 

The button you're looking for is actually **`link`**. 

When expanded, it will show the `linkEdit` one on his own :wink:

**Comment by akaiworld** [comment]
Thank you! That's nice!
