### ISSUE TITLE
Project Site: Expand "Get stated" with additional code example.

### ISSUE THREAD

**Issue by blzaugg** [liferay/alloy-editor#35]
http://alloyeditor.com/

It's unclear that `contenteditable="true"` is required for the editor to function.

```html
<div id="editable" contenteditable="true">
    Some sample content...
</div>
```

**Comment by couraud** [comment]
+1! 
Many thanks.

**Comment by ipeychev** [comment]
Fixed here: https://github.com/liferay/alloy-editor/issues/216
