### ISSUE TITLE
Can I save the created content?

### ISSUE THREAD

**Issue by swaathi** [liferay/alloy-editor#351]
Is it possible for me submit the created content as a form? I need to be able to save and update the data.

**Comment by ipeychev** [comment]
It should be, and it depends on how you are editing the content. For example, check this [link](http://docs.ckeditor.com/#!/guide/dev_savedata-section-saving-data-in-ckeditor-replacing-a-textarea), there are good advices.
AlloyEditor uses CKEditor's engine under the hood, so you can obtain the instance of CKEditor like this:
```
var alloyEditor = AlloyEditor.editable(...)
var ckeditorInstance = alloyEditor.get('nativeEditor')
```
Then, you can use all CKEditor's API out-of-the-box.

The other way is of course if you retrieve the data from the editor and store it to some of the fields in your form.

Hope that helps!
