### ISSUE TITLE
entities_processNumerical: 'force' without effect ?

### ISSUE THREAD

**Issue by dpobel** [liferay/alloy-editor#359]
I'd like to configure my AlloyEditor/CKEditor to produce only numerical entities so as mentioned in the config document of CKEditor, I try to set the config property `entities_processNumerical` to `force`. It's not documented anywhere but the config passed to `AlloyEditor.editable()` is mixed into the editor config so in the editor, I write something like:

``` js
AlloyEditor.editable(myNode, {entities_processNumerical: 'force'});
```

In a CKEditor plugin, I can verify that the config is correctly passed to CKEditor (`.config.entities_processNumerical` has the right value) but when I get the data from CKEditor, I still get `&nbsp;` in the code... I tried to set this config in the config.js loaded by CKEditor with the same result.

The setting seems to work correctly in a stock version of CKEditor.

So I'm a bit blocked and it seems like AlloyEditor does something that prevents this setting from working, but the question is what ?

**Comment by ipeychev** [comment]
About the not documented mixed configs, this is our bad. @jbalsas, could you add it to our guides, please? Also, the [question](https://github.com/liferay/alloy-editor/issues/357) from yesterday (how to use it from Angular) is a good candidate to be documented too.

About the configuration, I guess this [plugin](http://ckeditor.com/addon/entities) is missing. I don't think we include it in our default configuration of CKEditor's engine.

Thanks,

**Comment by jbalsas** [comment]
Hey @ipeychev, yeah, I'll make sure to add those to the documentation guides asap.

**Comment by wincent** [comment]
By way of "spring cleaning", I'm closing issues tagged with "question" that haven't had any activity in > 12 months. There have been quite a few releases since then and much has changed, and these "stale" issues are extremely unlikely to be acted on. Please feel free to comment and we can re-open on a case-by-case basis.
