### ISSUE TITLE
Is it possible to remove AlloyEditor after it is initialized?

### ISSUE THREAD

**Issue by sharpoverride** [liferay/alloy-editor#362]
This might not be place to ask, but I'd like to be able to destroy the editor once I'm done editing.
I have a single page app, so it doesn't make sense to keep all the listeners and editors created.

What's the intended way of clearing what CKEditor and AlloyEditor generate when I call editable?

**Comment by ipeychev** [comment]
Yes, just call the `destroy` method.

**Comment by sharpoverride** [comment]
Hi, On what?

**Comment by ipeychev** [comment]
Hey @sharpoverride,

When you create an instance of AlloyEditor, it will have this method. For example:
```
var editor = AlloyEditor.editable('editable');
editor.destroy();
```

See [here](http://alloyeditor.com/api/classes/Base.html#method_destroy) - AlloyEditor's Core class extends this class.

Hope that helps!

Thanks,

**Comment by sharpoverride** [comment]
Cool, thanks.
