### ISSUE TITLE
Toolbar always visible

### ISSUE THREAD

**Issue by jaysoneramos** [liferay/alloy-editor#363]
Background:
Our requirement is to fix the toolbar at the top of the editor. The problem is that - it only shows when the editor is focused.
Is there a way to set the toolbar always visible even the editor is not focused?

**Comment by jbalsas** [comment]
Hi @jaysoneramos 

As explained in other questions, AlloyEditor's toolbar is not meant to work in this way, but you can see how to do it [here](https://github.com/liferay/alloy-editor/issues/328#issuecomment-134308668).

@ipeychev Should we add this to the list of guides to do? :joy:

**Comment by ipeychev** [comment]
@jbalsas  Yeah, why not.

@jaysoneramos The default CKEditor UI comes exactly with a fixed toolbar on top. My question is: why didn't you choose CKEditor, but you preferred AlloyEditor with a fixed toolbar?

Thanks,

**Comment by jaysoneramos** [comment]
I like to use this editor as it has some advantage to CKEditor at some point but the only issue we have with Alloy is the toolbar, if there is a way to do it then we will go for this.

**Comment by ipeychev** [comment]
Okay, then just follow the link above and you will do it.

**Comment by jaysoneramos** [comment]
I have tried the link above but the toolbar appears only when the editor is focused. what we need is that the toolbar should always visible even the editor is not focus.

**Comment by jbalsas** [comment]
Hey @jaysoneramos, that is also explained in the same conversation, just scroll down a little bit :wink:

**Comment by jaysoneramos** [comment]
Hi @jbalsas,

I am using AlloyEditor v0.6.0 and try the easy hack you mention in here (https://github.com/liferay/alloy-editor/issues/328#issuecomment-134308668 )
![image](https://cloud.githubusercontent.com/assets/15257473/10777104/d1fc95f8-7d52-11e5-8034-0c88f20145d1.png)

but I got this error:
![image](https://cloud.githubusercontent.com/assets/15257473/10777055/41013c48-7d52-11e5-8d62-336095114a3f.png)

Seems the _mainUI does not exists in the editor.

**Comment by jbalsas** [comment]
Hey @jaysoneramos,

You're probably trying to do it way too soon. You should wait for the `uiReady` event before trying to access the `_mainUI` object. Give this a try:

```javascript
var editor = AlloyEditor.editable('editable');

editor.get('nativeEditor').on('uiReady', function(event) {
    editor._mainUI._setUIHidden = function() {};
});
```

**Comment by david1029** [comment]
@ipeychev 
Hello .. 
I have some problems alloyeditor static tool bar functions .. 
When user refresh alloyeditor page ,  this is working well .. 
When user go to another page , and user go to alloyeditor page , and then this is not working ... 
![bugs](https://cloud.githubusercontent.com/assets/15199228/22088706/9025b060-de18-11e6-8d9a-167e5bce2562.png)

If you have suggestion for this , please help me .. 

Thanks
