### ISSUE TITLE
toolbar does not disappear

### ISSUE THREAD

**Issue by kel093** [liferay/alloy-editor#371]
Hello. I am apologise if i duplicate the issue, but i don't found it in list of issue's. 
I am using the AlloyEditor and today saw strange behaviour. I selected the text after this the toolbar is appears, then i clicked on the any place on the screen and the toolbar does not disappear.
![bug](https://cloud.githubusercontent.com/assets/6705879/10938785/733cd998-8305-11e5-8f06-c7c6d1b3e051.png)

I investigated how plugin works and understood the problem, the problem is that editor.status == "ready" and listener "contentDom" will not be called. That's means that listeners "mousedown" and "keydown" are not be added to document.

I fixed this problem, please see my changes in function componentDidMount().

            if (editor && editor.status == "ready") {
                document.addEventListener('mousedown', this._mousedownListener);
                document.addEventListener('keydown', this._keyDownListener);
            } else {
                editor.once('contentDom', (function () {
                    document.addEventListener('mousedown', this._mousedownListener);
                    document.addEventListener('keydown', this._keyDownListener);
                }).bind(this));
            }

**Comment by ipeychev** [comment]
Hey @kel093,

Interesting issue! How exactly we can reproduce it?
Also, could you see if the following code snippet will fix your issue too:
```
editor.once('instanceReady', function() {
    document.addEventListener('mousedown', this._mousedownListener);
    document.addEventListener('keydown', this._keyDownListener);
}.bind(this));
```

Maybe we can just change the event and avoid the other "if".

Thanks,

**Comment by kel093** [comment]
I tried to change event "contentDom" on "instanceReady", but didn't help.

It's easy to reproduce, just call destroy() then init() on earlier initialized AlloyEditor.

Look like on this code:
<pre lang="javascript"><code>
var editor2 = AlloyEditor.editable('editable'); //init the AlloyEditor
setTimeout(function(){
    //reinit AlloyEditor
    editor2.destroy();
    editor2.init();
},1000);
</code></pre>

**Comment by ipeychev** [comment]
Ah, I see! This way of reinitializing is unsupported however. The function "init" is not supposed to be called manually.
The recommended way after destroying is to get a new fresh instance of the editor, like this:
```
var editor2 = AlloyEditor.editable('editable'); //init the AlloyEditor
setTimeout(function(){
    //reinit AlloyEditor
    editor2.destroy();
    editor2 = AlloyEditor.editable('editable');
},1000)
```

Thanks,

**Comment by kel093** [comment]
I tried this way, but It didn't help too.

**Comment by ipeychev** [comment]
Hm. Okay. Chema, would you have 5 mins to check this one? If not, I can try this evening.

@jbalsas

**Comment by jbalsas** [comment]
Yes, I'll check this one out later today

**Comment by jbalsas** [comment]
I just checked, and yeah, it does make sense that it would fail. I think the best fix would be to change the event from `contentDom` to `focus`. This way, we can even save the event initialization if the editor never gets really used.

I'll put a PR with this in a little while.

@kel093, I tested this, but could you verify this fixes the issue for you as well?

**Comment by kel093** [comment]
@jbalsas, I just tested and it looks well for me too.
Thanks for quick fix.

**Comment by ipeychev** [comment]
Hey @jbalsas,

Changing the event to focus breaks [one](https://github.com/liferay/alloy-editor/blob/e2a85401c669df27e386d912bc2bb440c4cf8e83/src/ui/react/test/alloy-editor.js#L109) of the tests on Firefox and all IEs.
After looking also on the comments [here](https://github.com/liferay/alloy-editor/pull/373#issue-115279433), let's try another fix, which will be to not wait for "contentDom or "focus" [here](https://github.com/liferay/alloy-"editor/blob/b5cf353a5c70cbaf86018bcac140e4b6f8fa2b54/src/ui/react/src/components/main.jsx#L105).
The change is committed, could you please check if that is OK for everybody?

@kel093

Thanks,

**Comment by jbalsas** [comment]
mmm... that's weird, they were passing for me... I guess only added the change for the `ae-editable` class part at the end and forgot to re-run the tests :(

Of course it makes sense that test will fail, we should update the initialization of the editors to fire a `focus` event before doing anything else. This is what will actually happen in practice when a user tries to work with the editor, isn't it?

The only thing that worried me was that some styling could flicker but I didn't see anything weird.

In any case I don't think attaching the events always will cause other issues. Will check later.

THanks!

**Comment by ipeychev** [comment]
Yeah, the first thing I tried was to add `focus` in the initialization, bit it didn't work. However, please check again, it was 4:30am :)

Focus is nasty event in general, very hard to deal, especially for testing. Had multiple issues previously with Firefox and since then I'm trying to avoid it. In this case it makes sense, if we can do it properly. Otherwise, let's attach the other events even before user starts to interact with the editor.

**Comment by jbalsas** [comment]
I think we can take the safe route here and avoid `focus` alltogether. I even have the feeling that this might save us from some issues in the future, so I'm fine with it.

And btw, I'm going to ask for a prohibition from 23pm to 6:30am on commits on this repo so you can get some more sleep :stuck_out_tongue_winking_eye:

**Comment by ipeychev** [comment]
Your request was declined. I will sleep when I get retired ;)
