### ISSUE TITLE
When clicking a link, possible to show a navigate/change/remove bubble?

### ISSUE THREAD

**Issue by kushal** [liferay/alloy-editor#376]
This is the behavior in Gmail, TinyMCE and most other editors. It feels buggy that this isn't the behavior in Alloy. (Awesome editor, btw, thanks so much!)

**Comment by ipeychev** [comment]
Hey @kushal,

Thanks for the report and for the nice words. We have similar behavior (except for navigate), with the difference that you have to click twice on a link or select part of it or the whole link - then the popup will appear and you will be able to delete/edit it.
However, I think such change would make sense. @jbalsas, could you please talk with the UX to see their opinion too?

Thanks,
Thanks,

**Comment by jbalsas** [comment]
Hey @ipeychev,

I'm in Chicago for the whole week, but I'll make sure to bring this up to the UX guys as soon as I get back next week!

**Comment by nickbouton** [comment]
+1 for this, the existing link behaviour was pretty unexpected.

I would love to see something similar to Gmail. We are working on a setup where we don't destroy the editor instances (i.e. always editable, but the UI is styled differently depending on the current editing mode or whether the editable container has focus), and even if we don't open a link directly on click (which would make editing difficult), offering the option of editing/navigating/deleting on a single click would make more sense. The double-click approach did not work for me either, FYI.

**Comment by jbalsas** [comment]
Hi, we have two different issues here:

1. __Need to double click to edit a link__. We can try to turn that into a single click, so the link edit ui will show automatically. This will be consistent with other one-click interactions we already have (image, table), so we can give this a go.

2. __Need to navigate to a link__. We used to show a tooltip on hovering over a link that allowed you to do this, but we never got around to implement it for the React UI. As it is, the edit link UI is growing quite big and complex, so we'd rather keep this out of there, but the way I see it, we have several options:
 - Implement a link tooltip for the React UI to allow navigation
 - Add a button to the edit link ui to navigate.
 - Add respective properties so it could be chosen wether to show the tooltip, the button, both or none.

What do you guys think?

**Comment by kushal** [comment]
Awesome, thanks!
