### ISSUE TITLE
Plugins 'ae_' are not initialized if ckeditor own plugins are present

### ISSUE THREAD

**Issue by jbalsas** [liferay/alloy-editor#379]
When using the `alloyeditor-no-ckeditor` version, some plugins might conflict with the existing one. This affects

- `dragresize`
- `tableresize`
- `tabletools`

If the CKEditor installation has the original bundled plugins, the namespaced ones won't get created. Then, if the editor is instantiated doing the following (not code complete):

```javascript
var editor = AlloyEditor.editable('editable', {
    extraPlugins: 'ae_dragresize,ae_tableresize,ae_tabletools',
    removePlugins: 'dragresize,tableresize,tabletools'
});
```

The namespaced plugins won't produce any behaviour since we are returning empty objects for them.

Since we namespaced them, it should be safe enough to avoid the check for the original ones.

**Comment by ipeychev** [comment]
Okay. In any case, those who include CKEditor and then our UI are assumed to know what they are doing :)

**Comment by jbalsas** [comment]
Hopefully noone other than myself has to deal with an externally downloaded CKEditor and the pain it brings to the table :joy:
