### ISSUE TITLE
How to set CKEditor config parameters on live instance?

### ISSUE THREAD

**Issue by nickbouton** [liferay/alloy-editor#385]
Hi there, first off, just wanted to say very nice work on Alloy Editor. I've been using it for a couple of weeks now and I'm finding it quite full-featured.

I have a question about setting custom CKEditor config parameters. I would like to disable image resizing on images uploaded into the editor, and apparently one of the following CKEditor config settings should do the trick:

```
CKEDITOR.replace('instanceId', {
  resize_enabled: false;
  image2_disableResizer: true;
};
```

Now, with a regular CKEditor instance, we could use the `CKEDITOR.replace` method to re-initialize the editor with custom configuration values. How would I go about doing this with AlloyEditor? Right now when I try that method, I get the following error:

`Uncaught The editor instance "[EditorInstanceName]" is already attached to the provided element.`

This is using the ID of the AlloyEditor as the first argument to `CKEDITOR.replace`. I'm assuming there's some better way to do this, as simply passing these custom config values through the AlloyEditor's config object doesn't seem to work either. Would appreciate any suggestions!

**Comment by ipeychev** [comment]
Hey Nick,

It is very simple - all the configuration parameters you pass to AlloyEditor during the creation, will be automatically propagated to CKEditor's engine too.
```
var editor2 = AlloyEditor.editable('editable', {
  key1: 'val1'
});
```

Thanks,

**Comment by nickbouton** [comment]
@ipeychev Thanks for the confirmation. I thought that passing configuration parameters through the AlloyEditor config object would be a standard pass-through, but so far I hadn't had any luck getting them to stick on the internal CKEditor instance. This is my first time using CKEditor so I'll take a look through the docs and see if I'm missing a plugin.

If you have an insight on turning off client-side manual image resizing, though, that would be super helpful.

Thanks!

**Comment by ipeychev** [comment]
Maybe you can also try to disable our plugin - "ae_dragresize"?

**Comment by nickbouton** [comment]
@ipeychev That did the trick for my resize issue, thank you! I guess that also explains why the config parameters I was passing didn't appear to be making any difference, because they were being overridden internally. Thanks for the help!
