### ISSUE TITLE
Hide toolbar on clicking on the save button on the edit link dialog

### ISSUE THREAD

**Issue by vidriloco** [liferay/alloy-editor#387]
Hello. 
I am building a custom edit link dialog that allows the user to either remove the link from the text or dismiss the dialog. However, I am having trouble to manage to dismiss the dialog via the button as ReactJS only allows to unmount parent components, but this component is loaded whenever a match with a link string occurs as far as I see on the initialization config block for building the AlloyEditor instance. 

What would be the best way to approach this?

Thanks, and congrats for such a nice piece of software :)

DISCLAIMER: I am starting with ReactJS, hope I am not asking a stupid question :S

**Comment by ipeychev** [comment]
Hey @vidriloco,

Thanks for the nice words!
If I haven't misunderstood the question, the correct way might be to remove the selection on clicking on this "dismiss" button. The selection can be moved to the end of the link, so the user will be able to continue writing, or just to be made empty. In this case, the next time, when the selection is then being evaluated, no toolbar will be displayed, because it will be empty (there will be no match for a link).

To make the selection empty, you can use CKEditor's API. On top of my head, you may try this code:
```
editor.get('nativeEditor').getSelection().removeAllRanges();
```

where `editor` is AlloyEditor's instance.

Hope that helps and please let us know if that works for you.

Chema, do you have some ideas too?
@jbalsas

**Comment by vidriloco** [comment]
Thanks ipeychev. I had already tried hidding it by using that method, but it does not seems to do anything; not even the selection gets removed from the editor, which is kind of weird, as I suppose it should do at least that, right?

**Comment by jbalsas** [comment]
Hey @vidriloco, right you'll need to fire an `actionPerformed` event in addition to the `removeAllRanges` call since that won't fire an `editorInteraction` event.

```javascript
var editor = this.props.editor.get('nativeEditor');

editor.getSelection().removeAllRanges();
editor.fire('actionPerformed', this);
```

@ipeychev, this is caused by https://github.com/liferay/alloy-editor/blob/master/src/core/uicore.js#L114-L115 only listening to mouse and key events... maybe we should add [selectionChange](http://docs.ckeditor.com/#!/api/CKEDITOR.editor-event-selectionChange) into the mix?

**Comment by jbalsas** [comment]
On a related note, I'm working on some changes on the link selection and edit behaviour in this branch https://github.com/jbalsas/alloy-editor/tree/AE-119-A_Target_Final

@ipeychev, could you get the branch and give it a try to see what you think or what would you expect?

@vidriloco is that closer to what you're trying to achieve?

**Comment by ipeychev** [comment]
Hey Chema,

Yeah, `actionPerformed` is needed, of course. I forgot mentioning it.
About adding `selectionChange` to the list of events - on theory mouse/key events shouldn't be used, but only `selectionChange`. The initial implementation was like this (for a very short time), because this approach just didn't work. The event wasn't called properly, causing the toolbars to not appear or to appear after some delay.

**Comment by vidriloco** [comment]
Hey Guys! 

Thanks again for the replies. I had already tried to fire the actionPerformed event after mangling with the editor state on this action i am implementing, but again, the same output. 

Could it be that I am missing something?

**Comment by jbalsas** [comment]
Hey @vidriloco,

Yeah, then it may be something else. I tested the snippet of code I showed and the toolbar was being dismissed properly.

How and where are you invoking this actions?

**Comment by vidriloco** [comment]
Ok. I redefined the ButtonLink class to a ButtonEditLink class with this render method and a `_closeEditLinkTool` method that closes the dialog. Also, I am using the already defined `_removeLink` method as it is defined on the ButtonLink class. The code snippet is shown below:

        /**
         * The rendering method in ReactJS
         */
        render: function render() {
            var cssClass = 'ae-button ' + this.getStateClasses();
            
            return (
                <div ref="editToolBar" className="ae-container-edit-link">
                    <button aria-label={"Remove link"} className="ae-button" disabled={!this.state.element} onClick={this._removeLink} title={AlloyEditor.Strings.remove}>
                        <span className="ae-icon-remove"></span>
                    </button>
                    <button aria-label={"Save"} className="ae-button" disabled={!this.state.linkHref} onClick={this._closeEditLinkTool} title={AlloyEditor.Strings.confirm}>
                        <span className="ae-icon-ok"></span>
                    </button>
                </div>
            );
        },

        /**
         * Closes the edit tool link in the editor element.
         *
         * @protected
         * @method _closeEditLinkTool
         */
        _closeEditLinkTool: function() {
          var editor = this.props.editor.get('nativeEditor');
          editor.getSelection().removeAllRanges();
          editor.fire('actionPerformed', this);
        },

**Comment by ipeychev** [comment]
Sorry, could you please paste the whole button code? Maybe there is something else, because the code in `_closeEditLinkTool` should work, as we mentioned above. Also, on which browser you are executing this code?

Thanks,

**Comment by vidriloco** [comment]
This is the full code for the button:

    (function () {
    'use strict';

    /**
     * The ButtonLink class provides functionality for creating and editing a link in a document. ButtonLink
     * renders in two different modes:
     *
     * - Normal: Just a button that allows to switch to the edition mode
     * - Exclusive: The ButtonLinkEdit UI with all the link edition controls.
     *
     * @uses ButtonStateClasses
     *
     * @class ButtonLink
     */
    var ButtonPoiEdit = React.createClass({
        displayName: 'ButtonPoiEdit',

        mixins: [AlloyEditor.ButtonStateClasses],

        // Allows validating props being passed to the component.
        propTypes: {
            /**
             * The editor instance where the component is being used.
             *
             * @property {Object} editor
             */
            editor: React.PropTypes.object.isRequired,

            /**
             * The label that should be used for accessibility purposes.
             *
             * @property {String} label
             */
            label: React.PropTypes.string,

            /**
             * The tabIndex of the button in its toolbar current state. A value other than -1
             * means that the button has focus and is the active element.
             *
             * @property {Number} tabIndex
             */
            tabIndex: React.PropTypes.number
        },

        // Lifecycle. Provides static properties to the widget.
        statics: {
            /**
             * The name which will be used as an alias of the button in the configuration.
             *
             * @static
             * @property {String} key
             * @default link
             */
            key: 'poi-edit'
        },

        getInitialState: function() {
            var link = new CKEDITOR.Link(this.props.editor.get('nativeEditor')).getFromSelection();
            var href = link ? link.getAttribute('href') : '';

            return {
                element: link,
                linkHref: href
            };
        },
        
        /**
         * Checks if the current selection is contained within a link.
         *
         * @method isActive
         * @return {Boolean} True if the selection is inside a link, false otherwise.
         */
        isActive: function isActive() {
            return new CKEDITOR.Link(this.props.editor.get('nativeEditor')).getFromSelection() !== null;
        },

        /**
         * Lifecycle. Renders the UI of the button.
         *
         * @method render
         * @return {Object} The content which should be rendered.
         */
        render: function render() {
            var cssClass = 'ae-button ' + this.getStateClasses();
            
            return (
                <div ref="editToolBar" className="ae-container-edit-link">
                    <button aria-label={"Remove link"} className="ae-button" disabled={!this.state.element} onClick={this._removeLink} title={AlloyEditor.Strings.remove}>
                        <span className="ae-icon-remove"></span>
                    </button>
                    <button aria-label={"Save"} className="ae-button" disabled={!this.state.linkHref} onClick={this._closeEditLinkTool} title={AlloyEditor.Strings.confirm}>
                        <span className="ae-icon-ok"></span>
                    </button>
                </div>
            );
        },
        
        /**
         * Closes the edit tool link in the editor element.
         *
         * @protected
         * @method _closeEditLinkTool
         */
        _closeEditLinkTool: function() {
          var editor = this.props.editor.get('nativeEditor');
          editor.getSelection().removeAllRanges();
          editor.fire('actionPerformed', this);
        },
        
        /**
         * Removes the link in the editor element.
         *
         * @protected
         * @method _removeLink
         */
        _removeLink: function() {
            var editor = this.props.editor.get('nativeEditor');
            var linkUtils = new CKEDITOR.Link(editor);
            var selection = editor.getSelection();
            var bookmarks = selection.createBookmarks();

            linkUtils.remove(this.state.element);

            selection.selectBookmarks(bookmarks);

            // We need to cancelExclusive with the bound parameters in case the button is used
            // inside another in exclusive mode (such is the case of the link button)
            this.props.cancelExclusive();

            editor.fire('actionPerformed', this);
        }
    });

    AlloyEditor.Buttons[ButtonPoiEdit.key] = AlloyEditor.ButtonPoiEdit = ButtonPoiEdit;
    })();

**Comment by vidriloco** [comment]
Ohh, and I am executing it on Firefox and Chrome, on both the same behaviour. 
What could it be? I am almost finished with my shiny editor, but still cannot overcome that little issue.

**Comment by ipeychev** [comment]
Probably the selection it locked. Before removing all the ranges, try to unlock it:
`editor.getSelection().unlock();`
You may also think to move the cursor to the end of the link or somewhere else, for that you can use CKEditor's/browser's native API.

Hope that helps!

**Comment by vidriloco** [comment]
Yes, that did the trick! 

Please note that this issue is also visible on your Live Demo editor. 

Thank you guys :+1:

**Comment by ipeychev** [comment]
The problem on our site seems to be related to Disqus :(
My brief investigation found that after link creation and clicking back, one of its files sends Ajax with CORS and this somehow "crashes" so the browser navigates to the link.
@jbalsas, any comments and suggestions for fixing (except removing Disqus from the site)?

**Comment by jbalsas** [comment]
Hey Iliyan, not sure what issue exactly were you referring to... I see you've removed disquss form the live-demo page, so it's probably not happening right now, is it?

**Comment by ipeychev** [comment]
Hey Chema,

I removed it, and yes, it works now, but there were comments on this page which seem now to be gone. To have comments there isn't a bad idea, if you can see how can we avoid this issue without removing Disqus entirely from this page, would be better.
