### ISSUE TITLE
Alloy with Webpack and React

### ISSUE THREAD

**Issue by fractall** [liferay/alloy-editor#389]
Hello, 
Is it possible to explain it better how to implement Alloy Editor as a React component with ES6 import using webpack?

I'm trying 
require('alloyeditor/dist/alloy-editor/alloy-editor-core-min.js');

But am getting "CKEditor is not defined".

Then I required('../ckeditor.js')

Now am getting Cannot read property 'PropTypes' of undefined.

**Comment by NotBrianZach** [comment]
How did you solve this?

**Comment by aaron7pm** [comment]
++ would like to know the solution as well

**Comment by jerson** [comment]
+10000

**Comment by ipeychev** [comment]
Okay guys, will release a new version and write a guide with a possible solution the next days.

Thanks,

**Comment by ipeychev** [comment]
Here is an example [repository](https://github.com/ipeychev/alloyeditor-react-component).

Hope that helps!

Thanks,
