### ISSUE TITLE
Alloy can't find relative paths

### ISSUE THREAD

**Issue by fractall** [liferay/alloy-editor#390]
I'm getting a bunch of 404 errors from css, language a config files and a 'dir' undefined.
Like:
http://localhost:8080/config.js?t=F62B Failed to load resource: the server responded with a status of 404 (Not Found)

I'm server-side rendering Alloy with React and webpack.

How can I make Alloy find the files it needs if they are excluded inside a node_modules folder? I

**Comment by ipeychev** [comment]
You closed the issue, I hope this means you resolved it meanwhile?

**Comment by luisrudge** [comment]
I'm having the same problem.. @fractall did you ever fixed this?

![image](https://cloud.githubusercontent.com/assets/941075/18425432/d8a4999e-788f-11e6-8a37-a6bb13f7930b.png)

**Comment by ipeychev** [comment]
Please look at the source of [this](https://github.com/ipeychev/alloyeditor-react-component) repo and on [this](https://github.com/ipeychev/alloyeditor-react-component#i-dont-want-to-copy-alloyeditor-to-the-dist-folder-like-you-did) paragraph too.
