### ISSUE TITLE
Blur the editor when a child component has been mounted

### ISSUE THREAD

**Issue by vidriloco** [liferay/alloy-editor#393]
Hey guys, this is me again.

This issue solution may not be fully related to AlloyEditor, but maybe more to ReactJS, however, I ask it here as I am using ReactJS due AlloyEditor.

I am close to finish the new and shinny text editor for which I am using your library. Now I have another question regarding a task I have not yet been able to achieve:

When the user clicks on the add link button on my editor, it is shown with a modal window and an input field on it. However, the input within the modal window is not taking focus, but neither the textarea of the editor is losing it. 

My question is, how can i make either the input on the modal get focus or the text editor input get blured.

**Comment by ipeychev** [comment]
Hello,

Did you try the simplest one - to set the focus of the input field when the dialog opens and to invoke the `focus` method of the native editor when the dialog closes?

Thanks,

**Comment by jbalsas** [comment]
Hey @vidriloco, you can check for example how we do it for the link input [here](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/components/buttons/button-link-edit.jsx#L34-L40)

**Comment by vidriloco** [comment]
Thanks @jbalsas , did checked the linked example, but basically, it should work with the `focus` event, as @ipeychev suggested, no?

**Comment by jbalsas** [comment]
Hey @vidriloco, it should work invoking the `focus` method of the input field you want to focus on. The key part of the example is that it makes sure the element has been rendered before attempting to focus it.

**Comment by vidriloco** [comment]
Calling `focus` on the componentDidMount method, should be correct, no?

**Comment by ipeychev** [comment]
Yes.
