### ISSUE TITLE
Broken assets after minification process on Ruby on Rails

### ISSUE THREAD

**Issue by vidriloco** [liferay/alloy-editor#394]
Hello guys

I am having the following error when making a selection on the editor:
AlloyEditor.Strings is undefined
   { 'aria-label': AlloyEditor.Strings.styles, className: cssClasses, 'data-tabinde...

I suspect that somehow, the minification process is affecting the AlloyEditor.Strings property, but have already tried two libraries for JS minimizing it with no success. It would be nice to know if someone has had this trouble while on minifying their assets while using AlloyEditor. 

Also getting the following error on the JS console:
Error: Plugin "contextmenu" cannot be removed from the plugins list, because it's required by "tabletools" plugin.

Thanks!

**Comment by ipeychev** [comment]
Hello,

Why are you trying to minify AlliyEditor? It already comes with a minimized version. Use it instead to minimize it again.

Thanks,

**Comment by vidriloco** [comment]
Well, I am not trying to minify the already minified version, but the normal one. Anyway, will leave it out of the minification process to see if that gets it fixed. 

Thanks :)

**Comment by ipeychev** [comment]
Great, please reopen if you need something more.
