### ISSUE TITLE
How to disable image resizing

### ISSUE THREAD

**Issue by CreepGin** [liferay/alloy-editor#395]
After a new image is inserted, users can interactively resize the image using the drag handles. I think it's the work of the `dragresize` plugin. I've been playing around with the config for a bit but can't seem to get rid of this effect. 

Any help is appreciated!

**Comment by CreepGin** [comment]
Figured it out.

```
removePlugins: "ae_dragresize"
```

**Comment by ipeychev** [comment]
:+1:
