### ISSUE TITLE
Creating a link which, crosses element boundaries, causes JS errors and a buggy toolbar.

### ISSUE THREAD

**Issue by blzaugg** [liferay/alloy-editor#40]
**Example Content:**
```html
<p>Some text <strong>with some bold text</strong> and some normal text.</p>
```

**Steps to replicate:**
 1. Go to Example/Live Demo page. http://alloyeditor.com/examples/
 1. Using your cursor, select a range of text which stars in some *bold* and ends in some normal text.
 1. The toolbar will display.
 1. Click the [link icon] and input a URL.
 1. Click the [checkmark].

**Expected Results:**
 - A single link created around selection. With with a child `<strong>`.
```html
<p>Some text <strong>with some</strong> <a href="..."><strong>bold text</strong> and some normal</a> text.</p>
```

**Actual Results:**
 - Two links, one in the `<strong>` on one outside.
```html
<p>Some text <strong>with some<a href="...">bold text</a></strong> <a href="...">and some normal</a> text.</p>
```
 - JS error: `Uncaught TypeError: Cannot read property 'setAttributes' of null `
 - Toolbar behavior is now buggy.

**Comment by ipeychev** [comment]
Fixed in version 0.7
