### ISSUE TITLE
Getting the Content , Events ?

### ISSUE THREAD

**Issue by daslicht** [liferay/alloy-editor#403]
Hi,
how do you get the generated html?

Are there any Event listeners such as BeforeImageUpload or Save etc ?

**Comment by ipeychev** [comment]
Hello,

1. Programmatically the generated content you can get using CKEditor's `getData()` function:
```javascript
var editor = AlloyEditor.editable('editable');
var data = editor2.get('nativeEditor').getData();
```

2. AlloyEditor does not deal with image upload directly. There is an event which will be fired when an image is added to AlloyEditor - `imageAdd`. It will be fired, when you add image via D&D, paste, etc.
The payload will be an object:
```javascript
var payload = {
	el: el,
	file: file
};
```

Where `el` is the inserted image element to the DOM, and `file` is the native `File` object. The image `src` will be Base64 string, and you can very easy upload the image to the server, then to replace the URL with what the server will return.

If you don't want to do this, you can try to use CKEditor's plugins for uploading images (look on their site). Most of the CKEditor's plugins will work OOTB in AlloyEditor, see [here](http://alloyeditor.com/guides/how_to_use_ckeditor_plugins/) how to integrate them to AlloyEditor.

Hope that helps, if not, please reopen the ticket!

Thanks,
