### ISSUE TITLE
Getting the text value in React

### ISSUE THREAD

**Issue by beeant** [liferay/alloy-editor#414]
I'm currently following the AlloyEditor x React integration from https://github.com/ipeychev/alloyeditor-react-component.

After I finished editing the text, how do you get the text value? Or it would be better it can do binding with React state/props.

Thank You

**Comment by ipeychev** [comment]
The text you can retrieve via CKEditor's API:
`editor.get('nativeEditor').getData();`
where `editor` is an AlloyEditor instance. Then, you can set the content wherever you want, to submit it, etc.

Thanks,

**Comment by beeant** [comment]
The `editor.get('nativeEditor').getData();` is getting the html with `data-reactid` attribute. Is this normal?
Thank you

**Comment by ipeychev** [comment]
Yes, this is the element, passed [here](https://github.com/ipeychev/alloyeditor-react-component/commit/45e58b2fa6538f2691cd6d1cfc68f921c58c8294#L6).

**Comment by beeant** [comment]
When I only have image on the editor, I'm getting this error:
```javascript
Uncaught IndexSizeError: Failed to execute 'extend' on 'Selection': 1 is larger than the given node's length.
```

**Comment by beeant** [comment]
oh sorry, seems to be fixed by adding `<p></p>` to the initial empty editor.
