### ISSUE TITLE
Camera button does not work on insecure origins in Chrome

### ISSUE THREAD

**Issue by jbalsas** [liferay/alloy-editor#421]
Chrome has deprecated [Powerful Features on Insecure Origins](https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins).

This causes the `camera` button to how an alert `An error occurred! [object NavigatorUserMediaError]` and a warning on the devtools console with the message _getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details._

We should properly capture those errors so the UI is updated accordingly without bothering the user.

**Comment by ipeychev** [comment]
Mmm, yeah, and we should switch alloyeditor.com to HTTPS and always to redirect there, as it should be.

**Comment by jbalsas** [comment]
Yeah, we can do that for the site, but we still should fix the button so it fails more gracefully for someone using it in HTTP.

**Comment by ipeychev** [comment]
Yeah, sure
