### ISSUE TITLE
SCRIPT5022: TypeMismatchError When inserting an image

### ISSUE THREAD

**Issue by sergiy-evision** [liferay/alloy-editor#424]
I got this error when trying to insert image (IE11, Windows 8.1 x64). this bug is reproducible on your Live Demo page http://alloyeditor.com/demo/
![image](https://cloud.githubusercontent.com/assets/8777681/12261840/fb8f411a-b923-11e5-8640-6e9d61c5f0f3.png)

**Comment by ipeychev** [comment]
Hello,

I just tried on the demo page and it was inserted correctly. Maybe it happens with some specific image type? Could you provide a test image?

Thanks,

**Comment by sergiy-evision** [comment]
Hello,
It seems to fail on any JPG image in IE 11. in chrome or FF it works fine.

Thanks,

**Comment by ipeychev** [comment]
I see. With JPG file and IE11 the image inserts correctly, but there is also an error in the console, this is the what happens. Correct?

**Comment by sergiy-evision** [comment]
@ipeychev, exactly, image was inserted but error logged on console. Thanks for quick fix :+1:
