### ISSUE TITLE
Toolbar is not shown by IE in the correct position

### ISSUE THREAD

**Issue by antoniopol06** [liferay/alloy-editor#425]
If you scroll on IE and you double click some word, toolbar will appear on top of the page. It must be appear over the word.

**Comment by ipeychev** [comment]
Hey @antoniopol06,

Thanks for the report and for the PR.
On which IE does it happen? I tested on the [Live demo](http://alloyeditor.com/demo/) and on the demo page using IE9, IE10 and IE11 and the toolbar appears correctly?
Also, with the PR you sent Toolbars shows at the beginning of the selection, not where the user released the mouse. Please see the attached screencast.
![test](https://cloud.githubusercontent.com/assets/78014/12278505/cba9644a-b981-11e5-98c9-fad8e19d05ba.gif)

Thanks,

**Comment by antoniopol06** [comment]
Hi @ipeychev 
The problem was over Windows 8.1 on IE 10. 
![toolbar](https://cloud.githubusercontent.com/assets/3017821/12293324/0e7b2120-b9f3-11e5-982d-98485554dfc8.gif)

I updated my PR and the problem that toolbar shows at beginning of the selection is fixed too.

**Comment by ipeychev** [comment]
Okay, I see!
Where is the updated code however? [Here](https://github.com/antoniopol06/alloy-editor/commit/54548ca0f42b337d90b9d85eae51a5dab95d637b) I see only those from yesterday?

**Comment by antoniopol06** [comment]
Sorry @ipeychev , now PR is ready.
