### ISSUE TITLE
alloyeditor-ocean.svg doesn't exist

### ISSUE THREAD

**Issue by ipeychev** [liferay/alloy-editor#428]
Font-template contains the following code:
```
url('<%= fontPath %><%= fontName %>.svg#<%= fontName %>') format('svg');
```

However, in the result font folder, there is no such font. This line should be removed from the template.

Originally reported here:
https://github.com/ipeychev/alloyeditor-react-component/issues/1

**Comment by hew** [comment]
Still no svg font. Webpack still errors out.

**Comment by ipeychev** [comment]
I'm not sure what you mean with "still no svg font". Isn't [this](https://github.com/liferay/alloy-editor/tree/master/dist/alloy-editor/assets/fonts) what are you looking for?
