### ISSUE TITLE
Add method to disable an editor

### ISSUE THREAD

**Issue by brendanhowell** [liferay/alloy-editor#436]
There is currently no method (that I can find) to disable the editor once it is activated.  This would be nice to have in order to allow users to click links & media once done with editing as well as just keeping the UI from appearing in "read-only" modes.

**Comment by jbalsas** [comment]
Hey @brendanhowell, you should be able to do this already using the [CKEDITOR.editor.setReadOnly method](http://docs.ckeditor.com/#!/api/CKEDITOR.editor-method-setReadOnly) like this:

```javascript
editor.get('nativeEditor').setReadOnly();
```

**Comment by brendanhowell** [comment]
Thanks @jbalsas!  This is closer but not quite what I need.  The editing UI does not appear any more but the component is still stealing clicks, so I can't click on the link I've just created.  It also still puts the dotted border around the div but this I can live with.  Is there a way to turn off mouse event stealing or at least pass those events through?

**Comment by jbalsas** [comment]
Hey @brendanhowell, I think this is the expected CKEditor behaviour based on 

- [Links are not handled correctly in a readonly block](https://dev.ckeditor.com/ticket/6032)
- [Links with children elements are not handled correctly in a readonly block](https://dev.ckeditor.com/ticket/10912)

See https://github.com/ckeditor/ckeditor-dev/blob/master/core/editable.js#L921 for the specific code capturing the link clicks.

I imagine it should be fairly simple to create a custom listener that you could enable when switching to read-only mode that would check if you clicked on a link and launch navigation.

Hope that helps!

**Comment by brendanhowell** [comment]
Hi @jbalsas I see. I was assuming that there would be a simple on/off switch for the editor but it seems most other users have cases where editing will take place in an "Editor View" on a separate page from the one where people will then click on the links.  Or that switching from "edit" to "read/use" mode would be done with a page load which is what I guess I will do.  This would be a nice feature to have if the goal of this project is to break down the classic CMS-style division of labor/interface between reading and writing.

**Comment by jbalsas** [comment]
Hey @brendanhowell, that sounds reasonable...

@ipeychev do you think we should add some kind of support for this use case on top of the default CKEditor behaviour?

**Comment by ipeychev** [comment]
Yes, Chema, I do.

**Comment by brendanhowell** [comment]
Very cool.  Let me know if I can help with testing.  I would try to implement it myself but given my limited knowledge of the code I am afraid it would be a messy hack.
