### ISSUE TITLE
Align text right with big toolbar

### ISSUE THREAD

**Issue by FilipeQ** [liferay/alloy-editor#437]
![example](https://cloud.githubusercontent.com/assets/7237584/12450740/74c9aae8-bf7d-11e5-8666-76fd266c5fc4.png)

When the text is aligned right and the toolbar need to grow vertically the top style dont change, toolbar hide the text.

**Comment by ipeychev** [comment]
Hey @FilipeQ,

In this case I would say it is better if you set some minimal width of the toolbar to fit all these icons and it will stay on one line even when the text is right aligned.
I don't see how can we handle this situation automatically. If you see how, please reopen this issue.

Thanks,
