### ISSUE TITLE
Live demo and 0.7.5 currently broken

### ISSUE THREAD

**Issue by hiddentao** [liferay/alloy-editor#447]
Just tried the live demo at http://alloyeditor.com/demo/ in Chrome Canary (Version 50.0.2627.0 64-bit).

Getting errors in the JS console:

```js
Uncaught SyntaxError: Identifier '_typeof' has already been declared
(index):591 Uncaught ReferenceError: AlloyEditor is not defined(anonymous function) @ (index):591(anonymous function) @ (index):638
(index):652 Uncaught ReferenceError: AlloyEditor is not defined(anonymous function) @ (index):652(anonymous function) @ (index):757
```

It seems that in  0.7.5 the `_typeof` boilerplate function gets defined multiple times (probably due to the build script concatenating files to generate the finals). 

Though it looks like this is already fixed in the latest `master`.

**Comment by ipeychev** [comment]
Yes, this has been already reported. We don't know what is the reason, but we don't care much about unstable versions of Chrome and we don't test again them. If this happens on the stable Chrome, we will take care.

Thanks,

**Comment by hiddentao** [comment]
Fair enough. I managed to get it working anyway with the latest `master`.
