### ISSUE TITLE
How to convert base64 image to file?

### ISSUE THREAD

**Issue by Qlipoth** [liferay/alloy-editor#453]
Hello, I'm using alloy-editor with sails.js framework. When i insert image it is in base64 format. 
To upload this image  it is necessary that the image was a file, like value of input type='file'. How to decode image to desired format?

**Comment by ipeychev** [comment]
Hello,

There is no need to convert it. AlloyEditor fires an event when an image is added. You will receive an File object, representing the image and you can use it in order to upload it:
```
var editor = AlloyEditor.editable('editable');
editor.get('nativeEditor').on('imageAdd', function(event) {
    console.log(event.data.file);
});
```

Thanks,

**Comment by Qlipoth** [comment]
Thanks for the answer, but event.data.file is undefined =(

**Comment by ipeychev** [comment]
No, it is like this. Which browser are you using and how do you insert the image? From the image add button?

**Comment by Qlipoth** [comment]
I'm using Chrome browser. I insert image by "add" in alloy-editor

**Comment by ipeychev** [comment]
It works fine, check the screencast below:

![image-add](https://cloud.githubusercontent.com/assets/78014/12716015/eb2ee860-c8dd-11e5-8101-9b2fb8651304.gif)

**Comment by Qlipoth** [comment]
Hello, I took test index.html from dist folder and wrote code from screencast, but data.file is undefined. 
What am I doing wrong?

**Comment by ipeychev** [comment]
It is hard to guess. Which version of the editor are you using? Why don't you clone the repo, build it, write this code and run it? It should work OOTB.
If it doesn't work for you, then might the issue is in the browser. As start, please try to disable any extensions.

Thanks,
