### ISSUE TITLE
How to set a placeholder?

### ISSUE THREAD

**Issue by coniel** [liferay/alloy-editor#454]
It seems like Alloy Editor ships with a placeholder plugin, but I can't figure out how to set the placeholder (tried setting a `placeholder` attribute as well as passing it as a config key). Do I need to activate the plugin somehow?

**Comment by ipeychev** [comment]
Hello,

[Here](https://github.com/liferay/alloy-editor/blob/be140ea6a08dcdbb23ef84f2b7f7a6e5ee982046/src/ui/react/demo/index.html#L19) is how we are using it. You will have to set `data-placeholder` attribute.
