### ISSUE TITLE
How to manage the localization of the title attribute?

### ISSUE THREAD

**Issue by CreepGin** [liferay/alloy-editor#455]
Right now the `title` and `aria-label` attributes are set to "Rich Text Editor, textarea-editor" by default (English locale). I'm seeking to change the localizations, and am currently doing it in the `instanceReady` handler. Is there a more suitable way to do this?

**Comment by ipeychev** [comment]
Hello,

You can achieve it by passing the title attribute to the configuration, like this:
```
var editor = AlloyEditor.editable('editable', {
    title: 'My new title and aria-label here'
});
```

Thanks,
