### ISSUE TITLE
Pasting content containing links is broken

### ISSUE THREAD

**Issue by emilecantin** [liferay/alloy-editor#478]
Steps to reproduce:

* Open up the Alloy Editor demo (http://alloyeditor.com/demo/)
* Copy this paragraph:

> Quis id nobis delectus eaque sit aut. Ad iure [omnis](http://example.com) consectetur autem in incidunt. Ipsa nihil nobis autem aut tempora. Quos neque amet praesentium. Illum ex esse sit.

* Notice how the text cuts at the link, and Alloy thinks the whole thing is a link.

Tested using Chrome 48 on OSX.

**Comment by ipeychev** [comment]
@emilecantin Released [v1.0.1](https://github.com/liferay/alloy-editor/releases/tag/v1.0.1) with this fix
