### ISSUE TITLE
Replace mixins

### ISSUE THREAD

**Issue by ipeychev** [liferay/alloy-editor#479]
Since React 0.13 mixins are deprecated. It would be nice to replace them with something else, for example [this](http://justinfagnani.com/2015/12/21/real-mixins-with-javascript-classes/) one.

**Comment by antoniopol06** [comment]
Last July React published [Mixins Considered Harmful](https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html)

**Comment by jbalsas** [comment]
Adding this to the `2.0` milestone.

**Comment by wincent** [comment]
There are no no longer any mixins on the 2.x-develop branch.
