### ISSUE TITLE
Removing tags that aren't on a whitelist

### ISSUE THREAD

**Issue by sei-dmorda** [liferay/alloy-editor#480]
Hi folks,

Is there a way to automatically remove tags that don't match a whitelist of tags allowed? 

For example, I have users that copy/paste content from Word to AlloyEditor. When they do that, many of the inline styles and other formatting come along with it. 

I'd like to be able to automatically strip any tags that don't match a whitelist so that they are automatically removed when the user pastes them into the AlloyEditor. That way the only tags that the user can input are the tags that I've specified in the toolbar (e.g., bold, italics, underline, bullets, etc).

Thanks in advance!

**Comment by ipeychev** [comment]
Hello,

Yes, it is, please look [here](docs.ckeditor.com/#!/guide/dev_acf). Just pass the required configuration when you create AlloyEditor's instance (the second argument is the config object) and it will be propagated down to CKEditor.

There are also specific configurations related to pasting from Word.

Hope that helps,

**Comment by sei-dmorda** [comment]
Hi ipeychev,

That was just what I was looking for, thanks so much. For anyone else that might have this question...here's how I implemented it.

```
<script` type="text/javascript">
    var myCoolEditor = AlloyEditor.editable('my-editor-controls', {
		toolbars: {
		    styles: {
		        selections: [
		        	{
						name: 'text',
						buttons: ['ul', 'ol', 'bold', 'italic', 'underline', 'link', 'removeFormat'],
						test: AlloyEditor.SelectionTest.text
		        	}, {
		        		name: 'link',
		        		buttons: ['linkEdit'],
		        		test: AlloyEditor.SelectionTest.link
		        	}
		      	]
		    }
		},
        allowedContent: 'p ul li ol b strong em u; a[!href]'
    });
</script>
```

**Comment by ipeychev** [comment]
:+1:
