### ISSUE TITLE
Example for adding dropdowns to the toolbar

### ISSUE THREAD

**Issue by harel** [liferay/alloy-editor#483]
I want to add a drop down to the add toolbar. The examples show how to add buttons only, but not drop downs. I will try to figure out and maybe submit a documentation update when I do but any help in the meanwhile will be appreciated.

**Comment by jbalsas** [comment]
Hey @harel,

We have many implementation examples in our code base that show how to add dropdowns. The way we've been approaching this, has been evolving over time, but the main principle remains the same. You can check, for example, the [`ButtonLinkTargetEdit`](https://github.com/jbalsas/alloy-editor/blob/1.0.1/src/ui/react/src/components/buttons/button-link-target-edit.jsx) component.

It does several things:

### Check `this.props.expanded` to determine if the dropdown is to be rendered

```jsx
if (this.props.expanded) {
    allowedTargetsList = this._getAllowedTargetsList();
}
```

### Have a button invoke `this.props.toggleDropdown`

This is passed via props by the parent component, provided by the [`WidgetDropdown` mixin](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/components/base/widget-dropdown.js)

```jsx
<button ... onClick={this.props.toggleDropdown} ... />
```

### Render the dropdown when `props.expanded` is `true`

```jsx
<AlloyEditor.ButtonDropdown>
    {children <li> here}
</AlloyEditor.ButtonDropdown>
```

Hopefully this should put you on the correct path to accomplish this. Other examples out there are:
- [ButtonTableCell](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/components/buttons/button-table-cell.jsx)
- [ButtonTableColumn](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/components/buttons/button-table-column.jsx)
- [ButtonTableHeading](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/components/buttons/button-table-heading.jsx)
- [ButtonTableRow](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/components/buttons/button-table-row.jsx)
- [ButtonStyles](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/components/buttons/button-styles.jsx)

We'll make sure to transfer this to the website as part of the next batch of updates as soon as possible.

Please, let us know if this was of any help to you, or if you still have some doubts.

**Comment by harel** [comment]
That's great - i'll go through it and try to implement my drop down. Glad its coming to the website!
Thanks!!!!!

**Comment by harel** [comment]
This all works great @jbalsas, thank you. 
I just have one question: How can I pass properties to the custom control I created? Its a drop down which is meant to provide a list of tags based on the user's configuration but I can only seem to add it to the toolbar using its 'key'. I tried hooking it up to the redux state but that didn't seem to work very well either.

**Comment by jbalsas** [comment]
Hey @harel, if I understand correctly, you want to pass configuration to your button. This explained in the **Configuring Buttons** section of the [Toolbar configuration](http://alloyeditor.com/guides/toolbar_configuration/) Guide.

To add buttons, you can either simply pass the key of the component, or an object like:

```javascript
{
    name: key
    cfg: {
        // Your custom config here
    }
}
````

Hope that helps!

**Comment by harel** [comment]
Perfect. Thanks very much! You guys are on the ball here! I really appreciate it.

**Comment by jbalsas** [comment]
We're happy to help @harel!

Just let us know if you ran into any problems with this... and of course, we'd be happy to see what are you cooking there if you can share it :wink:

**Comment by harel** [comment]
I'll be happy to share when its done. In the meanwhile, I've added a small modification for a scrollable button down which I can push as a PR if you guys are interested. Nothing fancy, but useful for long lists.

**Comment by ipeychev** [comment]
Thanks for the nice words! And yes, we would be really happy to see your contribution!

**Comment by harel** [comment]
@ipeychev : https://github.com/liferay/alloy-editor/pull/486
