### ISSUE TITLE
Firefox throws "e.data.$.clipboardData.items" error when you paste some text into editable content.

### ISSUE THREAD

**Issue by antoniopol06** [liferay/alloy-editor#485]
I attached a gif to reproduce that.
![firefoxerror](https://cloud.githubusercontent.com/assets/3017821/13747749/194f71dc-e9fa-11e5-8432-a689579abb31.gif)

**Comment by ipeychev** [comment]
Hey @antoniopol06,

Are you going to submit PR with these changes?

Thanks,

**Comment by antoniopol06** [comment]
Hi @ipeychev I sent PR to @jbalsas . This is the link https://github.com/jbalsas/alloy-editor/pull/11
