### ISSUE TITLE
Listen to basic events on editor

### ISSUE THREAD

**Issue by pierre-weceipt** [liferay/alloy-editor#489]
I'm just trying to add some class to the editor when it is active so that the user knows that he is editing but I can't find a way to easily plug events on the editor (I never used React and wanted to avoid getting into it just for that).
 So is there some basic events triggered by the editor like "focus" or "click", even some kind of "active" state would work for me?

Thanks for the answer and the great tool!

**Comment by ipeychev** [comment]
Hello,

Yes, there are. Under the hood we use CKEditor, so you can subscribe to all of its events. Here is how to do it:
```javascript
var alloyEditor = AlloyEditor.editable('test123');
var ckeditor = alloyEditor.get('nativeEditor');

ckeditor.on('focus', function(event) {
    console.log('Focus')
});
```

Thanks,

**Comment by pierre-weceipt** [comment]
It's working like a charm now, I already tried this but was missing 
```javascript
var ckeditor = editor.get('nativeEditor');
```
