### ISSUE TITLE
Getting an existing instance of editor to destroy it

### ISSUE THREAD

**Issue by pierre-weceipt** [liferay/alloy-editor#490]
I've got a similar need as in #362 and need to dinamically remove some editor instances. There is the destroy() method to clean things but I can't find a method to get the editor instance attached to a certain node. Did I miss something? 

Thanks

**Comment by ipeychev** [comment]
Hello,

Once the editor instance is created, we don't store the instances anywhere. There is no static method where you pass a DOM node and it returns the instance.
Those, who is creating the instances is supposed to keep them somewhere and destroy them accordingly by calling the `destroy`method.

Thanks,

**Comment by pierre-weceipt** [comment]
Okay, it would be a nice feature to have though!
