### ISSUE TITLE
Issue with clicking in a dropdown when there is overflow

### ISSUE THREAD

**Issue by ipeychev** [liferay/alloy-editor#491]
There is an issue with dropdown scrollbar. If the developer sets overflow property of listbox, only visible list item are clickable whereas when list is scrolled and a list item is clicked the dropdown scrolls to top and nothing is selected.

Issue created based on this question: http://alloyeditor.com/guides/how_to_use_ckeditor_plugins/#comment-2598383603
![bug](https://cloud.githubusercontent.com/assets/78014/14189811/a7270d42-f78f-11e5-9411-369365efe332.gif)

**Comment by jbalsas** [comment]
Hey Iliyan, I think this is the same as https://github.com/liferay/alloy-editor/issues/239 that for some reason got closed.

I'll take a look.
