### ISSUE TITLE
Can not use with meteor 1.3 + react + npm

### ISSUE THREAD

**Issue by zhaoyao91** [liferay/alloy-editor#494]
I tried to use alloy-editor in such environment, but failed. 
I've copy alloy-editor-ocean-min.css into /client dir, and in my test page, I wrote such code:
```
import React from 'react';
import Container from '/client/modules/core/components/container';
import {PageHeader} from 'react-bootstrap';

import AlloyEditor from 'alloyeditor'

const Page = (props) => {
    setTimeout(()=> {
        AlloyEditor.editable('editable');
    }, 1000);
    return <Container>
        <PageHeader>测试页</PageHeader>
        <div id="editable">
            <p>测试内容</p>
        </div>
    </Container>
};

export default Page

window.AlloyEditor = AlloyEditor
```
but only get errors from browser console...
![image](https://cloud.githubusercontent.com/assets/3808838/14345009/584e6fdc-fcdd-11e5-9cfa-e521fdf23f43.png)

**Comment by ipeychev** [comment]
Hello,

Is the path to AlloyEditor set correctly? Please read [here](https://github.com/ipeychev/alloyeditor-react-component#i-dont-want-to-copy-alloyeditor-to-the-dist-folder-like-you-did).

Also, this code:
```javascript
window.AlloyEditor = AlloyEditor
```
shouldn't be really needed.

The "Unexpected token <" is weird, but there is no syntax error in this file. Maybe the server returns it incorrect encoding (this is just shot in the dark)?

**Comment by zhaoyao91** [comment]
I feel setup such an editor is so complicated.
the `unexpeted token <' files are returned as html files (in fact, the main app file)

**Comment by ipeychev** [comment]
It is actually very simple to use, please see [here](http://alloyeditor.com/guides/). It requires to add one script on the page and that is everything. There is no need to add anything.
Importing from NPM and creating a module is adding an additional layer and it comes with its price.
