### ISSUE TITLE
UX: Table delete icon confusing

### ISSUE THREAD

**Issue by mattleff** [liferay/alloy-editor#496]
During some user testing it was noted that the table delete icon is confusing. Specifically users thought it would dismiss the table dialog instead of deleting the table.

What would your thought be of replacing the `x` with a trash can, something like this?

Before:

![image](https://cloud.githubusercontent.com/assets/120155/14363991/0c509006-fcc4-11e5-8d24-a3adf387ff40.png)

After:

![image](https://cloud.githubusercontent.com/assets/120155/14364003/16f71386-fcc4-11e5-89c9-ebfd3eb3a286.png)

**Comment by ipeychev** [comment]
+1 from me. Let's see what our UX guys will say too.

**Comment by jbalsas** [comment]
Hey @mattleff, @ipeychev, I'm also all for this. The only improvement over your suggestion I could think of, is if we could have a table icon with a small trash bin. That would give some context to the delete icon as well. 

However, since the toolbar is already contextual, maybe it might be too much 😅 

I'll mention this to our UX team to see what they think and what could we do about it.

**Comment by ipeychev** [comment]
:+1:

**Comment by jbalsas** [comment]
Hey @mattleff, @ipeychev, I brought this up with UX and they agreed that a simple trash icon would be more than enough.

@antoniopol06 will be adding it shortly 😉

**Comment by mattleff** [comment]
@jbalsas 👍 😀

**Comment by mattleff** [comment]
@jbalsas @ipeychev I tried the latest with the trash can icon and the atlas theme and it seems a little small to me:

![image](https://cloud.githubusercontent.com/assets/120155/14747813/92bd3a6c-0873-11e6-8b7f-a356cfa6b0e0.png)

If I add a background color and zoom in you can see it doesn't fill the vertical space of the icon:

![image](https://cloud.githubusercontent.com/assets/120155/14747996/9284e3fa-0874-11e6-8b4c-64973df7ad6d.png)

The ocean theme looks correct:

![image](https://cloud.githubusercontent.com/assets/120155/14750377/be1db0c0-0881-11e6-83c7-b2c287e925c2.png)

I'm still trying to figure out why atlas is too small...

**Comment by jbalsas** [comment]
Hey @mattleff, you're probably right... we have a different set of icons for the atlas theme, so we probably forgot to bring it that version as well 😞 

We'll take a look and add the missing icons on monday!
