### ISSUE TITLE
class="modal" -> contenteditable = false for chromium

### ISSUE THREAD

**Issue by Enteee** [liferay/alloy-editor#499]
the following project:
```html
<!DOCTYPE html>
<html>
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <link href="alloy-editor/assets/alloy-editor-ocean-min.css" rel="stylesheet">

    <script src="js/jquery-2.2.1.min.js"></script>

    <script src="alloy-editor/alloy-editor-all-min.js"></script>

    <script type="text/javascript">
        $(function(){
            AlloyEditor.editable('informationEditable');
        });
    </script>

</head>
<body>
    <!-- Information modal -->
    <div class="modal">
        <div id="informationEditable">
        </div>
    </div>
</body>
```
opened in firefox 45.0.1 and chromium 49.0.2623.87 (64-bit) results in:
* firefox: the contenteditable attribute of informationEditable is set to true
* chromium: the contenteditable attribute of informationEditable is set to false

I do think this is because of a conflict with the jquery modal class (somehow). Also the chromium way is probably not intenden behaviour.
thanks

**Comment by ipeychev** [comment]
Hello,

Bootstrap's `modal` class has `display: none;` so even if you have some text, it will be hidden.
If you are trying to edit some text in a dialog, create AlloyEditor instance _lazy_ - when you open the dialog. There is no point to create it initially - the user may never open this dialog.

Thanks,

**Comment by Enteee** [comment]
Thank you for your answer, I'll try switching to lazy loading as suggested. If I got you right here: the ```display: none```, which comes implicit with ```class="modal"```, makes alloy edtior initialize itself with the ```contenteditable``` attribute to ```true``` in firefox and to ```false``` in chromium.

so this:
```html
<!DOCTYPE html>
<html>
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <link href="alloy-editor/assets/alloy-editor-ocean-min.css" rel="stylesheet">

    <script src="js/jquery-2.2.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <script src="alloy-editor/alloy-editor-all-min.js"></script>

    <script type="text/javascript">
        $(function(){
            $('#example').on('shown.bs.modal', function() {
                var e = AlloyEditor.editable('informationEditable');
                e.get('nativeEditor').setData('Some text');
            });
            // delay modal show to 'simulate' user click
            setTimeout(function(){
                $('#example').modal('show');
            }, 1000);
        });
    </script>

</head>
<body>
    <div id="example" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Title</h4>
                </div>
                <div class="modal-body">
                    <div id="informationEditable"></div>
                </div>
            </div>
        </div>
    </div>
</body>

```
works in both browsers but as the editor needs some time to initialize itself i get the following behaviour on my machine:
1. modal opens
2. some time passes
3. editor pops up

which is ugly. Note: I'm aware that there might be better events to listen on but I do think the essence of the problem remains the same. So this is why I'd like to preload the editor before I show the modal:

```html
<!DOCTYPE html>
<html>
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <link href="alloy-editor/assets/alloy-editor-ocean-min.css" rel="stylesheet">

    <script src="js/jquery-2.2.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <script src="alloy-editor/alloy-editor-all-min.js"></script>

    <script type="text/javascript">
        $(function(){
            //$('#example').on('shown.bs.modal', function() {
                var e = AlloyEditor.editable('informationEditable');
                e.get('nativeEditor').setData('Some text');
            //});
            // delay modal show to 'simulate' user click
            setTimeout(function(){
                $('#example').modal('show');
            }, 1000);
        });
    </script>

</head>
<body>
    <div id="example" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Title</h4>
                </div>
                <div class="modal-body">
                    <div id="informationEditable"></div>
                </div>
            </div>
        </div>
    </div>
</body>
```

Which means I'll end up with:

firefox:
```html
<div contenteditable="true" id="informationEditable" class="cke_editable cke_editable_inline cke_contents_ltr ae-editable" tabindex="0" spellcheck="true" role="textbox" aria-label="Rich Text Editor, informationEditable" title="Rich Text Editor, informationEditable"><p>Some text</p></div>
```

chromium:
```html
<div id="informationEditable" contenteditable="false" class="cke_editable cke_editable_inline cke_contents_ltr ae-editable" tabindex="0" spellcheck="true" role="textbox" aria-label="Rich Text Editor, informationEditable" title="Rich Text Editor, informationEditable"><p>Some text</p></div>
```

note that in firefox: ```contenteditable="true" ``` and in chromium: ```contenteditable="false" ```. What should be the default behaviour and how can I force the contenteditable to ```true``` in both cases?

In general: Different behaviour in different browser not something which web software should avoid?

**Comment by jbalsas** [comment]
Hey @Enteee, 

Unless something recently changed, the expected behaviour is the one you're seeing in Firefox. This is not really an AlloyEditor limitation, but a CKEditor one. CKEditor will refuse to properly initialize when the node is not visible. Not sure why chromium behaves differently, but in any case, we'd need to verify the different behaviour against a released chrome version. I wouldn't expect them to be any different.

We are integrating AlloyEditor in some similar scenarios (collapsible panels, tabs...) and in all of them we defer the initialization until the editor is visible.

If you really want to preload the editor, maybe you could try doing it in a node with `opacity: 0` and then move it into the `modal-body` after it is ready. If that still doesn't work, maybe you could try using `clip`, something covering the node or doing it in an offscreen node. I don't remember how CKEditor is checking this off the top of my head, so these are just some possible workarounds that come to mind.

Hope it helps!

**Comment by ipeychev** [comment]
@Enteee If you really want to preload AlloyEditor, you may do what @jbalsas said, it makes sense.

However, in general there is no need to create an instance of AlloyEditor in advance in your case. This may just slow down the initial rendering of the page. Moreover, you shouldn't set the editable data via AlloyEditor (`e.get('nativeEditor').setData('Some text');`). If you are rendering the HTML on the server (and you should), create an element, populate the data on the server and set `contenteditable="true"`. This element might be hidden with `display:none`, this is OK. Once the user clicks, show the dialog and then instantiate AlloyEditor (create the instance after `$('#example').modal('show');`).

Note: technically, there is no need `contenteditable="true"` to be set in advance - AlloyEdiror will set it to true automatically when an instance is created. Setting it manually however is good from UX point of view.

Does that make sense?

Thanks,
