### ISSUE TITLE
ES6 support in Alloy editor

### ISSUE THREAD

**Issue by qasid** [liferay/alloy-editor#503]
I have components in ES6 format and want to import them in alloy but couldn't find any compatible way for doing it.

**Comment by ipeychev** [comment]
Hello,

What exactly do you mean with "importing them in alloy"? Are you going to contribute some code, or you wrote some plugins and you try to add them in your local copy of AlloyEditor?

Thanks,,

**Comment by qasid** [comment]
Hello,
Thank You!  for your reply.
Actually I  want to do something like 

```
//composite component
import mycomponent from " ./myComponent" ;

render : function(){
return (<div>
               <myComponent/> 
       </div>);
}
```
 
 when creating a button. 

Thanks

**Comment by ipeychev** [comment]
Hello,

You just have to transpile your code with Babel and after that you can add this button to AlloyEditor as any other button. All of the code of AlloyEditor is being transpilled by Babel, including all of the buttons.

Hope that helps!

Thanks,
