### ISSUE TITLE
Allow open target of hyperlink in editor - something lik Ctrl-Click in Word

### ISSUE THREAD

**Issue by JiriZidek** [liferay/alloy-editor#509]
Author of article has now no way to verify his link works.
http://alloyeditor.com/features/link/#comment-2645518602

**Comment by jbalsas** [comment]
Hey @JiriZidek 

Thanks for bringing this up. We'll discuss it with our UX team to see how can we best bring this feature to the editor.

**Comment by MrJingles2016** [comment]
Hey @jbalsas 

This could be a great edition to the editor. What about holding CTRL down to change the editor mode to "readonly" (http://alloyeditor.com/guides/editor_configuration/readonly_configuration/).

**Comment by julien** [comment]
Hi everyone,

I'm currently working on this issue, and just wanted to let you know that Firefox "behaves" this way by default: when holding CTRL on Windows/Linux or  Cmd on macOS, links open in new tabs, even when the editor is not in **read only** mode. 

Will submit a PR shortly.

Thanks
