### ISSUE TITLE
Multi-image drag-n-drop trigger unique event

### ISSUE THREAD

**Issue by mattleff** [liferay/alloy-editor#518]
Currently dragging-n-dropping and pasting an image trigger the same event ([here](https://github.com/liferay/alloy-editor/blob/master/src/plugins/addimages.js#L180) and [here](https://github.com/liferay/alloy-editor/blob/master/src/plugins/pasteimages.js#L71)). While this is good for most cases I'm wanting to have a separate event for a multi-image drag-n-drop. This allows me to turn several images into a single element in the editor (i.e., for a gallery).

I've added this to our repo with [this](https://github.com/SimpleUpdates/alloy-editor/blob/multi-image-event/src/plugins/addimages.js#L65-L88) but I was wondering if this is something that you would want or be willing to have. Or is there a better way to accomplish what I'm doing with the current code?

**Comment by ipeychev** [comment]
That is an interesting user case. So, in case of multiple files, you don't leave the editor to add them to the content, but you handle them by yourself, don't you?
Here is what I think we can do to help you:

Before to process the images, we collect them in an array which may have one or more elements and we fire another generic event, something like `beforeImageAdd`. It will have all the images as payload. Then, if the returned result is `false`, i.e. someone prevented the event, we will not process the images and the editor will not add them to the content.
In this case we will have backward compatibility and you will subscribe to this new event, will check the size, will add them as you do now and return false in the listener.

How does it sound for you?

Thanks,

**Comment by mattleff** [comment]
@ipeychev I think the `beforeImageAdd` sounds perfect.
