### ISSUE TITLE
Can I use Alloy Editor for SaaS Commercial Project?

### ISSUE THREAD

**Issue by bnqtoan** [liferay/alloy-editor#520]
I'm so sorry because put an issue here. I think it's wrong place but there are nowhere to ask.

I want to build a website creator for many clients, and use Alloy Editor as main editor,  I have some questions:

- Do I need to buy CKEditor premium license?
- Can I use Alloy Editor for SaaS Commercial Project?

Thanks for your help!

**Comment by jbalsas** [comment]
Hey @bnqtoan, I'm not very well versed in licensing models, so all I know is:

- For AlloyEditor conditions, you can and should refer to our [License](https://github.com/liferay/alloy-editor/blob/master/LICENSE.md)
- For CKEditor conditions, you should refer to [theirs](https://github.com/liferay/alloy-editor/blob/master/lib/ckeditor/LICENSE.md)

**Comment by ipeychev** [comment]
Disclaimer: IANAL

Both AlloyEditor and CKEditor's engine licenses allow it.
