### ISSUE TITLE
Show currently selected item in dropdown list.

### ISSUE THREAD

**Issue by qasid** [liferay/alloy-editor#521]
When a style is applied, it is not highlighted in the list when drop down list is opened again.
Is there any configuration settings required to handle this behavior?

**Comment by jbalsas** [comment]
This is currently not supported. From what I know, we'll have to go over our dropdowns one by one and figure out how the selected item should appear in each of them.

@qasid, is there a particular one that's bothering you?

We'll try to take a look at this over the next week.

Thanks for reporting it!

**Comment by qasid** [comment]
@jbalsas  Yes!  in Font drop down List
also the values are not updated automatically on first render. i.e. on selection I want to auto detect current font styles (e.g. size and family)

-

**Comment by mattleff** [comment]
This is also affecting us. One intermediate step would be to add an `.ae-active` variant to the `.ae-toolbar-element` styles so that we could manage the visual selection on menus ourselves. I'm happy to send a pull for that if you guys would like.

**Comment by jbalsas** [comment]
Adding this to milestone `1.3.0`
