### ISSUE TITLE
Convert email addresses into mailto: links

### ISSUE THREAD

**Issue by mattleff** [liferay/alloy-editor#522]
In the link dialog when you enter `me@example.com` it would make more sense to link it as `mailto:me@example.com` instead of `http://me@example.com`. The link dialog should be smart enough to convert `medium.com/@wob/the-sad-state-of-web-development-1603a861d29f` to `http://medium.com/@wob/the-sad-state-of-web-development-1603a861d29f` though.

Pull: #523.

**Comment by ipeychev** [comment]
Hey @mattleff,

Thanks for the contribution. There are some comments on the pull request, would you like to take a look on them?

Thanks,
