### ISSUE TITLE
Edit embedded link is broken - popup displays above wrong element

### ISSUE THREAD

**Issue by btknorr** [liferay/alloy-editor#526]
1) Goto http://alloyeditor.com/demo/ and scroll down some, then add an embedded link.  After you add it, the edit popup immediately shows in the correct spot.  

2) Click somewhere to dismiss the edit popup.

3) Now click back on the embedded element to edit it.  The edit popup displays far up the screen, and you have to scroll all the way up to see it hovering above the wrong element.

**Comment by ipeychev** [comment]
Thanks for the report!

I think the element is selected properly, but the toolbar is not positioned properly - scrollTop is not taken in consideration. Should be easy to fix, if it is this one.

Thanks,

**Comment by btknorr** [comment]
Yep you are right...this only happens when you have to scroll down to the content to be edited.

**Comment by ipeychev** [comment]
Fixed in [v1.2.2](https://github.com/liferay/alloy-editor/releases/tag/v1.2.2)
