### ISSUE TITLE
Testing embed buttons

### ISSUE THREAD

**Issue by antoniopol06** [liferay/alloy-editor#528]
There are not tests about embed, embed edit and embed remove buttons.

**Comment by ipeychev** [comment]
Hey @antoniopol06,

Are you going to send a PR with these changes?

Thanks,

**Comment by jbalsas** [comment]
Hey Iliyan, @antoniopol06 sent me https://github.com/jbalsas/alloy-editor/pull/16 for it.

I'm doing an EVP this week, so I won't have time to review it before sometime next week. Feel free to grab it before that if you wish! :relaxed:

**Comment by ipeychev** [comment]
Hey Chema,

It is OK, take your time.
GitHub does not show me that there is a PR to you - only that Antonio committed some code to his repo, which fixes some issue.

Thanks,

**Comment by antoniopol06** [comment]
Hi @ipeychev I sent you just now the PR that I sent to @jbalsas

**Comment by ipeychev** [comment]
Hey Antonio,

I am traveling tomorrow and I will return on Sunday, so it is better if Chema reviews it first. Then we can merge it.

Thanks,
