### ISSUE TITLE
In Alloyeditor with separate ckeditor, buttons are not executing commands to native editor.

### ISSUE THREAD

**Issue by usiyalla** [liferay/alloy-editor#531]
I am using alloyeditor with my own ckeditor. Everything loads fine but button like buttonbold are not working. When ButtonCommand.execCommand call native editor execCommand it dont find commandName in its commad list.
What i am missing do i need to register ckeditor with alloy.

**Comment by usiyalla** [comment]
I had to included missing basicstyles plugin in alloy editor extra plugins.

**Comment by ipeychev** [comment]
👍

**Comment by ipeychev** [comment]
Great, congratulations you did it by yourself. I was going to start checking for the reasons this evening.

**Comment by jbalsas** [comment]
Nice @usiyalla, glad you could work this out!

@ipeychev, seeing this, some action points come to mind:
- Buttons depending on CKEditor plugins could at least document their dependencies
- Based on the documented dependencies, we could calculate the set of required `extraPlugins` for all the buttons in the editor config to work properly.

How does this sound?

**Comment by ipeychev** [comment]
Hey Chema,

About documenting the dependencies, I would say if we don't have it, this would be a bug. Ours or CKEditor's dependencies, it doesn't matter, they should be documented.

About calculating the required extra plugins automatically, this is a good idea. We could raise a warning if there are missing plugins, or even to leave the value as "auto" by default and fill it with the needed plugins of creating the instance.
I don't have the code in front of me, but AFAIR we were documenting inside a comment block, didn't we? If so, we have to think how to get this info when we create the instance.

**Comment by jbalsas** [comment]
Yeah, that's what I was thinking... not having this documented is definitely something we need to address.

For the plugin requirement calculation, I guess that would depend on how we code the dependency. For example, we could use [`React statics`](https://facebook.github.io/react/docs/component-specs.html#statics) and do something like:

```jsx
var ButtonBold = React.createClass({
    [...]

    statics: {
        // possible statics: 'requires', 'dependencies', 'pluginDependencies'... 
        requires: 'basicstyles'
    },

    [...]
});

AlloyEditor.Buttons[ButtonBold.key] = AlloyEditor.ButtonBold = ButtonBold;
```

With this, I think we might even write a `yuidoc` preprocessor so we can extract the info for the documentation from there and avoid having to duplicate it in the comment block.

We can take a look into this if it sounds good to you.

**Comment by ipeychev** [comment]
Could be in statics, I don't see any better place for that.

I think it might be possible to get the information even without touching YUI doc. Maybe we will be able to reference it using some of "Cross-referencing Modules and Classes"?

**Comment by wincent** [comment]
By way of "spring cleaning", I'm closing issues tagged with "question" that haven't had any activity in > 12 months. There have been quite a few releases since then and much has changed, and these "stale" issues are extremely unlikely to be acted on. Please feel free to comment and we can re-open on a case-by-case basis.
