### ISSUE TITLE
can't remove the marker

### ISSUE THREAD

**Issue by myblackboxgithub** [liferay/alloy-editor#532]
I would like to make AlloyEditor to switchable between enable and disable.
When a imaged is selected and destroy editor, it is fine, but when it back to enable, it remains ‘ckimgrsz’ class, margin and anchor are still there, and it makes error messages, 'lock' of null or 'unlock' of null.

how can I remove it? thanks

`var myEditor;
//to enable
if (!CKEDITOR.instances.introduction)
	myEditor = AlloyEditor.editable('introduction');

//to disable
if (CKEDITOR.instances.introduction)
	myEditor.destroy();`

![bugs](https://cloud.githubusercontent.com/assets/15113714/15672912/59abfcf0-272b-11e6-8b5f-18ad934b90e7.gif)

**Comment by jbalsas** [comment]
Hey @myblackboxgithub, we'll take a look into this... I agree this probably shouldn't happen, and it might be as easy as properly clean up within the `imageresize` plugin.

In the meantime, we implemented a less expensive way of disabling the editor using [`.setReadOnly`](https://github.com/liferay/alloy-editor/issues/436), so you might give it a try to see if that somehow changes how this behaves.

**Comment by myblackboxgithub** [comment]
thanks @jbalsas,
I tried it with .setReadOnly, it seems work fine, but the selected mark still remains and it can be resizable image. 

then I added some code what I found Internet to make it unselect. it seems works fine. 
thanks for help.

`function enableEditing() {
    if (!CKEDITOR.instances.introduction) {
        myEditor = AlloyEditor.editable('introduction');
    }
    else {
        myEditor.get('nativeEditor').setReadOnly(false);
    }
}

function disableEditing() {
    if (CKEDITOR.instances.introduction) {

//to remove selection
        var oEditor = CKEDITOR.instances.introduction;
        var doc = oEditor.document,
            range = new CKEDITOR.dom.range(doc),
            body = doc.getBody();
        range.setStart(body, 0);
        range.setEnd(body, 0);
        oEditor.getSelection().selectRanges([range]);
        oEditor.getSelection().removeAllRanges();        

        myEditor.get('nativeEditor').setReadOnly(true);
    }
}`

**Comment by jbalsas** [comment]
Hey @myblackboxgithub, glad it's working for you now!

I still see this as a potential bug, so we'll work to fix all cases, both destroying and setting it to read only should probably work without you having to add additional code. We'll use this issue to track the fix so you're aware when it lands in a new version so you can remove this additional code.

Thanks for reporting this! ☺️

**Comment by myblackboxgithub** [comment]
I have tried it several times, but I realize that the setReadOnly isn't suitable to me. 
I need to destroy editor and create new one if it need without any trace of previous one.
I'm wondering how I can call to dismiss editor instance, like as any of a mouse click, out of the alloyeditor's area?

**Comment by ipeychev** [comment]
You have to invoke `destroy`, that's the right way for killing the editor. If something is left after that, it is not intended and should be fixed.
And yes, you can do it on any event out of the editable area.

**Comment by myblackboxgithub** [comment]
Thanks, it works as it expected. 
but it has a problem on ae_richcombobridge for Font Size and Family Plugin http://alloyeditor.com/guides/how_to_use_ckeditor_plugins/
the Font, FontSize won't work once it has destroyed and created.

**Comment by jbalsas** [comment]
Hey @myblackboxgithub, could you open a separate issue for that one? We'll investigate and fix as soon as possible!

**Comment by ipeychev** [comment]
Fixed in [v1.2.3](https://github.com/liferay/alloy-editor/releases/tag/v1.5.3).
