### ISSUE TITLE
beforeImageAdd event is needed, when a single image is uploaded by the image button

### ISSUE THREAD

**Issue by AXJ15** [liferay/alloy-editor#534]
In the closed issue #518  you suggested adding 'beforeImageAdd' event to pre handle the multi-image drag-n-drop. Actually, this event is way helpful if we can subscribe to it with the image button as well at [buttom-image.jsx](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/components/buttons/button-image.jsx#L87), for some pre-check of the file e.g. its size.

**Comment by ipeychev** [comment]
Correct, fixed.

Thanks for the heads up!

**Comment by AXJ15** [comment]
Great!, I'm starting to like this, thanks a lot )

**Comment by ipeychev** [comment]
Fixed in [v1.2.3](https://github.com/liferay/alloy-editor/releases/tag/v1.5.3).
