### ISSUE TITLE
Refused to execute script because its MIME type ('text/html') is not executable

### ISSUE THREAD

**Issue by barriehadfield** [liferay/alloy-editor#540]
Sorry, I suspect this is a question more than an issue, but I am having trouble getting this working.

I have tried installing via NPM, via requiring in application.js and via including the JS -all fine in my html hape and I get the same problem in all situations. I am using Rails.

The issue is as below - Chrome is refusing the execute script..

In my JS console, I can see the AlloyEditor loaded and can interact with it:

window.AlloyEditor.getBasePath()
"http://localhost:3000/squad/66/"

Any help really appreciated!

Refused to execute script from 'http://localhost:3000/squad/66/lang/alloy-editor/en.js?t=G4CD' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
dmsi:1 Refused to execute script from 'http://localhost:3000/squad/66/config.js?t=G4CD' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
alloy-editor-no-react.js?ec37:96 GET http://localhost:3000/squad/66/skins/moono/editor.css?t=G4CD CKEDITOR.tools.extend.append @ alloy-editor-no-react.js?ec37:96CKEDITOR.tools.extend.appendStyleSheet @ alloy-editor-no-react.js?ec37:86b @ alloy-editor-no-react.js?ec37:496CKEDITOR.skin.loadPart @ alloy-editor-no-react.js?ec37:498q @ alloy-editor-no-react.js?ec37:257(anonymous function) @ alloy-editor-no-react.js?ec37:257q @ alloy-editor-no-react.js?ec37:22CKEDITOR.event.CKEDITOR.event.fire @ alloy-editor-no-react.js?ec37:24CKEDITOR.editor.CKEDITOR.editor.fire @ alloy-editor-no-react.js?ec37:25CKEDITOR.event.CKEDITOR.event.fireOnce @ alloy-editor-no-react.js?ec37:24CKEDITOR.editor.CKEDITOR.editor.fireOnce @ alloy-editor-no-react.js?ec37:25l @ alloy-editor-no-react.js?ec37:255(anonymous function) @ alloy-editor-no-react.js?ec37:255c.push.callback @ alloy-editor-no-react.js?ec37:243f @ alloy-editor-no-react.js?ec37:241y @ alloy-editor-no-react.js?ec37:241A @ alloy-editor-no-react.js?ec37:241CKEDITOR.env.ie.CKEDITOR.env.version.f.$.onerror @ alloy-editor-no-react.js?ec37:242
dmsi:1 Refused to execute script from 'http://localhost:3000/squad/66/lang/en.js?t=G4CD' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
alloy-editor-no-react.js?ec37:240 Uncaught TypeError: Cannot set property 'dir' of undefined

**Comment by ipeychev** [comment]
Hello,

As we mentioned several times before, we don't know why is this happening. We don't use Rails and we cannot help. This is something related to the server, maybe some configuration, or I don't know what, but until server returns MIME type ('text/html'), it will never work. The editor is out of the scope here.

Thanks,

**Comment by hew** [comment]
@barriehadfield 

https://github.com/liferay/alloy-editor/issues/341#issuecomment-261106545

**Comment by gianlucadario87** [comment]
has somebody  resolved this problem???
