### ISSUE TITLE
How to prevent button component from unmounting when modal popup is fired and interacted with

### ISSUE THREAD

**Issue by jbhamilton** [liferay/alloy-editor#545]
Can't seem to figure this one out.

I have created a custom link editing button which works fine in all ways but one. I allow users to select a 'entry' (which is a custom page inside a CMS) so that I can use the URL of the entry as the `href` property for the link. This selection is done via a modal pop-up. The problem is when the contents of the modal is interacted with the link editing button component is dismounted and then the callback function from the modal window no longer has a mounted component to work with.

How can I prevent the button component from losing focus and being unmounted while the user interacts with the modal window contents?

Big thanks for everything you guys have created and do.

Code below, problem found within function `onLinkEntry`:

```
React.createClass({

    element : null,

    mixins : [AlloyEditor.ButtonStyle, AlloyEditor.ButtonStateClasses, AlloyEditor.ButtonActionStyle],

    propTypes: {
        editor: React.PropTypes.object.isRequired
    },

    getDefaultProps: function(){
        return {
            style : {
                element : 'richtext_link_edit'
            }
        };
    },//getDefaultProps

    statics: {
        key: 'richtext_link_edit'
    },//statics

    getInitialState: function(){

        var state   = { href : '' },
            a       = this.getLinkElement();

        if(a && a.getName() === 'a'){

            this.element = a;

            state.href = a.getAttribute('href');

            var target = a.getAttribute('target');
            if(target){
                state.target = target;
            }//if

            var rel = a.getAttribute('rel');
            if(rel){
                state.rel = rel;
            }//if

        }//if

        console.log(state);

        return state;

    },//getInitialState

    componentDidMount: function(){
        var that = this;
        $(this.refs['href'].getDOMNode()).on('keypress',function(event){
            if(event.keyCode === 13){
                that.onUpdateLink();
            }//if
        });
    },//componentDidMount

    setAttribute: function(attr,value){
        if(this.element){
            this.element.setAttribute(attr,value);
        }//if
        this.setState(function(state){
            state[attr] = value;
        });
    },//setAttribute

    removeAttribute: function(attr){

        if(this.element){
            this.element.removeAttribute(attr);
        }//if

        this.replaceState( _.omit(this.state,attr) );

    },//removeAttribute

    getLinkElement: function(){
        return this.props.editor.get('nativeEditor').getSelection().getStartElement();
    },//getLinkElement

    onTargetBlank : function(){
        if(!this.state.target){
            this.setAttribute('target','_blank');
        } else {
            this.removeAttribute('target');
        }//el
    },//onSelectLink

    onRelNofollow: function(){
        if(!this.state.rel){
            this.setAttribute('rel','nofollow');
        } else {
            this.removeAttribute('rel');
        }//el
    },//onRelNofollow

    onLinkEntry: function(){

        var that = this;

        Enact.selectEntryModal.openModal({},function(event,value){
            that.setState({ href : value.url, title : value.title });
        });

    },//onLinkEntry

    onRemoveLink: function(){

        var editor      = this.props.editor.get('nativeEditor'),
            linkUtils   = new CKEDITOR.Link(editor),
            selection   = editor.getSelection(),
            bookmarks   = selection.createBookmarks();

        linkUtils.remove(this.element);

        selection.selectBookmarks(bookmarks);

        // We need to cancelExclusive with the bound parameters in case the button is used
        // inside another in exclusive mode (such is the case of the link button)
        this.props.cancelExclusive();

        editor.fire('actionPerformed', this);

    },//onRemoveLink

    onUpdateLink: function(){

        var editor      = this.props.editor.get('nativeEditor'),
            linkUtils   = new CKEDITOR.Link(editor);

        if (this.state.href) {

            if (this.element) {

                linkUtils.update(this.state.href, this.element);

            } else {

                linkUtils.create(this.state.href);

                var a       = linkUtils.getFromSelection(),
                    attrs   = _.omit(this.state,'href');

                for(var attr in attrs){
                    a.setAttribute(attr,attrs[attr]);
                }//for

            }//el

            editor.fire('actionPerformed', this);

        }//if

        // We need to cancelExclusive with the bound parameters in case the button is used
        // inside another in exclusive mode (such is the case of the link button)
        this.props.cancelExclusive();

    },//onUpdateLink

    onClearLink: function(){
        this.setState({ href : '' });
    },//onClearLink

    onChangeHref : function(event){
        this.setState({ href : event.target.value });
    },//onChangeHref

    render: function(){

        var rel_icon        = 'fi-thumb-down',
            rel_title       = 'Set a `nofollow` on the link, preventing search engines from following the link',
            target_icon     = 'fi-account-login',
            target_title    = 'Make link open in new tab',
            show_remove     = (!this.element) ? ' hide' : '';

        if(this.state.rel){
            rel_icon    = 'fi-thumb-up';
            rel_title   = 'Remove the `nofollow` from the link';
        }//if

        if(this.state.target){
            target_icon     = 'fi-account-logout';
            target_title    = 'Make link open in same tab';
        }//if

        return (
                <div>
                    <button className='ae-button' title='Create link from existing entry' onClick={this.onLinkEntry}>
                        <span className='fi-project icon'></span>
                    </button>
                    <button className='ae-button' title={rel_title} onClick={this.onRelNofollow}>
                        <span className={rel_icon + ' icon'}></span>
                    </button>
                    <button className='ae-button' title={target_title} onClick={this.onTargetBlank}>
                        <span className={target_icon + ' icon'}></span>
                    </button>
                    <button className={'ae-button' + show_remove} title='Remove link' onClick={this.onRemoveLink}>
                        <span className='fi-link-broken icon'></span>
                    </button>
                    <div className='ae-container-input'>
                        <input ref='href' className='ae-input' type='text' onChange={this.onChangeHref} defaultValue={this.state.href} placeholder='Type or paste link...'/>
                        <button className='ae-button' title='Clear link' onClick={this.onClearLink}>
                            <span className='fi-circle-x icon'></span>
                        </button>
                    </div>
                    <button className='ae-button' title='Update link' onClick={this.onUpdateLink}>
                        <span className='fi-check icon'></span>
                    </button>
                </div>
            );

    }//render

});
```

**Comment by ipeychev** [comment]
Hello,

If I understand properly the problem, the user clicks somewhere outside the toolbar. By design, in this case the toolbar will hide and unmount - otherwise people won't be able to get rid of it.

The case described here is specific, because the action is still part of editing the link, but outside editor's  UI and this is not a case we support.
The ideal situation would be if this wasn't a modal dialog, but a something, rendered in the context of the Toolbar, then everything would be OK. Since it is outside, I don't think we have an OOTB solution. We shall think how (if possible) to handle this situation.

Thanks,

**Comment by jbhamilton** [comment]
You understood the problem exactly. I understand there is no OOTB solution, but would it be possible to hijack or prevent the events from the [WidgetFocusManager](http://alloyeditor.com/api/classes/WidgetFocusManager.html) (I believe this is what is controlling when to lose focus and hide the toolbar) from thinking the toolbar has lost focus? If that isn't possible the only other solution I could conceive of is caching the prior selection of the text to be linked or the link to be edited and once the modal is done with its work and fires the callback, the callback would force the selection of the text or link again, bringing it back to its prior state. Only problem is I'm not sure how to implement that. I will fiddle with it and let you know if I come up with something.

Thanks again.

**Comment by jbalsas** [comment]
Hey @jbhamilton, there is no easy way to hack in there that I can think of, but we can take a look.

In Liferay we've done something similar (although we never considered keeping the toolbar open) that might help. For example, we have a button that shows a dialog to select media files (images, audio, video...) in the system. What we did is:

- Create a [CKEditor command](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/plugins/itemselector/plugin.js#L53-L-75) to encapsulate all the logic of showing the dialog and putting the result back into the editor
- Create a [`ButtonImage`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-editor/frontend-editor-alloyeditor-web/src/main/resources/META-INF/resources/_diffs/buttons/button_image_selector.js#L21) that invokes the given command.

This will, at the very least solve the coupling issue you currently have, and I think you might find it a better solution for the future, as you may be able to reuse the feature from somewhere else.

Once you have the user-selected content in the editor, you may use either CKEditor's API to trigger a selection change that would force the toolbars to render again based on the selection or fire a custom  `editorInteraction` event to achieve the same...

Hope some of this can help you...

**Comment by ipeychev** [comment]
@jbhamilton Despite the user opened the dialog, this does not necessarily mean that the selection got lost. Even that the toolbar disappeared, you should be still able to apply the href to the selection. CKEDITOR.Link should be able to do it - and you can consider to apply it once the user selects the href.

If in any case, even if the selection disappeared for some reason, you can easily restore it:
```javascript
// Before showing the dialog
var nativeEditor = editor.get('nativeEditor'); // editor is the result of AlloyEditor.editable('editable');
var sel = nativeEditor.getSelection();
var ranges = sel.getRanges();

// Here you display the dialog, user selects the href

sel = nativeEditor.getSelection();
sel.selectRanges(ranges);

// Now you can invoke CKEDITOR.Link in order to apply the href
```

Hope that helps,
