### ISSUE TITLE
FontSize dropdown value doesn't update when increment font size using custom button

### ISSUE THREAD

**Issue by qasid** [liferay/alloy-editor#548]
**Steps**

1. Create new button "button-ifontsize" following steps defined [here](http://alloyeditor.com/guides/create/create_buttons/). and on click call "handleClick" function.
```
handleClick: function() {

      let editor = this.props.editor.get("nativeEditor");
      let parentNode= document.getSelection().extentNode.parentNode;
      let fontSizePX= window.getComputedStyle(parentNode, null).getPropertyValue('font-size');
      let nfontSize= parseInt(fontSizePX);

      nfontSize = nfontSize + 1;

      value = nfontSize +'px';
      var vars= {};
      vars["size"]= value;
      CKEDITOR.config.fontSize_style= {
      	element: 'span',
      	styles: { 'font-size': '#(size)' },
      	overrides: [ {
      		element: 'font', attributes: { 'size': null }
      	} ]
      };
      let  styles={};
      styles= new CKEDITOR.style( CKEDITOR.config.fontSize_style,   vars );
			editor.applyStyle( styles );
      editor.fire("actionPerformed",this);
    },

getDefaultProps: function() {

        return {

            style: {
                styles: {
                  'font-size': '#(size)' },
                }


        };
    },

statics: {
        key: 'ifontsize'
    },

```
2. Add 'FontSize', 'ifontsize' as new text selection buttons.(FontSize in font plugin)
3. Create a div placeholder `<div class="ae-placeholder" contenteditable="true" data-placeholder="Write here the description" id="description"></div>` in html file.
4. Enter sample text.  
5. Select text. Toolbar is rendered.
6. Select size from FontSize drop down. Size is applied
7. Increment font size using "ifontsize" button.

**Expected result**
 Size is applied and FontSize drop down value also changes. 

**Actual result**
  Size is applied but FontSize drop down value doesn't change.

This only happens when toolbar is rendered first time. Any selection after that changes the FontSize dropdown value with similar steps.

**Comment by jbalsas** [comment]
Will take a look

**Comment by qasid** [comment]
Hello @jbalsas, @ipeychev ,  any update on this?

**Comment by jbalsas** [comment]
Hey @qasid, I'm really sorry, I got diverted to different matters... @antoniopol06 will take a look asap!
