### ISSUE TITLE
Toolbar renders away from div having CSS property overflow set to auto.

### ISSUE THREAD

**Issue by qasid** [liferay/alloy-editor#549]
Toolbar renders at bottom and away from selection when all text is selected using keyboard command Ctrl+A or select manually using mouse
![toolbar_renders_away_from_selection](https://cloud.githubusercontent.com/assets/18445645/16077066/043b8880-3310-11e6-89b7-13690e224c41.png)
**Steps**
1 Create a div with over flow property set to auto.
```
<div id="container" >
          <div contenteditable="true"  id="description" style="width:100px; height:100px; overflow:auto;">
            <p>Armstrong spent about <s>three and a half</s> two and a half hours outside the spacecraft, Aldrin slightly less; and together they collected 47.5 pounds (21.5&nbsp;kg) of lunar material for return to Earth. A third member of the mission, <a href="http://en.wikipedia.org/wiki/Michael_Collins_(astronaut)">Michael Collins</a>, piloted the <a href="http://en.wikipedia.org/wiki/Apollo_Command/Service_Module">command</a> spacecraft alone in lunar orbit until Armstrong and Aldrin returned to it for the trip back to Earth.</p>
                </div>

        </div>
  <script type="text/javascript">
var instance = AlloyEditor.editable('description');
</script>
```
2. Select all text (using mouse or Ctrl+A).

**Expected result**
Toolbar renders near selected text.

**Actual result**
Toolbar renders away from selected text.

**Comment by qasid** [comment]
Hello @ipeychev,
Any update on this issue?

**Comment by ipeychev** [comment]
Umm, we put this with very low priority. It is an issue, true, but I couldn't imagine how could it happen in the real life, so we put it into the backlog.

However, let's see if this could be reprioritized:
1. What is the use case here?
2. What is the point of selecting the whole text and applying some style on it? Moreover, why is it useful to have such a small editable area?

Thanks,

**Comment by qasid** [comment]
Potential use case here is re-sizable text area. User can adjust the size of editable text area on the fly.

In this particular case there can be multiple scenarios where user selects whole text.
e.g: 
- User wants to change/apply font size &/or family of selected content
- User wants to re-align selected text
- User wants to change/apply styles formatting 

Currently in my opinion, by default toolbar renders where the text selection highlight ends.  Therefore in case of overflow since some portion of the selected text is visible to the user, toolbar appears as if it has rendered away from the text area.

**Comment by qasid** [comment]
@ipeychev  Thank You! I just confirmed it.
