### ISSUE TITLE
Info ReadMe Suggestion/Request

### ISSUE THREAD

**Issue by twmbx** [liferay/alloy-editor#550]
I'm very intrigued by the editor & very interested in using it. It would be great to have a little section at the end of the read me that details any projects that actually have implemented the editor in the wild.

Blogging software or CMS software.

**Comment by ipeychev** [comment]
Hello,

That is actually very good idea, but I'm not sure how we are going to collect this information? I'm aware of some companies apart from Liferay, but they are definitely a small part of the whole customer base. We may also expect people to share this information, but I'm not sure how fast this will be?

Thanks,

**Comment by jbalsas** [comment]
I agree this is a nice thing to have... of course Liferay is using it as the default editor in several bundled apps.

We could have something in the `README.md` asking people to let us know if they're using it, and some page like http://ckeditor.com/about/who-is-using-ckeditor or http://expo.getbootstrap.com in the site so we could add whoever's using it there.

Additionally, we could do a first request via twitter to see who's out there ;)

**Comment by wincent** [comment]
Going to close this one due to inactivity, but pull requests to [the website branch](https://github.com/liferay/alloy-editor/tree/website) are always welcome.
