### ISSUE TITLE
cant load alloy editor

### ISSUE THREAD

**Issue by pramodrhegde** [liferay/alloy-editor#551]
alloy-editor-all-min.js:25 Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "widget" was not found at "http://d1q0tj5904dmk1.cloudfront.net/alloy-editor/plugins/widget/plugin.js?t=FACH".

this weird issue i am getting when i load alloy editor in my React component. any idea how to solve this?
i am using latest version of 1.2.2

**Comment by ipeychev** [comment]
Hello,

This probably means you have to add `widget` plugin too. It is required by some of your design dependencies.

Thanks,

**Comment by pramodrhegde** [comment]
Thank you
