### ISSUE TITLE
Alloy Editor Unmount issue in react

### ISSUE THREAD

**Issue by pramodrhegde** [liferay/alloy-editor#552]
Hi there I am using Alloy editor in a react project and my life cycle methods look something like this
```
componentDidMount:function(){

    var self = this;

    self._editor = AlloyEditor.editable(self.props.container, {
      toolbars:toolbars
    });

    self._editor.get('nativeEditor').on('change',function(event){
      self.props.onRichTextChange(self.props.container,self._editor.get('nativeEditor').getData());
    });
  },
  componentWillUnmount:function(){
    if(this._editor){
      this._editor.get('nativeEditor').setReadOnly(true);
      this._editor.destroy();
    }
  }
```

but sometime when i am not editing and saving alloy editor component its throwing this below error.
i don know what is actually causing this issue.

> alloy-editor-no-react.js?ec37:637 Uncaught TypeError: Cannot read property 'getRanges' of null

any idea on this?

**Comment by ipeychev** [comment]
Hello,

No way to guess just like this. The best would be to provide some reproducible code.
Destroy in general works fine. Check the attached test case. The editor is not being destroyed inside an unmount, but when you click on the destroy button, but it shouldn't make much difference. Do you have any plugins added? If you can attach a zip file with reproducible code, it will be the best option.

Thanks,

[test_case.zip](https://github.com/liferay/alloy-editor/files/330669/test_case.zip)

**Comment by ipeychev** [comment]
Also, I believe there is no need to do `this._editor.get('nativeEditor').setReadOnly(true);`

**Comment by ipeychev** [comment]
Might be the same like [this](https://github.com/liferay/alloy-editor/issues/556#issuecomment-228513815)

**Comment by ipeychev** [comment]
Hey @pramodrhegde,

Could you please check if the latest version on master fixes this issue too?

Thanks,

**Comment by ipeychev** [comment]
Fixed in [v1.2.3](https://github.com/liferay/alloy-editor/releases/tag/v1.5.3).

**Comment by pramodrhegde** [comment]
Hi thanks! can you please let me know which file(s) you have changed for this fix?

**Comment by ipeychev** [comment]
If I remember correct, [this](https://github.com/liferay/alloy-editor/commit/171804368e75438d4f8ad1f9c60a262f5ad22f9d) was it.
