### ISSUE TITLE
Trigger toolbar show manually

### ISSUE THREAD

**Issue by WhatAKitty** [liferay/alloy-editor#553]
Hi, I am looking for a way that can trigger toolbar show manually.
The reason that why I have to do is: When I trigger context menu, the toolbar will show.

**Comment by ipeychev** [comment]
Hello,

There is no API for this, but you may try the following:
1. Attach a listener to the contextmenu event.
2. Inside the listener, do the following:
```javascript
var selectionData = nativeEditor.getSelectionData();

if (selectionData) {
    nativeEditor.fire('editorInteraction', {
        nativeEvent: event,
        selectionData: selectionData
    });
}
```

where `editor` is the result of `alloyEditor.get('nativeEditor');` and `event` is what was passed to the `contextmenu` listener.

Thanks,

**Comment by WhatAKitty** [comment]
@ipeychev Hi, thanks for your hlep. But unluckly, It was not worked for me.
Following is my code:

```
import React from 'react';
import AlloyEditor from 'alloyeditor';

import './AlloyEditorExtends/ButtonAdd.jsx';

import '../../../../web/styles/alloyeditor/alloy-editor-ocean-min.css';
import '../../../../web/styles/alloyeditor/alloy-editor-custom.css';

let AlloyEditorComponent = React.createClass({
    componentDidMount: function() {
        this.editor = AlloyEditor.editable(this.props.container, this.props.config);
    },
    
    componentWillUnmount: function() {
        this.editor.destroy();
    },
    
    _onDblClick: function(e) {
        e.preventDefault();
        const nativeEditor = this.editor.get('nativeEditor');
        const selectionData = nativeEditor.getSelectionData();

        if (selectionData) {
            nativeEditor.fire('editorInteraction', {
                nativeEvent: event,
                selectionData: selectionData
            });
        }
    },
    
    render: function() {
        return (
            <div className="row">
                <div className="col-xs-10 col-xs-offset-1" >
                    <div id={ this.props.container } className="alloyeditor" onContextMenu={ this._onDblClick }>
                        { this.props.children }
                    </div>
                </div>
            </div>
        );
    }
});

export default AlloyEditorComponent;
```

**Comment by ipeychev** [comment]
And why not? There should be a selection otherwise the toolbar will not show. 
Also, in your function you pass `event` to `nativeEvent`, but the param is called `e`. This does not look correct.

**Comment by WhatAKitty** [comment]
@ipeychev Oh, I see. I made a big mistake, Thanks.

**Comment by WhatAKitty** [comment]
@ipeychev Btw, If there is  no selection, could I trigger toolbar show maually? Like buttonAdd does.

**Comment by ipeychev** [comment]
No, you can't. AlloyEditor's philosophy is to show the toolbars only when needed. If you want an always visible toolbar, please use CKEditor directly.

**Comment by WhatAKitty** [comment]
@ipeychev Oh, I think I was not clear about my question. I don't need a always visible toolbar but a toolbar that I trigger contextMenu evnet.

**Comment by WhatAKitty** [comment]
@ipeychev What I want to do is replace buttonAdd, and show buttonAdd toolbar by trigger contextMenu.

**Comment by ipeychev** [comment]
Please feel free to fork the editor and modify the [code](https://github.com/liferay/alloy-editor/blob/e4cefedd56f45097899466cb61ebec7bcb1f9fbf/src/ui/react/src/components/toolbars/toolbar-add.jsx) of ToolbarAdd. Add listener to the `contextmenu` event and render the Toolbar in the listener.

Thanks,

**Comment by WhatAKitty** [comment]
@ipeychev Ok, I will. Thank you very much.
