### ISSUE TITLE
multiple instance destroy

### ISSUE THREAD

**Issue by myblackboxgithub** [liferay/alloy-editor#555]
Hi, I have still problem enable and disable of alloyeditor.
It doesn't destroy multiple instances properly.

I thought issue #515 have fixed but it isn't.
it makes getRanges null error.
I have produced the error with the code which ipeychev has written.

and I need to add color button along with font, size, 
but doesn't it support the ar bridge for ckeditor colorbox plugin yet?

Thanks.
![instance](https://cloud.githubusercontent.com/assets/15113714/16305332/43c8f946-3951-11e6-8eef-42ccfe5e235f.gif)

**Comment by ipeychev** [comment]
Hello,

It is hard to guess why is that happening from the screencast. Is there a chance to provide some reproducible code, for example as a zip file?

Thanks,

**Comment by myblackboxgithub** [comment]
Thanks @ipeychev, 
I tried to upload the zip here, but it won't accept the zip file to here, so I have put to my onedrive.
https://1drv.ms/u/s!Am_TIh273u0uhSV4rF3_F7esnko4
if there are multiple instances, and it have crashed and make the error.

**Comment by ipeychev** [comment]
I see. Remove `startupFocus: true` and it will start working.

**Comment by myblackboxgithub** [comment]
thanks, I don't think it is a good example to kill instances.
I have put another code and example.
if it has crashed like getRanges error, it doesn't work for alloyeditor bridge of ckeditor plugin(like font, fontsize...)
so I would like to fix the problem.
the code is https://1drv.ms/u/s!Am_TIh273u0uhSZ4rF3_F7esnko4

![getranges](https://cloud.githubusercontent.com/assets/15113714/16333491/5af1254c-39f3-11e6-8eab-6aa2bd4d244b.gif)

**Comment by myblackboxgithub** [comment]
Once it has destroy, with the way 
```
var editor = AlloyEditor.editable('editable');
editor.destroy();
```
CKEDITOR.instances has Object {}
but editor.get('nativeEditor') exists with name of 'editable'.
Would you look at this?
Thanks.
