### ISSUE TITLE
The latest version v1.5.3 or v1.2.3?

### ISSUE THREAD

**Issue by pvnr0082t** [liferay/alloy-editor#559]
Hi @ipeychev ,
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host this project in cdnjs.
I found that the latest released version on GitHub is v1.5.3 but release note is v1.2.3. And the latest version had been published on NPM also v1.2.3. I think that's a typo, right? Thank you.

ref: 
https://github.com/liferay/alloy-editor/releases/tag/v1.5.3
https://www.npmjs.com/package/alloyeditor

https://github.com/cdnjs/cdnjs/issues/8199

**Comment by ipeychev** [comment]
Hello,
This is an issue indeed. The latest version is 1.2.3. I will fix that, thanks for the heads up!

**Comment by ipeychev** [comment]
Fixed, thanks again.

**Comment by pvnr0082t** [comment]
Thanks. @ipeychev  :facepunch:
