### ISSUE TITLE
When setting float image, it breaks through the div

### ISSUE THREAD

**Issue by Kirich11** [liferay/alloy-editor#560]
Is there anyway to prevent this kind of behavior ? Here is a printscreen of  what i mean
![default](https://cloud.githubusercontent.com/assets/18256217/16487758/6ab9c0a6-3ed5-11e6-8a76-fcf0053e175c.png)

**Comment by ipeychev** [comment]
Hello,

As first attempt, you may try to set some margin to the images inside the editable area. For example:
.ae-editable img[style*="float: left"] {
    margin: 20px;
}

Let me know if that helps.

Thanks,

**Comment by Kirich11** [comment]
No, that didn't help. I wrote the margin in chrome console to see what will it do
![rtr](https://cloud.githubusercontent.com/assets/18256217/16515671/ffe77f3c-3f7b-11e6-92a0-2650fac15f6f.png)

**Comment by jbalsas** [comment]
Hey @Kirich11, I think adding `clear: both;` to your content editable area should do the trick

**Comment by Kirich11** [comment]
￼clear: both changes nothing at all =)

Did this issue ever appeared in your tests? 
And the new thing i've discovered is that if you make it `float: left` and then comment it (changing float to none) the position of the image won't change to the initial
![kek](https://cloud.githubusercontent.com/assets/18256217/16516118/ac776ed6-3f7e-11e6-9b3e-be384b3c073d.png)

**Comment by jbalsas** [comment]
Did you add the `float: left` to your content editable container `:after`?

Check out these two animations from our [demo page](http://www.alloyeditor.com/demo), one with clear and one without:

![clear](https://cloud.githubusercontent.com/assets/905006/16516275/7d34c8fa-3f77-11e6-94cc-3f720537c53b.gif)
![no_clear](https://cloud.githubusercontent.com/assets/905006/16516276/7d367c90-3f77-11e6-97a8-cbd16985ec6b.gif)

**Comment by Kirich11** [comment]
So i found how to fix it. In your css the container has `display: table`, which doesn't exist in the editor's css. 
Thx for the quick response

**Comment by ipeychev** [comment]
Great, thanks!
