### ISSUE TITLE
can't add new line after inserting embed link

### ISSUE THREAD

**Issue by brunjick** [liferay/alloy-editor#561]
After inserting embed link on the **last line**, whatever it is, Youtube or Twitter etc. I can't insert new line or paragraph after this. You can reproduce this issue on the official demo page.

I think correct behaviour would be auto inserting new line in that situation, or allowing enter button to insert one when user selects embedded element.

**Comment by ipeychev** [comment]
Hello,

That's true. @jbalsas, could you please take a look?

Thanks,

**Comment by jbalsas** [comment]
Yes, we'll take a look at this and some other pending issues next week

**Comment by antoniopol06** [comment]
Hi!

There are some elements that block creating new lines in CKeditor when they are positioned at the end of the content. You can see this behaviour for elements such as images, tables, cells, embed divs...

To solve this problem you can use the [magic line](http://ckeditor.com/addon/magicline) plugin. This plugin shows an additional button when a new line cannot be created manually after a given block.

We'll need bring this to our UX team to see how we can adapt this concept to better fit into the whole AlloyEditor philosophy.

**Comment by jbalsas** [comment]
Closing this issue for now... if you guys think we should bundle this plugin by default, please let us know.

Thanks!

**Comment by Jikodis** [comment]
It would be great to have this bundled into the plugin by default.

**Comment by jbalsas** [comment]
Hey @lpsBetty, I think we've applied a similar approach in some of our usages. We're actually using `editor.execCommand('enter');` to get the new line from the editor instead of being forced to create the break line ourselves. Might want to take a look at that! 😉

**Comment by lpsBetty** [comment]
@jbalsas ah, thanks! that makes more sense! :)
