### ISSUE TITLE
[question] disable moving toolbar

### ISSUE THREAD

**Issue by brunjick** [liferay/alloy-editor#562]
Can I somehow disable moving toolbar like this? http://i.giphy.com/ngif7CqiJqme4.gif

**Comment by ipeychev** [comment]
Hello,

Which version of the editor are you using? In v1.2.3 it will not move, if you don't leave the editable area. You may check the [live demo](http://alloyeditor.com/demo/)

Here is a screencast:
![ux](https://cloud.githubusercontent.com/assets/78014/16500791/72f9297e-3f06-11e6-9fd4-b9d4659b8645.gif)

**Comment by brunjick** [comment]
@ipeychev Thanks for response, now it's solved. I guess it was because I explicitly set editable element height. The reason I did this, was because, editor didn't have any height when data-placeholder attribute was absent, so it was not shown at all. maybe that's the bug

**Comment by ipeychev** [comment]
Okay, then I will close this. If you think there is something more to discuss, please let me know. Otherwise - glad I helped you.

Thanks,
