### ISSUE TITLE
TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by Tzaphkiel** [liferay/alloy-editor#573]
I've been having issues with the instantiation of the AlloyEditor within a React component and therefore went back to the basics to test and enhance the component by small steps... with tests.

It already fails at requiring of the `alloyeditor` library...

Maybe I'm doing something wrong but I just cannot see it...  :confused:
:eyes: Second pair of eyes (or more) needed pls !

```coffee
should = require('chai').should()
{assert, expect} = require 'chai'
sinon = require 'sinon'
React = require 'react'
{mount} = require 'enzyme'

describe 'Editor component', ->

  it 'Should allow to be loaded through require', ->
    AlloyEditor = require 'alloyeditor'
```

Gives the following trace:
```js
 TypeError: Cannot read property '0' of null
at J:\leroyse\web\sam-client-wp\node_modules\alloyeditor\dist\alloy-editor\alloy-editor-no-react.js:18:39
at J:\leroyse\web\sam-client-wp\node_modules\alloyeditor\dist\alloy-editor\alloy-editor-no-react.js:18:221
at J:\leroyse\web\sam-client-wp\node_modules\alloyeditor\dist\alloy-editor\alloy-editor-no-react.js:20:234
at deployCKEditor (J:\leroyse\web\sam-client-wp\node_modules\alloyeditor\dist\alloy-editor\alloy-editor-no-react.js:821:2726)
at J:\leroyse\web\sam-client-wp\node_modules\alloyeditor\dist\alloy-editor\alloy-editor-no-react.js:1068:8
at Object.<anonymous> (J:\leroyse\web\sam-client-wp\node_modules\alloyeditor\dist\alloy-editor\alloy-editor-no-react.js:14947:2)
at Module.load (J:\leroyse\web\sam-client-wp\node_modules\coffee-react\lib\register.js:44:34)
at require (internal/module.js:16:19)
at Context.<anonymous> (J:\leroyse\web\sam-client-wp\test\components\custom\RichEditor.test.coffee:11:19)
at callFn (J:\leroyse\web\sam-client-wp\node_modules\mocha\lib\runnable.js:326:21)
at Test.Runnable.run (J:\leroyse\web\sam-client-wp\node_modules\mocha\lib\runnable.js:319:7)
at Runner.runTest (J:\leroyse\web\sam-client-wp\node_modules\mocha\lib\runner.js:422:10)
at J:\leroyse\web\sam-client-wp\node_modules\mocha\lib\runner.js:528:12
at next (J:\leroyse\web\sam-client-wp\node_modules\mocha\lib\runner.js:342:14)
at J:\leroyse\web\sam-client-wp\node_modules\mocha\lib\runner.js:352:7
at next (J:\leroyse\web\sam-client-wp\node_modules\mocha\lib\runner.js:284:14)
at Immediate._onImmediate (J:\leroyse\web\sam-client-wp\node_modules\mocha\lib\runner.js:320:5)
```

Using dependencies (not all listed) 
```json
 "dependencies": {
    "alloyeditor": "1.2.3",
    "react": "15.2.1",
  }
```
And I even initialized the jsdom with a location as the stack trace seems to point to the `location.href.match...` in the code and ´href` is supposedly null...:
```js
'use strict';
// src: http://airbnb.io/enzyme/docs/guides/jsdom.html
var jsdom = require('jsdom').jsdom;

jsdom.env({
  url: 'http://localhost/', 'html': '',
  onload: function( window ) {
    console.log(window.location.href); // http://localhost/?something=not#hash
    console.log(window.location.hash); // #hash
  }
});

// setup the simplest document possible
var doc = jsdom('<!doctype html><html><body></body></html>')

// get the window object out of the document
var win = doc.defaultView

// set globals for mocha that make access to document and window feel
// natural in the test environment
global.document = doc
global.window = win

// take all properties of the window object and also attach it to the
// mocha global object
propagateToGlobal(win)

// from mocha-jsdom https://github.com/rstacruz/mocha-jsdom/blob/master/index.js#L80
function propagateToGlobal (window) {
  for (let key in window) {
    if (!window.hasOwnProperty(key)) continue
    if (key in global) continue
    global[key] = window[key]
  }
}

global.navigator = {
  userAgent: 'node.js'
};
```

**Comment by Tzaphkiel** [comment]
If I add this to the setup.test.js:
```js
global.location = {
  hash: "",
  host: "localhost:8080",
  hostname: "localhost",
  href: "http://localhost:8080/",
  origin: "http://localhost:8080",
  pathname: "/",
  port: "8080",
  protocol: "http:",
  search: ''
};
```

The error goes away but another appears:
```js
  ReferenceError: CKEDITOR is not defined
 at J:\leroyse\web\sam-client-wp\node_modules\alloyeditor\dist\alloy-editor\alloy-editor-no-react.js:21:1
 at deployCKEditor (J:\leroyse\web\sam-client-wp\node_modules\alloyeditor\dist\alloy-editor\alloy-editor-no-react.js:821:2726)
 at J:\leroyse\web\sam-client-wp\node_modules\alloyeditor\dist\alloy-editor\alloy-editor-no-react.js:1068:8
 at Object.<anonymous> (J:\leroyse\web\sam-client-wp\node_modules\alloyeditor\dist\alloy-editor\alloy-editor-no-react.js:14947:2)
 at Module.load (J:\leroyse\web\sam-client-wp\node_modules\coffee-react\lib\register.js:44:34)
 at require (internal/module.js:16:19)
...
```

I don't think I should have to define location globally... It should be taken from `window` instead

**Comment by ipeychev** [comment]
Hello,

Did you see [this](https://github.com/ipeychev/alloyeditor-react-component) repository? Could you please check how we are requiring the editor there?

I also went ahead and checked it requiring works. It does, please check the attached file. Please extract it and run "npm i && npm test".

[alloyeditor-require.zip](https://github.com/liferay/alloy-editor/files/384575/alloyeditor-require.zip)

Thanks,

**Comment by Tzaphkiel** [comment]
I've been doing some more tests and it seems to have to do with whether I use Jsdom or not in my component's tests and if I set it in the global scope or not...

I am using Enzyme with chai and mocha and `mount` the components under tests when I need to deeply verify their behavior. 
If I use `shallow` however, I don't need Jsdom and there is no problem to require AlloyEditor.
Maybe this helps narrow down the problem or gives a hint on what I could/should do to solve it.

**Comment by ipeychev** [comment]
Hello,

I'm not familiar with Enzyme and JSDOM I'm personally avoiding as a plague. I'm not sure what you mean with `shallow `. In general, this problem doesn't look to be related to AlloyEditor, but despite of that, here is a general hint from me:
Try to stay as close to the real environment as possible. Don't use JSDOM, and don't use headless browsers like PhantomJS. Use real ones, since that is what your users will use. Otherwise, your tests will be pointless.

Thanks,

**Comment by Rohan-Doshi** [comment]
I am using JEST(which uses JSDOM) for testing my application which has alloyeditor on one of the page. I am facing a similar issue. Did you find a work-around @Tzaphkiel

**Comment by Tzaphkiel** [comment]
@Rohan-Doshi No I did not and I stopped testing AlloyEditor components that way since I had to deliver the application.
I've instead and unfortunately resorted to manual testing thinking I would give it a try afterwards... but you know how that goes.

**Comment by Rohan-Doshi** [comment]
The issue for me was alloyeditor was not able to find the value for `CKEDITOR_BASEPATH` and `ALLOYEDITOR_BASEPATH` during JEST testing. I had it defined in index.html as shown [here](https://github.com/ipeychev/alloyeditor-react-component/blob/master/src/index.html), and JEST doesn't bundle everything before testing. 
So I added my node_modules in JEST Test environment and set these in my JEST global variables.

Hope this helps @Tzaphkiel

**Comment by Tzaphkiel** [comment]
That sounds about right... I'll give it a try when I get a chance.
Thx @Rohan-Doshi
