### ISSUE TITLE
Access CKEditor document model

### ISSUE THREAD

**Issue by brunjick** [liferay/alloy-editor#577]
As documented [here](https://github.com/ckeditor/ckeditor5-design/wiki/Document-Model#the-api) "The API entry point is reachable through the `editor.dm` property", but I can't access it through this way
```
var nativeEditor = this.editor.get('nativeEditor');
console.log(nativeEditor.dm); //undefined
```
am I doing something wrong?

**Comment by ipeychev** [comment]
Hello,

The link to the documentation posted above is about CKEditor 5. It is not yet released. AlloyEditor uses the engine from CKEditor 4.

Thanks,
