### ISSUE TITLE
Issues in using CKEditor's colorbutton plugin.

### ISSUE THREAD

**Issue by riteshjagga** [liferay/alloy-editor#578]
I implemented text and background color feature using `colorbutton` plugin of `CKEditor`.

Here are the dependencies:

     var extraPlugins = AlloyEditor.Core.ATTRS.extraPlugins.value
          + ',ae_buttonbridge'
          + ',ae_panelmenubuttonbridge'
          + ',colorbutton';

but there are few issues with this:
 1. Scrollbar of web page disappears when button is clicked. Compare the two screenshots.
 2. The grid of colors is very small. Need to know a way to make each color item bigger.
 3. What is the purpose of down arrow when panel of colors opens. Is it a UI bug?

![screen shot 2016-08-04 at 12 36 47 pm](https://cloud.githubusercontent.com/assets/13287256/17393266/38d89db0-5a40-11e6-9887-8a128f3cea97.png)
![screen shot 2016-08-04 at 12 37 00 pm](https://cloud.githubusercontent.com/assets/13287256/17393267/38d9e08a-5a40-11e6-8ea2-b6dc6122d5c8.png)

**Comment by ipeychev** [comment]
Hello,

1) and 2) are questions for CKEditor's forums, since these are third party plugins.
About 3) - the arrow points to the selection. We don't distinguish if the panel is open or not and I personally find it useful. You may try to hide it with some CSS if it disturbs you.

Thanks,
