### ISSUE TITLE
Combobox dropdown goes under other toolbar buttons

### ISSUE THREAD

**Issue by riteshjagga** [liferay/alloy-editor#579]
I am selecting some text in the far right of the editor which resizes the toolbar in three lines. When I open a control having a dropdown, the dropdown goes under other toolbar buttons. It is then impossible to select the dropdown item e.g. `Arial` in the `Font` combobox.

![screen shot 2016-08-04 at 12 44 23 pm](https://cloud.githubusercontent.com/assets/13287256/17393427/4934ec9e-5a41-11e6-84b4-63666de2808a.png)

**Comment by ipeychev** [comment]
Hello,

This you may fix by adding a z-index property to the dropdown element in your application. By default AlloyEditor does not add any because the values are very specific to each application.

Thanks,

**Comment by riteshjagga** [comment]
Thank you. Adding this class fixed it:

```
.ae-ui .ae-dropdown {
  z-index: 1;
}
```
