### ISSUE TITLE
Whenever focus on Alloy Editor for the first time $ undefined error coming.

### ISSUE THREAD

**Issue by pramodrhegde** [liferay/alloy-editor#580]
**alloy-editor-no-react.js:14915 Uncaught TypeError: Cannot read property '$' of undefined**
this is the issue we are getting recently or we have noticed recently that happens very randomly mostly first time Alloy Editor is loaded. our guess is that its because of Alloy Editor not yet loaded and we are trying to edit it.
we are using it in React component. 
is there any ways we know that Alloy Editor is loaded so that we can enable editor div after that ?

Thanks in advance !

**Comment by ipeychev** [comment]
Hello,

Yes, there is an event for that:
```
alloyEditor.get('nativeEditor').on('instanceReady', ...);
```

Thanks,

**Comment by pramodrhegde** [comment]
Thanks !
