### ISSUE TITLE
Problem with resizing images in Firefox

### ISSUE THREAD

**Issue by Bjarno** [liferay/alloy-editor#582]
The handles to resize an image are placed incorrectly when the image in centered...

[example image](https://i.imgur.com/ynbrlMk.png) (tried it with the web demo to make sure there was nothing wrong with my setup)

This appears on the latest version of Alloy Editor (1.2.3) on Mozilla Firefox. It doesn't happen at all on Google Chrome.

Another, possibly related, issue I have with images is that whenever you change the alignment, the resize handles aren't updated directly, only when clicking somewhere else and clicking again on the image.

There are no error messages in the console.

**Comment by ipeychev** [comment]
Hello,

The problem is that AlloyEditor doesn't deal with image resizing in Firefox. This is it's native behavior. Maybe it doesn't like the styles AlloyEditor applies to the image in case of centering it.

**Comment by Bjarno** [comment]
Any idea where I can disable Firefox behaviour and maybe try the webkit plugin?

**Comment by ipeychev** [comment]
1. There are threads about disabling img resizing, for example [here](http://stackoverflow.com/questions/289433/firefox-designmode-disable-image-resizing-handles).
2. You will have to modify the checks, where [this](https://github.com/liferay/alloy-editor/blob/ad527762e1e4c52b993f1cd8b104b279fab442b1/src/plugins/dragresize.js#L18) variable is used.

**Comment by Bjarno** [comment]
Disabling Firefox behaviour and also checking if the browser is Firefox solved this for me, without any side effects at first glance. May need more checks to make sure nothing else gets broken of course.

**Comment by ipeychev** [comment]
Good! Then, would you like to send us a pull request? We may change the default behavior and use the plugin in Firefox too.

Thanks,
