### ISSUE TITLE
Uncaught TypeError: Cannot read property '$' of undefined

### ISSUE THREAD

**Issue by yourGuy** [liferay/alloy-editor#586]
my set up :
webpack 1.13.1
react 15.2.1

I installed alloy via npm (npm install alloyeditor)
my app likes more or less like this:

```
import React from 'react';
var AlloyEditor = require('alloyeditor');

var Designer = React.createClass({
    componentDidMount: function() {
        this._editor = AlloyEditor.editable('my-profile-container');
    },
    render: function() {
        return (
            <div id="my-profile-container">Edit this</div>
        );
    }
});
export default Designer;
```
The result I'm getting an error in the console  on load : 
alloy-editor-no-react.js:14915 Uncaught TypeError: Cannot read property '$' of undefined
However the content is editable but no toolbar or any other buttons are showing
The error is additionally thrown every time I focus on the editable area

**Comment by ipeychev** [comment]
With this information is hard to say, but please check the attached file for an working example and also [this](https://github.com/ipeychev/alloyeditor-react-component) repository.
[test.zip](https://github.com/liferay/alloy-editor/files/453196/test.zip)

Thanks,

**Comment by hew** [comment]
It's because of react router.

**Comment by shruti2015** [comment]
Hey , @hew I am also using in same as yours but getting following errors in browser console.

bundle.js:37833 GET http://localhost:2222/lang/alloy-editor/en-gb.js?t=G4CD 
bundle.js:37833 GET http://localhost:2222/config.js?t=G4CD 404 (Not Found)
bundle.js:37833 GET http://localhost:2222/skins/moono/editor.css?t=G4CD 
bundle.js:37977 Uncaught TypeError: Cannot set property 'dir' of undefined(…)

I would appreciate any help from you.

**Comment by shruti2015** [comment]
Hey @hew I am also using alloy as your but getting following errors.

> bundle.js:37833 GET http://localhost:2222/lang/alloy-editor/en-gb.js?t=G4CD
> bundle.js:37833 GET http://localhost:2222/config.js?t=G4CD 404 
> bundle.js:37833 GET http://localhost:2222/skins/moono/editor.css?t=G4CD 
> bundle.js:37833 GET http://localhost:2222/lang/en-gb.js?t=G4CD 
> bundle.js:37977 Uncaught TypeError: Cannot set property 'dir' of undefined(…)

would appreciate any help from you.
