### ISSUE TITLE
Is there an event I can hook on when clicking on the confirmation button (the checkbox)?

### ISSUE THREAD

**Issue by gablabelle** [liferay/alloy-editor#587]
Hello,

Is there an event I can hook on when clicking on the confirmation button (the checkbox) ?

![screen shot 2016-09-15 at 11 00 10 am](https://cloud.githubusercontent.com/assets/1565793/18554863/a5c12582-7b33-11e6-8200-6ad9fcaccde0.png)

The problem I'm facing is that when I create a link and confirm, the change event is not triggered. So I need to make another change to the content in order to trigger the change event and make sure that newly created link will be saved when submitting the form.

Here is the config:

```
getAlloyEditorConfigs() {
    return {
      toolbars: {
        add: {
          buttons: [
            'image',
            'hline'
          ],
          tabIndex: 2
        },
        styles: {
          selections: [
            {
              name: 'text',
              buttons: [{
                name: 'styles',
                cfg: {
                  styles: [
                    {
                      name: 'Titre',
                      style: {element: 'h3'}
                    },
                    {
                      name: 'Sous-Titre',
                      style: {element: 'h4'}
                    }
                  ]
                }
              },
                'bold',
                'italic',
                'underline',
                'ul',
                'link'
              ],
              test: AlloyEditor.SelectionTest.text
            }
          ]
        }
      }
    };
  },
```

Did not find any event listed in the [ButtonLink api docs](http://alloyeditor.com/api/classes/ButtonLink.html). Any other suggestion would be appreciated.

Thanks for your help.

**Comment by ipeychev** [comment]
Hello,

There is a way to achieve it, but this looks like a dirty hack to me. I'm trying to understand why you need a subscription to `change` event? Aren't you submitting the content directly to the server? If so, the created link should be saved to the server.

Thanks,

**Comment by gablabelle** [comment]
@ipeychev the short story is that is we update the object being sent to the server on submit when the editor triggers an "change" event. So after creating a link it's doesn't trigger the change event and does not update until I make another change that triggers the needed event.

So please explain how to achieve even if it's a dirty hack. ;-)

Thanks.

**Comment by sebastienjust** [comment]
Hello, 
we just discovered the same issue. When a link is applied to text (either by clicking on the OK button or pressing ENTER key), we don't receive change event from ckEditor.
Here is how we get the underlying editor change events : 
```
this._editor = AlloyEditor.editable(this.domNode, { ... });
this._ckEditor = this._editor.get('nativeEditor');

// later ...
var ckEditor = this._ckEditor;
var self = this;
this._subWidgetListener = ckEditor.on("change", function (evt) {
    var value = ckEditor.getData();
    console.debug(value);
    self._set("value", value);
});
```

So, if you have an idea on how we can trigger the event (or fix the problem) ?

Following your question on why the data is not sent to server : in our case, we listen for changes on all widgets to do some pre-processing before sending data to server (for example, extracting images in data: format) and also enable/disable "save", "undo" buttons on the form that holds the fields. This also contributes to keep the form abstract data model in sync with all form fields and make the "save" operations transactional for a whole abstract data model.

Thanks,
(by the way Alloy is great, users love it)

**Comment by ipeychev** [comment]
Okay, here it is:
AlloyEditor fires an general event in case of user triggered actions and it is called `actionPerformed`. Making a text bold, adding a link, image, etc. will fire this event, so you may try to subscribe to it in the same way you as you would subscribe to `change` event.
Why don't we fire `change` event? At least because of these reasons:
1. This event is fired by CKEditor's engine and we didn't want to mess with it.
2. The fact that user performs an action (clicks on a button) doesn't necessarily mean that there will be a change. The event will be fired, but it might be prevented for example. It also follows a logical sequence - there _might_ be a change as result of an action, performed by the user.

@sebastienjust Thanks for the nice words :)

Thanks,

**Comment by gablabelle** [comment]
@ipeychev thanks a lot for your reply. it did exactly what I was hoping for. Problem solved here. ;-)

Thanks again.

**Comment by ipeychev** [comment]
Great!
