### ISSUE TITLE
File upload in link dialog

### ISSUE THREAD

**Issue by mattleff** [liferay/alloy-editor#588]
For our usage of AlloyEditor we need the ability for users to upload files that will be linked. Something like this:

![image](https://cloud.githubusercontent.com/assets/120155/18588646/52c368aa-7bf5-11e6-8f6f-06d6dc362840.png)

Is this something that the AlloyEditor project would be interested in including or is it not in scope for the project? I think we could implement it in a generic fashion using a Promise similar to how the link autocomplete was done (#488). The upload button would only be shown if a Promise was provided in the config.

**Comment by ipeychev** [comment]
Hello,

Thanks for the suggestion. May I request some screencast or a link to live demo, please? From this image I'm not completely sure how exactly it would work.

Thanks,

**Comment by jbalsas** [comment]
Hey @mattleff, I think this might fall a bit out of the scope of the project. I doubt we'd be able to provide a generic enough feature that would serve different purposes and environments.

For instance, in Liferay, we've developed that feature as a set [plugin](https://github.com/liferay/liferay-portal/tree/master/modules/apps/foundation/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/plugins/itemselector) that you can configure and add to the toolbar. In our case, we're using the `+` toolbar on the left for such interactions.

![item_selector](https://cloud.githubusercontent.com/assets/905006/18627810/544783b8-7e5d-11e6-9758-f5b3cb8df6b3.gif)

You can see in this case a specific portion of that, [inserting an image from a persisted file](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/plugins/itemselector/plugin.js#L367-L378). You could do something similar and provide whatever markup you wished.

What do you think?

**Comment by mattleff** [comment]
Here's a screen recording of what we're thinking: https://vimeo.com/183392551

At this point the only changes I had to make to Alloy were to show the file upload button and have it call a delegate method to show the file upload/picking UI ([Filestack](https://www.filestack.com/)). I can understand if that's not a method you want to support for core Alloy.

**Comment by ipeychev** [comment]
Hey @mattleff,

In general, I like the idea to have such a functionality and your approach (call a function) looks generic enough. Maybe we can have this button only if the user explicitly configures the link and provides a method for uploading.

@jbalsas The plugin you created looks cool too. Wouldn't it work (with a few tweaks) if attached to such a button in the link toolbar? Also, what do you think about @mattleff's approach?

Thanks,

**Comment by jbalsas** [comment]
Hey @ipeychev, @mattleff 

Don't get me wrong... I love this feature, but the fact that you guys managed to implement it without a lot of trouble makes me think that we've succeeded in making an extensible enough environment, so I'd be reluctant to add more features that will need to be supported in the future.

In this line of thought, what I see might be missing is a way to configure what shows in a button without the need of rewriting or monkey-patching it. Foreseen future needs... maybe what we need is some kind of "plugin" or "add-on" infrastructure that could be used to hook into the rendering of the buttons? Something like:

```javascript
{
        name: 'link',
        buttons: [{
            name: 'linkEdit',
            cfg: {
                addons: [MattLeff.FilePicker]
            }
        }],
        test: AlloyEditor.SelectionTest.link
}
```

What do you guys think?

**Comment by mattleff** [comment]
Hey @jbalsas, @ipeychev,

I totally get that this is kind of a specific use-case. Further discussion around the link dialog has taken us in a slightly different direction, adding some other features that might be specific to our users (link preview, targets in autocomplete results, etc.). If you get another request in the future for upload support you could consider adding support at that point.
