### ISSUE TITLE
Is there an onChange or similar event?

### ISSUE THREAD

**Issue by souptown** [liferay/alloy-editor#593]
After half an hour of searching the Guides and API docs, I can't figure out how to be notified when the user changes the text in the editor.

**Comment by ipeychev** [comment]
Hey Matt,

Sorry for that. AlloyEditor uses CKEditor's engine, so its API is valid for AlloyEditor too. In this case, you may subscribe to its [change](http://docs.ckeditor.com/#!/api/CKEDITOR.editor-event-change) event like this:
```javascript
var editor = AlloyEditor.editable('editable');
var nativeEditor = editor.get('nativeEditor'); // this is CKEditor's instance
nativeEditor.on('change', function() { 
    console.log('TEST');
});
```

Thanks,

**Comment by souptown** [comment]
Great - that did the trick. Thank you!
