### ISSUE TITLE
CKEditor 5

### ISSUE THREAD

**Issue by n-scope** [liferay/alloy-editor#594]
Thanks for this great editor !

I am on a project which needs collaborative editing. It seems CKEditor 5 uses an OT based model, and collaborative editing is on the roadmap.

Perhaps it is a little premature as CKEditor 5 is not yet released, but do you plan to support/migrate to it when it will ?

**Comment by ipeychev** [comment]
Yes, sure, we do. This would be the base for version 2.x

**Comment by n-scope** [comment]
Thanks, great news !
