### ISSUE TITLE
Dynamic change of CKEditor config params

### ISSUE THREAD

**Issue by etovolchanka** [liferay/alloy-editor#599]
Is there any way to change config parameters of ckeditor instance using an external button? e.g.
Toggle forcePasteAsPlainText by onClick

**Comment by ipeychev** [comment]
Hello,

About `forcePasteAsPlainText` you should ask in CKEditor's forums, I don't know the answer of this particular question, but you may get the instance of CKEditor by using the code below. After that, all the API of CKEditor will be available for you.
```javascript
var alloyEditor = AlloyEditor.editable('editableElement');
var ckeditorInstance = alloyEditor.get('nativeEditor');
```

Thanks,
