### ISSUE TITLE
Using CKEDITOR Plugins with Alloyeditor (Spell Checker)

### ISSUE THREAD

**Issue by sharmamahesh** [liferay/alloy-editor#602]
Hi

I want to use CKEditor plugins SpellCheker with Alloyeditor? (e.g.: http://ckeditor.com/addon/scayt).
I have downloaded  SCAYT plugin and all the dependencies plugins as well and put those in plugins folder. I have attached a file having code for spell checker. I have tried to add Spell check button to the toolbar but i am not able to add that. So, is there any way to add Spell Check button.

[CKeditorPluggin.txt](https://github.com/liferay/alloy-editor/files/518986/CKeditorPluggin.txt)

**Comment by ipeychev** [comment]
Hello,

What means "i am not able to add that"? Is there some issue you encounter with adding a button?
There are examples about adding buttons on AlloyEditor site, you may check them if you are not sure how to do it. The source code is full of examples too.

Thanks,

**Comment by sharmamahesh** [comment]
Hello, 
I have checked for font size and i am able to add font size button to the alloy editor toolbar. But i have a requirement in that i need to add Spell Check button to the toolbar. I used ckeditor plugins still not able to add spell check button to the alloy editor toolbar. I had attached a file regarding spell checker code in my last comment. Can you look and let me know what wrong i am doing?

**Comment by jbalsas** [comment]
Hey @sharmamahesh, @ipeychev, the `scayt` plugin uses `CKEDITOR.UI_MENUBUTTON`, which we currently don't support out of the box. We can work on support for this, but in the meantime you'll need to create your own button for it if you need to use it with current versions.

**Comment by jbalsas** [comment]
I'm adding this to the `1.3.0` milestone as well.

**Comment by sharmamahesh** [comment]
Hi,
Can you provide any document  on how to add UI_MENUBUTTON.

**Comment by jbalsas** [comment]
Hey @sharmamahesh, I'll be sending a PR adding support for `UI_MENUBUTTON` soon, so it will be available once we release `1.3.0`. You will be able to do the same you do for other buttons using the new `menubuttonbridge` plugin. We'll update the site with documentation for it as well.

In the case of the `scayt` plugin, you'll also need to add all the other necessary plugins such as `contextmenu`,  `floatpanel`... for everything to work, but I'm testing and it is doable.

**Comment by sharmamahesh** [comment]
when can we expect release 1.3.0?

**Comment by jbalsas** [comment]
We are targeting end of next week for it: https://github.com/liferay/alloy-editor/milestone/41

**Comment by sharmamahesh** [comment]
Any update on this issue?

**Comment by jbalsas** [comment]
Hey @sharmamahesh, code is sent and we are waiting to merge https://github.com/liferay/alloy-editor/pull/643 before we can release the new version.

We've also created some tutorials that will show how to use this feature. We'll make them public as soon as we release the version.

**Comment by sharmamahesh** [comment]
Hi jbalsas,
I am using latest version of Alloy editor(1.3.0).
Still i am not able to add spellcheck.
I have created a demo and you can download the zip from https://www.sendspace.com/file/bhf5ny
Can you please look into this?
