### ISSUE TITLE
CKEditor change event not being called on styles update

### ISSUE THREAD

**Issue by wenneberg6** [liferay/alloy-editor#607]
Modifying a paragraph to a heading using the Alloy styles dropdown, or the Heading 1 button, does not trigger a CKEditor change event. 

Example using your own demo:
http://alloyeditor.com/demo/

Paste this snippet into dev-tool console and then change a paragraph to a heading. 
With an ordinary CKEditor instance the function would be called.
```
CKEDITOR.instances.contentEditable.on('change', function(){
   console.log('change')
})
```

This also affects the undo functionality.  
Tested using Chrome and Firefox on windows.

Thanks

**Comment by MrJingles2016** [comment]
I experience the same behavior when removing a link. CKEDITOR is not notifyed when I remove a link via the Edit link toolbar ?

**Comment by ipeychev** [comment]
Hello,

It will not, there is a separate event for that: https://github.com/liferay/alloy-editor/issues/587#issuecomment-247514942

Thanks,

**Comment by wenneberg6** [comment]
Thanks, made it work listening for both the 'actionPerformed' and 'change' events. 

When doing "bold", "italic", "underline", **both events** are fired. For some, this might be an issue.

**Comment by ipeychev** [comment]
You may subscribe to both events in the same time and debounce the function.
