### ISSUE TITLE
Keep custom class from original textarea

### ISSUE THREAD

**Issue by vichenze** [liferay/alloy-editor#610]
Hello,

I have a textarea like this before loading alloy-editor:

`<textarea class="**bg-success character-count**" name="chapoOri" id="chapoOri"></textarea>`

And then Alloy editor creates the following div:
`<div class="cke_textarea_inline cke_editable cke_editable_inline cke_contents_ltr ae-editable" tabindex="0" spellcheck="true" role="textbox" contenteditable="true"></div>`

I'd like to keep in the editable div the classes from the original textarea (bg-success character-count), or eventually add them manually after the editable div was created. How can I do that ?

Thanks !

**Comment by ipeychev** [comment]
Hello,

You may subscribe to the event fired when AlloyEditor's instance is created and then restore the classes, like this:
```
var alloyEditor = AlloyEditor.editable('editable');
var nativeEditor = alloyEditor.get('nativeEditor');

nativeEditor.on('instanceReady', function(event) {
var editableArea = nativeEditor.editable();
// restore the classes here
});
```

Thanks,

**Comment by vichenze** [comment]
Thanks !
