### ISSUE TITLE
Toolbar background color for Safari

### ISSUE THREAD

**Issue by sharmamahesh** [liferay/alloy-editor#611]
Hi,
 I have created a sample in which i have added most of the controls to the Alloy editor toolbar. 
For Safari, the toolbar colors becomes white for half of the controls.
Also is there any way to add the buttons into new line?

I have attached demo as well as screenshots in Safari as well as Chrome for refernce.

![safariissue](https://cloud.githubusercontent.com/assets/22740015/19649953/54271d42-9a25-11e6-8ebe-1a81b97f478d.png)
![chrome](https://cloud.githubusercontent.com/assets/22740015/19649954/5444ef66-9a25-11e6-8bc0-8c2a61c6abcb.png)
[index.txt](https://github.com/liferay/alloy-editor/files/548128/index.txt)

**Comment by ipeychev** [comment]
Hello,

For the Safari issue, I will /cc @jbalsas here.
About displaying the buttons on a second row, AlloyEditor does not provide such functionality. Its idea is to keep just a few buttons and not to have a giant toolbar. You can play however with CSS and you should be able to achieve it.

Thanks,

**Comment by jbalsas** [comment]
Hey @sharmamahesh, thanks for reporting!

We'll take a look at the Safari issue.

/cc @antoniopol06

**Comment by sharmamahesh** [comment]
I am facing 1 more problem in IE. When there are many buttons in the toolbar then they are not automatically adjusted to the next line but for chrome and firefox they appear in the next line.

I have attached the screen shots for IE and Chrome for reference.
![chrome_toolbar](https://cloud.githubusercontent.com/assets/22740015/19768434/1a6bb890-9c75-11e6-938f-b80fccd4fe3b.png)
![ie_toolbar](https://cloud.githubusercontent.com/assets/22740015/19768435/1a6fd16e-9c75-11e6-8167-afd62a7962bd.png)

**Comment by jbalsas** [comment]
Hey @sharmamahesh, thanks for reporting, we'll also take a look into this. We're finishing some other tasks and will take on this one next.

**Comment by sharmamahesh** [comment]
Any update on this issue?

**Comment by jbalsas** [comment]
Hey @sharmamahesh, we briefly took a look but we're still not sure what's going on.

I'm scheduling it for the next version as well, so hopefully we'll have news soon.

Thanks!

**Comment by antoniopol06** [comment]
Hi @sharmamahesh 

I couldn´t reproduce the issue about Safari but I sent pull request to fix the IE problem. 

Thanks for reporting that!
