### ISSUE TITLE
How to add cancelBubble event for the alloy editor buttons.

### ISSUE THREAD

**Issue by sharmamahesh** [liferay/alloy-editor#612]
Hi,
I have attached alloy editor to Dhtmlx Grid's cell using excell type.
When I select the content of the editor, toolbar of Alloy editor appears and when I click on any button (say bold) of Alloy editor's toolbar, grid's cell is getting detach and the content is also not changed to bold.
So, I need to add cancelbubble event for the alloy editor buttons. I am stuck and not able to proceed. Please reply with the solution.

I have attached file and screen shots for the reference.

![beforeclickonbold](https://cloud.githubusercontent.com/assets/22740015/19888320/e75722fe-a053-11e6-9d7d-21eba47ee107.PNG)
![afterclickonbold](https://cloud.githubusercontent.com/assets/22740015/19888321/e75882f2-a053-11e6-9a9d-e3eefdcdb154.PNG)

[dhtmlxgrid_excell_custom_editor.txt](https://github.com/liferay/alloy-editor/files/563852/dhtmlxgrid_excell_custom_editor.txt)

**Comment by ipeychev** [comment]
Hello,

You may try to subscribe to 'actionPerformed' event and then to stop event's propagation, like this:
```javascript
var alloyEditor = AlloyEditor.editable('editable');
var nativeEditor = alloyEditor.get('nativeEditor');

nativeEditor.on('actionPerformed', function(event) {
  event.stopPropagation();
});
```

Thanks,

**Comment by sharmamahesh** [comment]
Hello, 
 I tried using 'actionPerformed' event but still it is not working. 
When i clicked on bold button it doesnot call 'actionPerformed' event.
I have attached the file for the reference.
[dhtmlxgrid_excell_custom_editor.txt](https://github.com/liferay/alloy-editor/files/569036/dhtmlxgrid_excell_custom_editor.txt)

**Comment by ipeychev** [comment]
I don't see something wrong with the subscription to the event. Please provide a zip file with code, which reproduces the issue or create something online, on jsFiddle or wherever.

**Comment by ipeychev** [comment]
This complain is for GitHub. Meanwhile you can add an example on Plunker

**Comment by sharmamahesh** [comment]
Hi,
You can download the demo zip from https://www.sendspace.com/file/0mfghl

**Comment by sharmamahesh** [comment]
Any update on this issue?

**Comment by ipeychev** [comment]
The `detach` function is called before `actionPerformed` subscription. This destroys the editor -  that's the main reason `actionPerformed` does not work for you.

You may do the following:
1. A `onclick` event is attached to the document but it does not propagate event to the `detach` function. Please pass it.
2. In `detach` function, check if the main UI element of the editor contains the current event target, like this:
```javascript
dhtmlxEvent(document.body, "click", function(event) {
        if (self.editStop) {
            self.editStop(event) // editStop should pass the event to the detach function
        }
        if (self.isActive) {
            self.setActive(false)
        }
    });

// inside detach function
if (!document.getElementsByClassName('ae-ui')[0].contains(event.target)) {
    // stop editing, this means the active element does not belong to the editor - user clicked somewhere else
}
```

Thanks,
