### ISSUE TITLE
OnBlur Event  is triggered on click on Dropdown list button.

### ISSUE THREAD

**Issue by qasid** [liferay/alloy-editor#613]
I have implemented ck-editor on blur function such that it sets contenteditable property of editable div to false. 
The problem I'm having is that it is called even when click on Dropdown List button, due to which alloy editor fails to apply selected styles since the content is not editable now. 

1: Why is onBlur event called in case of Dropdown List? 
2: Is there a way to prevent it?

**Comment by jbalsas** [comment]
Will investigate

**Comment by qasid** [comment]
@jbalsas  any update?

**Comment by jbalsas** [comment]
Hey @qasid, @ipeychev, sorry this dropped off my radar... 

I think this is caused by the fact that our UI sits outside the editor and gains focus, thus blurring the editor...

**Comment by Tzaphkiel** [comment]
Hello,

I seem to also have the problem in my react component.

I basically wanted to only activate the editor when I clicked on the react component: that works.
I wanted then to de-activate the editor when I lost focus (in the editor), i.e.: blur of the CKEDITOR.editor

My deactivation is however triggered any time I click on a drop-down menu item of the editor's toolbar.
The following CKEDITOR documentation specifically mentions that it should not be the case:


> Note: This event will NOT be triggered when focus is moved internally, e.g. from an editable to another part of the editor UI like a dialog window. If you are interested only in the focus state of the editable, listen to the focus and blur events of the CKEDITOR.editable instead.
_src: https://docs.ckeditor.com/#!/api/CKEDITOR.editor-event-blur_

I'm wondering if I'm setting the "blur" event on the right component...

```js
class RichEditor extends React.Component {
  constructor (props) {
    super(props)
    this.state = {isEditorActive: false, content: props.content}

    this.propagateChange = this.propagateChange.bind(this)
    this.activate = this.activate.bind(this)
    this.deActivate = this.deActivate.bind(this)
  }
  // ...
  activate () {
    if (this.state.isEditorActive) return
    this.alloyEd = AlloyEditor.editable(this.props.container, editorConfig)
    this.ckeditor = this.alloyEd.get('nativeEditor')
    this.ckeditor.setData(this.props.content, {internal: false})
    this.ckeditor.on('change', this.propagateChange)
    this.ckeditor.on('paste', this.propagateChange)
    this.ckeditor.on('blur', this.deActivate)

    this.setState({isEditorActive: true})
  }
  deActivate (evt) {
    if (!this.state.isEditorActive) return
    if (evt) evt.stop()
    this.setState({isEditorActive: false})
    if (this.ckeditor) {
      this.ckeditor.removeListener('blur', this.deActivate)
      this.ckeditor.removeListener('paste', this.propagateChange)
      this.ckeditor.removeListener('change', this.propagateChange)
      try {
        this.alloyEd.destroy()
      } catch (err) {
        // ignore
      }
    }
  }

  componentWillUnmount () {
    this.deActivate()
  }
  // ...
}
```

**Comment by wincent** [comment]
By way of "spring cleaning", I'm closing issues tagged with "question" that haven't had any activity in > 12 months. There have been quite a few releases since then and much has changed, and these "stale" issues are extremely unlikely to be acted on. Please feel free to comment and we can re-open on a case-by-case basis.
