### ISSUE TITLE
Cannot read property 'setAttribute' of null

### ISSUE THREAD

**Issue by anagorn** [liferay/alloy-editor#615]
Hi,

I don't get the editor up and running after following your instructions and seeing the examples given.
Environment: React v15.3.2 (with Webpack), NPM v3.10.8, Node v6.7.0

- I've installed the editor via NPM
- I've added the following code in the head of my index.html:
 `    <script>
      window.ALLOYEDITOR_BASEPATH = '/node_modules/alloyeditor/dist/alloy-editor/';
      window.CKEDITOR_BASEPATH = '/node_modules/alloyeditor/dist/alloy-editor/';
    </script>`

In header.js:
`class HeaderHolder extends Component {
var AlloyEditor = require('alloyeditor');
/****/
 componentDidMount() {
        this._editor = AlloyEditor.editable(this.props.container, this.props.alloyEditorConfig);
    }
  componentWillUnmount() {
    this._editor.destroy();
}
render() {
       /***/
                                <div id={this.props.container}>
                                    <h1>AlloyEditor will make this content editable</h1>
                                    <p>
                                        Example text
                                    </p>
                                </div>`

But when I browse to my application, an console error appears:
_bundle.js:31693 Uncaught TypeError: Cannot read property 'setAttribute' of null_

I've search for similar issues but I didn't find them. Can you help me figure this one out?
Thanks in advance!

**Comment by ipeychev** [comment]
Hello,

Probably the element, which are you passing to AlloyEditor as the editable element cannot be retrieved/it doesn't exist.

Thanks,

**Comment by praWINK** [comment]
I am new to reactjs and i also have this same issue @jpeychev could you plz elaborate this answer

**Comment by ipeychev** [comment]
Hey @praWINK, probably the same what I said in [this](https://github.com/liferay/alloy-editor/issues/615#issuecomment-257970162) comment is valid in your case too.
