### ISSUE TITLE
Release v1.2.5

### ISSUE THREAD

**Issue by jbalsas** [liferay/alloy-editor#616]
Hey @ipeychev, I'm planning to release `1.2.5`.

Is there anything you'd like to see in there, or is it fine for me to cut it with what we have?

Thanks!

**Comment by ipeychev** [comment]
No, Chema, go ahead

**Comment by jbalsas** [comment]
Hey Iliyan, I've fixed one failing test and tagged the release. I'm in the process of updating the website.

The only thing I'm missing is permission to publish the npm module. Could you add my user so I can also do that?

Thanks!

**Comment by ipeychev** [comment]
Hey Chema,

I added you, go ahead.

<img width="301" alt="ls" src="https://cloud.githubusercontent.com/assets/78014/19994575/f0c3b0d4-a24f-11e6-9640-a31a97038872.png">


Thanks,

**Comment by jbalsas** [comment]
Awesome!!

AlloyEditor `1.2.5` has been published.. and we have a green set of tests again!! 🎉 

<img width="375" alt="screen shot 2016-11-04 at 09 12 11" src="https://cloud.githubusercontent.com/assets/905006/19998738/d0d0219e-a26e-11e6-8769-8cfe31de8cd4.png">

(Missing Edge here... should we reconsider our support matrix to add it?)

**Comment by ipeychev** [comment]
Great!
And yes, adding Edge makes sense totally.

**Comment by jbalsas** [comment]
We'll try to do that for `1.3.0` ;)

How do you feel about dropping support for some of those old IE's for `2.0.0`?

**Comment by ipeychev** [comment]
For 2.0 definitely. Maybe support IE11+, or even only Edge
