### ISSUE TITLE
Add Support for Edge

### ISSUE THREAD

**Issue by jbalsas** [liferay/alloy-editor#617]
AlloyEditor should be tested and supported in Edge as well as the rest of supported browsers

**Comment by pierre-weceipt** [comment]
I'm using edge ATM with alloyeditor and no bug to report so far.

**Comment by jbalsas** [comment]
Hey @pierre-weceipt, thanks a lot for letting us know, that's wonderful news!

For us to officially support it would mean that we automatically run all the tests on Edge as well, to make sure we don't introduce any regression. ☺️

**Comment by pierre-weceipt** [comment]
Yup, that make sense. But it's always good to know that things are working and that you probably won't have anything to debug :D

**Comment by jbalsas** [comment]
Yeah, this definitely make me more confident in achieving this ☺️ 

BTW, @pierre-weceipt, could you share with us where are you using AlloyEditor? Are you finding it useful? Did you find any issues? We'd appreciate any feedback to help us plan the future roadmap 😉

**Comment by pierre-weceipt** [comment]
We are using it in a document template editor to avoid having toolbars everywhere; it helps keeping the UI clean^^ 
So far our client like it, the contextual toolbar is intuitive and easy to use. As a developper I'm not confident enough in react.js to customize some buttons. The thing I miss most is an easy API to add custom CSS classes to the elements to help with the integration in other frameworks and already existing apps. It could be added to the configuration object used when creating the editor.

**Comment by jdalton** [comment]
It may be as easy as adding it to the SauceLabs [browsers array](https://github.com/liferay/alloy-editor/blob/25151898f9385f09096f05ab7cf30aeea281330d/test/core/karma.js#L74).

**Comment by hew** [comment]
Might want to update the README re: Edge.
