### ISSUE TITLE
Switch to CKEditor5

### ISSUE THREAD

**Issue by jbalsas** [liferay/alloy-editor#618]
CKEditor is releasing periodic [Developer Previews](http://ckeditor.com/blog/Third-Developer-Preview-of-CKEditor-5-Available) of its newer version.

We should start playing around with it and make sure we are ready to do the switch when it's released.

This will be the base of our `2.0.0.` version.

**Comment by jbalsas** [comment]
I'm removing the `2.0.0` milestone since the recently released CKEditor5 is changing licensing models, so we probably need to stick with `4.x` until we figure it out.

**Comment by wincent** [comment]
Closing this because of the aforementioned licensing issues. Also, no plans to drop support for IE11 as long as it appears in the Liferay DXP compatibility matrix (and it still does).
