### ISSUE TITLE
alloy-editor-no-react-min.js:860 Uncaught TypeError: Cannot read property 'PropTypes' of undefined

### ISSUE THREAD

**Issue by thanhthang20** [liferay/alloy-editor#621]
![screen shot 2016-11-14 at 8 27 30 am](https://cloud.githubusercontent.com/assets/5382700/20250712/472d2a12-aa44-11e6-8a89-a94408ab6b91.png)

```
class NewPost extends React.Component {
  constructor(props) {}

  componentDidMount() {
    AlloyEditor.editable('myContentEditable');
  }

  render() {
    return (<div id='myContentEditable'></div>)
  }
}
```
```

<html>
  <head>
    <link rel='stylesheet' href='/bower_components/alloyeditor/dist/alloy-editor/assets/alloy-editor-ocean-min.css'>
  </head>
  <body>
    <div id="root">${html}</div>
    <script src="/script/vendor.bundle.js"></script>
    <script src='/bower_components/alloyeditor/dist/alloy-editor/alloy-editor-no-react-min.js'>     </script>
    <script src="/script/bundle.js"></script>
  </body>
</html>
```

**Comment by ipeychev** [comment]
![screen shot 2016-11-14 at 9 39 42 pm](https://cloud.githubusercontent.com/assets/78014/20282001/1bae4bf4-aab3-11e6-9d61-c3b9e8acb122.png)

**Comment by ipeychev** [comment]
It is not easy to say what is wrong without reproducible code, but from the error I would say that React is missing for some reason. Check how do you import it.

**Comment by thanhthang20** [comment]
@ipeychev 
It works now. You are right.
This is the best Editor I have ever seen.

Back to the problem:
I complied React into "vendor.bundle.js" and my code into "bundle.js". Then I install Alloy with Bower and load "alloy-editor-no-react-min.js" separately.   

The problem is that above way working when I using Browserify but NOT work when I using Webpack.

**Comment by ipeychev** [comment]
Great, glad it worked.
