### ISSUE TITLE
[Question] Does destroying editor instance clear event listeners?

### ISSUE THREAD

**Issue by brunjick** [liferay/alloy-editor#629]
I have an SPA application, so on component destroy hook I want to destroy editor as well. But on initialization I set event listeners on native CKEditor instance like this:
```js
var nativeEditor = editor.get('nativeEditor');
nativeEditor.on('focus', () => {
    // do stuff
});
```
So, does `editor.destroy()` clear these event listeners or should I remove them manually?

**Comment by ipeychev** [comment]
It should destroy them
