### ISSUE TITLE
IE11: Some of the options in toolbar are shown in different color

### ISSUE THREAD

**Issue by sharmamahesh** [liferay/alloy-editor#634]
Hi,
I have added ck editor pluggins for "undo","redo","find" ,"paste as plain text" and "smiley" and use these in Alloy editor toolbar.These options in the toolbar are shown in different color (Black) than the others, hence they look like disabled/ inactive (when they are not). 
The issue is only for IE browser for chrome and firefox its working.

I have attached the screenshots for chrome and IE for refernce.
![ie11_toolbar_issue](https://cloud.githubusercontent.com/assets/22740015/20483139/87052784-b016-11e6-9720-0203bfc729fd.png)
![chrome_toolbar](https://cloud.githubusercontent.com/assets/22740015/20483140/87055434-b016-11e6-8a14-9fcf820fe152.png)

**Comment by jbalsas** [comment]
Hey @sharmamahesh, can you let us know in which specific version of IE is this happening?

**Comment by sharmamahesh** [comment]
yes,
I have attached a screen shot regarding version.
![ie11_version](https://cloud.githubusercontent.com/assets/22740015/20483597/de920164-b018-11e6-9631-29fde70a9747.png)

**Comment by jbalsas** [comment]
Thanks a lot for reporting, @sharmamahesh!

This is probably related due to some lack of css filters support in IE. We are using css filters to colour the png icons coming from ckeditor, but it's a complicated process.

We'll investigate to see if we can support this in IE as well.

**Comment by sharmamahesh** [comment]
Any update on this issue?

**Comment by sharmamahesh** [comment]
Any update on this issue?

**Comment by antoniopol06** [comment]
Hi @sharmamahesh ,

We worked on this issue. To convert the icons, that plugins use, to white color, AlloyEditor use filter css property.
Unfortunately, [IE removed -ms-filter property](https://msdn.microsoft.com/en-us/library/ms530752(v=vs.85).aspx) and [DX Filters for IE was marked as obsolete](https://msdn.microsoft.com/en-us/library/hh801215(v=vs.85).aspx) and it does not work too.

AlloyEditor has other themes, and the moono theme is fit to see the icons of the toolbar with the same color.

We need to research about what is the best way to resolve this issue. 

We think about adding a task to the build to generate a sprite or copy the icons from official ckeditor plugins when the browser is IE 10 and IE 11. What do you think @ipeychev ?

Thanks for reporting this issue.

**Comment by sharmamahesh** [comment]
Any update on this issue?

**Comment by sharmamahesh** [comment]
Any update on this issue?

**Comment by wincent** [comment]
Doing some "spring cleaning" by closing issues that were opened in 2016 — much has changed since then and there have been many releases, so there is a risk that these older issues have grown very stale and are very unlikely to be acted upon. Please feel free to commend and we can look at re-opening on a case-by-case basis.
