### ISSUE TITLE
Table borders are not visible on copy + paste text from excel

### ISSUE THREAD

**Issue by sharmamahesh** [liferay/alloy-editor#635]
Hi.
When i try to copy and paste table from excel to editor ,no table border displayed form copied text ( though it has border added ).
I have attached screen shots for the reference.
![table_border_issue](https://cloud.githubusercontent.com/assets/22740015/20484487/6c5ad81e-b01d-11e6-85ae-00f1d01045e6.png)
![excel_table](https://cloud.githubusercontent.com/assets/22740015/20484493/740b6a4c-b01d-11e6-9123-9722867a25f0.png)

**Comment by jbalsas** [comment]
Hey @sharmamahesh, this happens because we're not providing styling for the tables, iirc... you probably can simply add your own css to give tables whatever styling you want.

**Comment by sharmamahesh** [comment]
Hi,
When we copy a table from word and paste to alloy editor then it shows the border of the table. but for excel it does not shows.

**Comment by sharmamahesh** [comment]
i have checked on http://ckeditor.com/ and table borders are visible.

**Comment by ipeychev** [comment]
Hey @sharmamahesh,

@jbalsas's piece of advice was good. CKEditor add a special class - " cke_show_border" with some predefined style for the borders, which doesn't necessarily match the borders, set in Word or Excel. 
Please go ahead and add some basic CSS for the borders, for example:
```css
.ae-editable table td, .ae-editable table th {
    border: #d3d3d3 1px dotted;
}
```
