### ISSUE TITLE
IE09: Insert image is not working

### ISSUE THREAD

**Issue by sharmamahesh** [liferay/alloy-editor#637]
Hi,
when i try to insert image in IE9, the image is not inserted.
I have attached a screen shot having version of IE.
![ie9_version](https://cloud.githubusercontent.com/assets/22740015/20553181/479735f2-b178-11e6-84ed-7a64100f72bd.png)

**Comment by sharmamahesh** [comment]
Any update on this issue?

**Comment by jbalsas** [comment]
Hey @sharmamahesh, what's the difference with https://github.com/liferay/alloy-editor/issues/637?

Can you please provide the specific steps to reproduce the issue? There are many different ways to get images in the editor, so the more specific you are the fastest we can figure out what's going on.

**Comment by sharmamahesh** [comment]
Hi @jbalsas,
I tried to insert image using Insert Image icon in the Alloy editor toolbar in IE09 but image is not inserted.
While for IE10 and IE11 image is inserted.

#644 issue related with drag/drop and copy/paste of images.

**Comment by jbalsas** [comment]
Thanks @sharmamahesh, we'll take a look, no timeline for a fix yet.

**Comment by antoniopol06** [comment]
Hi @sharmamahesh ,

Internet Explorer 9 does not support [files property](https://msdn.microsoft.com/en-us/library/hh772931(v=vs.85).aspx) and [file object](https://msdn.microsoft.com/en-us/library/hh772305(v=vs.85).aspx)

We will research what is the best way to resolve this issue.

Thanks!

**Comment by sharmamahesh** [comment]
Any update on this issue?

**Comment by sharmamahesh** [comment]
Any update on this issue?

**Comment by wincent** [comment]
Sorry that this went unanswered for so long. IE 11 is the oldest version of IE that AlloyEditor supports, so issues under IE 9 are to be expected. (In general, our supported browsers are the ones listed in [the Liferay Compatibility Matrix for Liferay DXP](https://web.liferay.com/documents/14/21598941/Liferay+DXP+7.1+Compatibility+Matrix/9f9c917a-c620-427b-865d-5c4b4a00be85)).
