### ISSUE TITLE
On copy + paste from Microsoft word doc( having text and image) , it doenot paste image

### ISSUE THREAD

**Issue by sharmamahesh** [liferay/alloy-editor#639]
Hi,
When i copy and paste some content from Microsoft word document having text and image. Only text is displayed and copied image is not displayed . ( when we only copy image and paste then it works )
I have attached screen shots and word file for the reference.

[Test.docx](https://github.com/liferay/alloy-editor/files/608939/Test.docx)
![issue while copy paste image with text](https://cloud.githubusercontent.com/assets/22740015/20563465/c8812b42-b1ae-11e6-915c-2c406d498aa5.png)

**Comment by ipeychev** [comment]
Hello,

Which browser is that?

**Comment by sharmamahesh** [comment]
Hi, I am using Chrome.

**Comment by sharmamahesh** [comment]
Any update on this issue?

**Comment by jbalsas** [comment]
Hey @sharmamahesh, we are simply using the `pastefromword` plugin that comes by default with it, so it's probably not something we can fix on our own.

Could you please test on the [CKEditor](http://ckeditor.com/) page to see if it happens there as well?

**Comment by sharmamahesh** [comment]
I have checked on CKEditor. same behaviour shown there as well.

**Comment by jbalsas** [comment]
Hey @sharmamahesh, in that case, you should open an issue on their [ticket system](http://dev.ckeditor.com/) so they can take a look and fix it. Once it's fixed and release, we'll get it simply by updating our CKEditor version.
