### ISSUE TITLE
Support additional toolbar context decision flow

### ISSUE THREAD

**Issue by jbalsas** [liferay/alloy-editor#64]
Developers should be able to add their own toolbars and define the conditions that drive which context they affect.

Some toolbars may respond to the same context, but some may be more specific than others, and the one may take precedence over the other.

Additionally, some toolbars may not be entirely dependant on context and may decide to not participate in the context decision process.

**Comment by ipeychev** [comment]
Fixed via commit https://github.com/liferay/alloy-editor/commit/fe6b81178ab9f90a9ee31949521d71fc2ed72082
