### ISSUE TITLE
IE : Image drag and drop and copy/paste is not working

### ISSUE THREAD

**Issue by sharmamahesh** [liferay/alloy-editor#644]
Hi,
I have a text area in which Alloy editor is attached.
1. When i try to drag and drop the image in IE 11, IE 10 and IE 9, it is not working. But for other browsers its working.
2. Copy/ Paste of image is only working in Firefox browser. For rest of the browsers(Chrome and IE) its not working. 
I have attached the file for refernce and IE 11 version screen shot.
![ie 11 version](https://cloud.githubusercontent.com/assets/22740015/20703615/5a0fe462-b642-11e6-9ce6-8cddfe9efcf0.png)

[index.txt](https://github.com/liferay/alloy-editor/files/618529/index.txt)

**Comment by antoniopol06** [comment]
Hi @sharmamahesh !

I tried to reproduce these issues but I could not. What version of AlloyEditor did you use?

Thanks for reporting that.

**Comment by sharmamahesh** [comment]
AlloyEditor v1.2.3

**Comment by antoniopol06** [comment]
The following gifs show what I did to try to reproduce your issue on AlloyEditor 1.2.5:
![Uploading dragresize_ie.gif…]()
![Uploading copypaste.gif…]()

What steps did you use to reproduce the issues?

Thanks!!!

**Comment by sharmamahesh** [comment]
Hi,
I have a text area and i have attached Alloy editor to the text area.
Then i try to drag and drop a image in IE9,10 and 11 but its not working.
I have attached a file for reference.

Copy/paste of image is not working in Chrome and IE. You can check it on Alloy editor live demo as well.
Its only working in Firefox.
[index.txt](https://github.com/liferay/alloy-editor/files/626666/index.txt)

**Comment by sharmamahesh** [comment]
Any update?

**Comment by wincent** [comment]
Doing some "spring cleaning" by closing issues that were opened in 2016 — much has changed since then and there have been many releases, so there is a risk that these older issues have grown very stale and are very unlikely to be acted upon. Please feel free to commend and we can look at re-opening on a case-by-case basis.
