### ISSUE TITLE
Wrong link for How to build it

### ISSUE THREAD

**Issue by carlosdelsol** [liferay/alloy-editor#646]
This link doesn't work

![howtobuildit](https://cloud.githubusercontent.com/assets/6344173/20802617/e2b06908-b7ec-11e6-8825-ac3928dc9037.png)
![404notfoud](https://cloud.githubusercontent.com/assets/6344173/20802618/e2b32abc-b7ec-11e6-9b2a-1de11f57a4b2.png)

**Comment by jbalsas** [comment]
Thanks for reporting this, @carlosdelsol!

I've fixed the url and we've pushed a new version together with the `1.3.0` release ;)
