### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by jbalsas** [liferay/alloy-editor#649]

**Comment by jbalsas** [comment]
Release is officially done :)

- [Tag](https://github.com/liferay/alloy-editor/tree/v1.3.0)
- [Npm package](https://www.npmjs.com/package/alloyeditor)
- [Site update](http://alloyeditor.com/updates/)
- [Twitter announcement](https://twitter.com/jbalsas/status/805751669497667584)

**Comment by ipeychev** [comment]
Awesome!
