### ISSUE TITLE
Using CKEDITOR Plugins with Alloyeditor (Spell Checker)

### ISSUE THREAD

**Issue by sharmamahesh** [liferay/alloy-editor#650]
Hi jbalsas,
Regarding issue: https://github.com/liferay/alloy-editor/issues/602
I am using latest version of Alloy editor(1.3.0).
Still i am not able to add spellcheck.
I have created a demo and you can download the zip from https://www.sendspace.com/file/bhf5ny
Can you please look into this?

**Comment by sharmamahesh** [comment]
Any update on this issue?

**Comment by sharmamahesh** [comment]
Any update on this issue?

**Comment by antoniopol06** [comment]
Hi @sharmamahesh ,

We added tutorials about using this kind of CKEDITOR plugins, you can find it [here](http://alloyeditor.com/guides/ckeditor_plugins/ui_menu_button_bridge/)

You need to add to extraPlugins 'ae_menubridge,ae_menubuttonbridge' just before 'scayt'. This new AlloyEditor plugins work as adapter to use menubuttons from CKEDITOR plugins.

Let me know if you have problem to add it.

Thanks!

**Comment by sharmamahesh** [comment]
Hi @antoniopol06 ,
I have added ae_menubridge,ae_menubuttonbridge before 'scayt' and i am able to add spell check button.
But there is some issues which i am facing.
1. Check spelling option is missing.
2. Option "Disbale SCAYT" is not shown. If we want to disable spell check we again need to click on "Enable SCAYT".

I have attached screen shots of ckeditor and alloy editor both for refernce.
![ckeditor_spellcheck](https://cloud.githubusercontent.com/assets/22740015/21421764/92ff8640-c85a-11e6-8791-5ff99798fcfd.png)
![disable_scayt](https://cloud.githubusercontent.com/assets/22740015/21421763/92ff5350-c85a-11e6-973f-d99fe233c117.png)
![spell_check_missing_cheking_spell](https://cloud.githubusercontent.com/assets/22740015/21421766/93006600-c85a-11e6-8f8c-d54e719b71ad.png)
![ckeditor_disable_scayt](https://cloud.githubusercontent.com/assets/22740015/21421765/930055ac-c85a-11e6-8633-7a2888a95cc8.png)

**Comment by sharmamahesh** [comment]
Any update on this issue?

**Comment by jbalsas** [comment]
Hey @sharmamahesh, this is working exactly as expected and as it does in CKEditor.

- You only see the 'Enable SCAYT' option until you enable it, since it isn't enabled by default. Then, you have the 'Disable SCAYT' option to turn it off again.
- In order to see the ' Check Spelling' option, you need to add and enable the [wsc plugin](http://ckeditor.com/addon/wsc) as well.
