### ISSUE TITLE
IE9 issue with Alloy editor when attached to DhtmlxGrid

### ISSUE THREAD

**Issue by sharmamahesh** [liferay/alloy-editor#653]
Hi,
I have attached Alloy editor to the Dhtmlx grid cell. 
If i click on any cell that is attached to Alloy editor then it is open but if i want to edit another cell that cell is no longer editable.
This issue is specifically for IE9.

It works fine for other browsers.

I have attached a demo at following url https://www.sendspace.com/file/aayuly 
and screen shot of error which i got in the browser console for reference.
![alloyeditorissue](https://cloud.githubusercontent.com/assets/22740015/21012536/8e5efe88-bd7c-11e6-9d4f-14f71d6aa1de.png)

**Comment by sharmamahesh** [comment]
Any update on this issue?

**Comment by sharmamahesh** [comment]
Any update on this issue?

**Comment by wincent** [comment]
Sorry that this went unanswered for so long. IE 11 is the oldest version of IE that AlloyEditor supports, so issues under IE 9 are to be expected. (In general, our supported browsers are the ones listed in [the Liferay Compatibility Matrix for Liferay DXP](https://web.liferay.com/documents/14/21598941/Liferay+DXP+7.1+Compatibility+Matrix/9f9c917a-c620-427b-865d-5c4b4a00be85)).
