### ISSUE TITLE
Keyup events slow with large documents

### ISSUE THREAD

**Issue by waltonseymour** [liferay/alloy-editor#654]
Hi,

When using a sample text of Hamlet ([link](http://courses.cs.washington.edu/courses/cse341/07wi/handouts/hamlet.txt)), each keystroke takes around 100ms, which is considerable slower than CKEditor.

I'm working with minified builds and running in production mode. My guess is that is has something to do with [this event listener](https://github.com/liferay/alloy-editor/blob/master/src/core/uicore.js#L147).

![screen shot 2016-12-11 at 1 33 09 pm](https://cloud.githubusercontent.com/assets/7594493/21082294/1e1ccbd2-bfa7-11e6-995e-259718f7a806.png)

Any suggestions for how to reduce this latency?

**Comment by waltonseymour** [comment]
Interestingly, I don't notice any latency issues on the demo on http://alloyeditor.com

**Comment by ipeychev** [comment]
Hello,

I added this text to our internal [demo page ](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/demo/index.html) and checked. It worked fine.
Therefore, it must be something specific for the environment where you noticed the issue. What is it? What is the browser? Have you added any additional plugins?

Thanks,

**Comment by waltonseymour** [comment]
I'm using chromium and I haven't added any plugins. I can take a look at it later tonight and try to debug it a bit more.

Thanks.

**Comment by waltonseymour** [comment]
After digging a bit, I've found a reproduction.

Simply pasting it in will result in raw text wrapped in a <pre> tag. If you convert the text to "normal", where each paragraph becomes a <p> tag, you'll notice the latency.

I've gotten this behavior on http://alloyeditor.com/ as well

**Comment by ipeychev** [comment]
Fixed, please see the commit message for more information.

Thanks for the report.

**Comment by waltonseymour** [comment]
Awesome, thanks
