### ISSUE TITLE
Placeholder CSS

### ISSUE THREAD

**Issue by antoniopol06** [liferay/alloy-editor#655]
Placeholder class is customizable and its css styles uses a fix ae-placeholder class.

This placeholder should have min-height to show always the placeholder. When its parent has 0px and it has overflow: hidden, ::before is not showed.

**Comment by ipeychev** [comment]
Hey @antoniopol06,

This change - the issue and the fix look odd at first glance. Adding the CSS from the source means that the user won't be able to change it and this is what we usually try to avoid.

Also, what do you mean with  the following: "When its parent has 0px and it has overflow: hidden, ::before is not showed."? The parent of the placeholder is supposed to be the editable are itself, isn't it? What does that mean, that the editable area has 0px height and it has `overflow: hidden`? This looks odd, the editable area is not supposed to has 0px height. What is the user case here?

Thanks,

**Comment by antoniopol06** [comment]
Hi @ipeychev ,

You are right, I researched more about the use case, and it is not an AlloyEditor problem. This issue can be closed.

Thanks!!!
