### ISSUE TITLE
autolinkAdd doesn't work on urls that contain - in the domain name

### ISSUE THREAD

**Issue by deadcyclo** [liferay/alloy-editor#657]
The autolinkAdd feature ignores urls that contain a - So for example https://alloyeditor.com would be recognized as an url while https://alloy-editor.com would not even though alloy-editor.com is a perfectly legal domain name. I have verified that this issue occurs also in your online demo.

**Comment by ipeychev** [comment]
Thanks for the report, I'll take a look.

**Comment by ipeychev** [comment]
Ah, thanks, @antoniopol06, will check the PR later today or tomorrow morning.
