### ISSUE TITLE
Typo in getToolbarButtons method

### ISSUE THREAD

**Issue by zsagia** [liferay/alloy-editor#663]
In toolbar-buttons.js in row 35 we need to use "buttonCfg[button.name]" instead of "buttonCfg[button]" 

https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/components/base/toolbar-buttons.js#L35

This mistake cause the given configs won't be merged to defaults.

**Comment by ipeychev** [comment]
Hm, interesting how we didn't see that so far, that part is pretty old code. Could you please be more specific about the issue? For example, could you please provide some example configuration which cannot be merged. This will help to create a test.

**Comment by zsagia** [comment]
Hi Iliyan,

We realized this issue in portal master after I made a fix for  "showTargetSelector" https://github.com/liferay/alloy-editor/commit/b9ec505c0ab494fd97488e974e86f57d30bbbaca

My portal fix is: https://github.com/zsagia/liferay-portal/commit/3f4476bd857f8ac9280bbbc04bffdf1581bd36b5

This is not reproducible on alloy-editor master branch

I debugged alloy-editor and I noticed that this issue is causing if the "buttons" list contains objects instead of strings.

For example:
in portal environment "buttons" list has an object: {name: 'linkEdit', cfg:{...}}
in alloy-editor demo "buttons" list has a string: 'linkEdit'

**Comment by zsagia** [comment]
"interesting how we didn't see that so far, that part is pretty old code."

Maybe nobody uses linkEdit element with "showTargetSelector=false".

**Comment by ipeychev** [comment]
Then, @antoniopol06, could you please make the change and confirm with @zsagia it fixes the issue?

**Comment by antoniopol06** [comment]
Hi @zsagia !

You need to put showTargetSelector into [cfg property](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/components/base/toolbar-buttons.js#L35).

Then you need to replace [getToolbarsStylesSelectionsLinkJSONObject](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-editor/frontend-editor-alloyeditor-web/src/main/java/com/liferay/frontend/editor/alloyeditor/web/internal/editor/configuration/AlloyEditorCreoleConfigContributor.java#L157-L165) with the following code:
`

		protected JSONObject getToolbarsStylesSelectionsLinkJSONObject() {

		JSONObject jsonObject = JSONFactoryUtil.createJSONObject();

		JSONArray linkButtonsJSONArray = JSONFactoryUtil.createJSONArray();

		JSONObject jsonLinkEditObject = JSONFactoryUtil.createJSONObject();

		JSONObject cfgJSONObject = JSONFactoryUtil.createJSONObject();

		cfgJSONObject.put("showTargetSelector", false);

		jsonLinkEditObject.put("name", "linkEdit");
		jsonLinkEditObject.put("cfg", cfgJSONObject);

		linkButtonsJSONArray.put(jsonLinkEditObject);

		jsonObject.put("buttons", linkButtonsJSONArray);
		jsonObject.put("name", "link");

		jsonObject.put("test", "AlloyEditor.SelectionTest.link");

		return jsonObject;
	}
`

Let me know if it works.

Thanks a lot!

**Comment by zsagia** [comment]
Hi @antoniopol06,

I tested your suggested solution and it worked for me but, the config will be correct, it needs my previous config as well what I mentioned above.
Sorry about my false ticket opening I thought one config is enough for the hidden target button.

Can I use your code in my updated pull-request?

Thanks for your help. :)

**Comment by antoniopol06** [comment]
Hi @zsagia !

Yes, of course!

Thanks!

**Comment by jbalsas** [comment]
@antoniopol06, @zsagia can we close this, then?

**Comment by zsagia** [comment]
I think yes. We could make a correct portal config on master which solved this issue.

**Comment by jbalsas** [comment]
awesome, thanks! 👍
