### ISSUE TITLE
Spacing between two lines

### ISSUE THREAD

**Issue by sharmamahesh** [liferay/alloy-editor#665]
Hi,
Can we reduce the spacing between two lines in Alloy editor.
I have attached a screen shot for refernce.
![spacing](https://cloud.githubusercontent.com/assets/22740015/21682040/583edb04-d378-11e6-9341-06ba81305429.png)

**Comment by ipeychev** [comment]
Hello,

Yes, you may add some custom style to `p` (paragraph) elements and decrease `line-height` and `margin-bottom`.

Thanks,
