### ISSUE TITLE
Allow discovery of plugin buttons via `ae_uibridge`

### ISSUE THREAD

**Issue by jbalsas** [liferay/alloy-editor#667]
AlloyEditor supports [using CKEditor plugins](http://alloyeditor.com/guides/how_to_use_ckeditor_plugins/) thanks to the `ae_*bridge` set of plugins. However, in order to add the buttons to a toolbar, the user needs to figure out how is the particular plugin naming the button, so for instance, in order to use the `Paste from Word` plugin, one would need to do the following:

```js
var editor = AlloyEditor.editable('editable', {
    extraPlugins: AlloyEditor.Core.ATTRS.extraPlugins.value +',ae_uibridge,ae_buttonbridge,pastefromword,clipboard,dialog,dialogui',
    toolbars: {
        add: {
            buttons: ['table', 'hline', 'image', 'camera', 'PasteFromWord']
        },
        ...
    }
});
```

Since this is error-prone and forces the user to dig into the plugin code for the exact string, it would be nice to have some kind of API so a user could simply do:

```js
var editor = AlloyEditor.editable('editable', {
    extraPlugins: AlloyEditor.Core.ATTRS.extraPlugins.value +',ae_uibridge,ae_buttonbridge,pastefromword,clipboard,dialog,dialogui',
    toolbars: {
        add: {
            buttons: ['table', 'hline', 'image', 'camera', ...AlloyEditor.getButtonsFor('pastefromword')]
        },
        ...
    }
});
```

**Comment by jbalsas** [comment]
This won't make it in the `1.3.1` milestone. Targeting next release now...

**Comment by julien** [comment]
Hi @jbalsas,

Could you tell me if something like this:

https://github.com/julien/alloy-editor/commit/942227556bb70cde6cd9f429947732a88725796e

Would be a possible implementation?

Thanks!

**Comment by jbalsas** [comment]
Hey @julien, thanks for the work on this. Unfortunately, I don't think that's a viable implementation. We need these to be dynamic in a way that only available buttons show up and in a way we don't have to manually maintain a plugin list.

On top of that, there are some plugins exposing more than one ui component. For example the [`font plugin`](https://github.com/ckeditor/ckeditor-dev/blob/master/plugins/font/plugin.js) introduces two buttons [`Font`](https://github.com/ckeditor/ckeditor-dev/blob/master/plugins/font/plugin.js#L231) and [`FontSize`](https://github.com/ckeditor/ckeditor-dev/blob/master/plugins/font/plugin.js#L232)

The expected behaviour would be:

```javascript
// Scenario 1, font plugin is loaded using extraPlugins
editor.getButtonsFor('font'); // ['Font', 'FontSize']
```

```javascript
// Scenario 2, font plugin is not loaded
editor.getButtonsFor('font'); // []
```

I think the common entry point is https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/uibridge/uibridge.js#L27-L35, or inside the independent `add` handlers of every bridge. Plugins registering ui components are necessarily running over those handlers, and if we could identify the calling plugin, then we'd have a dynamic and real map of the available buttons.

**Comment by julien** [comment]
Hi @jbalsas you're welcome, and thanks for the pointers I will have a look in that direction.

**Comment by julien** [comment]
Hi again @jbalsas,

So I had a look at [https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/uibridge/uibridge.js#L27-L35](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/uibridge/uibridge.js#L27-L35) and it was a good starting point.

I haven't prepared any **pr** yet, but as I understand we need some kind of "iterator" to go through all the "required" plugins given a plugin name ... (please correct me if I'm wrong) 

I've modified my previous code to look like this

```javascript
getButtonFor: function (name) {
    
    function PluginIterator(plugin) {
        this.plugin = plugin;
    }
    
    PluginIterator.prototype.hasNext = function () {
        return this.plugin && this.plugin.requires;
    };
    
    PluginIterator.prototype.next = function () {
        var plugin = CKEDITOR.plugins.get(this.plugin.requires);
        if (plugin) {
            this.plugin = plugin;
        }
        return this.plugin.name;
    };

    var plugin = CKEDITOR.plugins.get(name.toLowerCase());
    if (!plugin) {
        return '';
    }

    var iterator = new PluginIterator(plugin);
    var requires = [plugin.name];
    while (iterator.hasNext()) {
        requires.push(iterator.next());
    }
    return requires;
}
``` 

Which would work the following way

```javascript
AlloyEditor.getButtonFor('PasteFromWord');
// output: ["pastefromword", "clipboard", "dialog", "dialogui"]

// or in the case of an unexisting plugin

AlloyEditor.getButtonFor('NoSuchPluginRegistered');
// output: ''
```

The `PluginIterator` might not be the best name and should probably be placed in another file (or it's own file) rather than being in the `getButtonFor` function, but tell me if that looks better than previously.

Thanks!

**Comment by jbalsas** [comment]
Hey @julien, you're overthinking this. Take the `font` plugin as an example.

You can see that it will call the [`editor.ui.addRichCombo`](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/uibridge/richcombo.jsx#L221-L223) method one per registered ui component.

In there, we already have the buttons names, so we could simply do:

```javascript
var pluginName = /plugins\/(.*)\/plugin.js/.exec((new Error().stack));

AlloyEditor.BRIDGE_BUTTONS[pluginName] = AlloyEditor.BRIDGE_BUTTONS[pluginName].push(richComboName);
```

Then, you should simply need something like:

```javascript
AlloyEditor.getButtonFor = function(pluginName) {
    return AlloyEditor.BRIDGE_BUTTONS[pluginName] || [];
}
```

Now, of course throwing an error to get the plugin name sounds like a very bad idea, so it'd be better to be able to do it in a nicer way :)

**Comment by jbalsas** [comment]
I've re-added this to the now `1.4.0` milestone. Based on https://github.com/liferay/alloy-editor/pull/718 I'm confident we can land this soon....
