### ISSUE TITLE
Spell check enable/disable at initialization of Alloy editor

### ISSUE THREAD

**Issue by sharmamahesh** [liferay/alloy-editor#672]
Hi,
Is there any way to enable/disable spell check at the time of initialization of editor?

**Comment by jbalsas** [comment]
Hey @sharmamahesh, isn't this answered [here](https://github.com/liferay/alloy-editor/issues/650)?

**Comment by jbalsas** [comment]
If what you want is change the configuration, then sure, you can pass any configuration you want when you initialize the editor:

```
AlloyEditor.editable({
    scayt_autoStartup: true
})
```

**Comment by sharmamahesh** [comment]
Thanks @jbalsas ,
Can we also add setting of dictionary to Oxford. So that on right click of text it give suggestions.

**Comment by jbalsas** [comment]
Honestly, I have no idea, @sharmamahesh.

You can pass any configuration you need to the plugin there. You should investigate how to do that in the plugin documentation.

**Comment by jbalsas** [comment]
For right click, however, you'll have to reenable plugins such `contextmenu` and maybe add some others. Update your [`removePlugins` configuration](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/adapter/alloy-editor.js#L369) depending on what you need. Again, you need to check the plugin to see what dependencies it has.

**Comment by jbalsas** [comment]
Closing... please @sharmamahesh let us know if you still have more questions about this.
