### ISSUE TITLE
Alloy Editor option not get enabled

### ISSUE THREAD

**Issue by sharmamahesh** [liferay/alloy-editor#680]
Hi,
Sometimes alloy editor ( i.e. + icon ) option is not get enabled. And on console log it gives an error 
"Uncaught TypeError: Cannot read property '$' of undefined
    at t._setUIHidden (alloy-editor-all-min.js:880)
    at t.<anonymous> (alloy-editor-all-min.js:880)"

On refresh page, Alloy Editor ( i.e. + icon ) option get enabled.

I have checked on Alloy editor Demo as well.
Attaching a screen shot for reference.
![console_log](https://cloud.githubusercontent.com/assets/22740015/22250696/d8250484-e26d-11e6-97c0-8cdb511ccded.png)

**Comment by ipeychev** [comment]
Hey @sharmamahesh,

Thanks for the report. Without debugging, I think this happens if user starts to interact with the editable area before editor to be fully initialised.
@antoniopol06 or @julien, could you please verify?

Thanks,

**Comment by julien** [comment]
Hi @ipeychev,  I'm having a look at it, the behaviour is exactly what you described.
