### ISSUE TITLE
contextmenu for spell check

### ISSUE THREAD

**Issue by sharmamahesh** [liferay/alloy-editor#681]
Hi
I have added contextmenu for spell check as discussed in https://github.com/liferay/alloy-editor/issues/672
tickets.
However along with the contextmenu 1 more dialog is visible.
Can we disable that dialog?

I ahve added screen shot for the reference
![contextmenu](https://cloud.githubusercontent.com/assets/22740015/22294848/d65dc852-e33a-11e6-9f64-2d9b49e42885.png)

**Comment by julien** [comment]
Hi @sharmamahesh,

Could you share the configuration you're using please?

Have you tried changing the value of this http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-scayt_moreSuggestions option?

Thanks

**Comment by jbalsas** [comment]
Hey @sharmamahesh, that is part of the plugin. You can pay to get the ads removed, or use it for free with the ads. This has nothing to do with us, and there's nothing we can do about it.
