### ISSUE TITLE
Alloy Editor - Inconsistent behavior of link functionality

### ISSUE THREAD

**Issue by Manju056** [liferay/alloy-editor#704]
Hi,

I am getting issue for Link functionality of alloy editor which are as follows:

1. Sometimes when we add link to a text and save it, it gets saved as normal text without link.

2. Also sometimes link does not get added to a text and it throws an exception on click of tick icon (confirm option). The screenshot of error is attached below. 

This behavior is not consistent and occurs when we perform adding link operation several times.
Issue is not browser specific.

-------------------------------------------------------------------------------------------------------------
Screenshot of Exception for 2nd Issue on developer tool console of Chrome browser

![alloyeditorexception](https://cloud.githubusercontent.com/assets/26568378/24142421/7e30d89e-0e4c-11e7-8541-5d32623ad877.png)

**Comment by ipeychev** [comment]
Hey @Manju056,

Thanks for the report. We will have to be able to reproduce it, otherwise we can't fix it. Also, does it happen on a specific browser only?

Thanks,

**Comment by Manju056** [comment]
Hi @ipeychev ,

This issue is not browser specific and also this behavior is not consistent. It is reproducible when I perform add link operation several times.

Thanks,

**Comment by sharmamahesh** [comment]
Any update on this issue?

**Comment by sharmamahesh** [comment]
I have created demo for this issue.
Please download the demo zip from https://www.sendspace.com/file/u1qzht

I am using Chrome browser. Issue occurs when spellcheck is enabled.
I have added screen shots as well.
![consoleerror](https://cloud.githubusercontent.com/assets/22740015/25040793/2af0fcdc-2129-11e7-8546-25b26683aeb6.png)
![insertinglinkerror](https://cloud.githubusercontent.com/assets/22740015/25040794/2afd17b0-2129-11e7-9165-66ca8cc8c75e.png)

**Comment by sharmamahesh** [comment]
Note: If I typed word having wrong spelling and then try to insert link then it causes the issue.

**Comment by sharmamahesh** [comment]
Any update on this issue?

**Comment by sharmamahesh** [comment]
Any update on this issue?

**Comment by sharmamahesh** [comment]
Please update on this ticket as i am stuck and not able to proceed.

**Comment by jbalsas** [comment]
Hey @sharmamahesh, we'll take a look at this next. 

When you say you have spellcheck enabled, is it the CKEditor plugin, or the browser spellcheck?

@antoniopol06, can you investigate?

**Comment by antoniopol06** [comment]
Ok @jbalsas , I will take a look this issue.

**Comment by sharmamahesh** [comment]
Hey @jbalsas, I am using CKEditor plugin.
I have created a demo as well download the demo zip from https://www.sendspace.com/file/u1qzht

**Comment by sharmamahesh** [comment]
Hey @antoniopol06 , any update on this issue?

**Comment by antoniopol06** [comment]
Hi @sharmamahesh ! I am working on this issue.

**Comment by antoniopol06** [comment]
Hi @sharmamahesh !

As you said before, it is problem from scayt plugin. You need to set this property _scayt_inlineModeImmediateMarkup_ to true. Because if this property is false, when editor loses its focus, scayt will be destroyed and link (and other actions as bold, italic) loses element that was generated by scayt plugin and the action will fail.

The config, that you use in the demo zip, should be like:
```
AlloyEditor.editable('editor', {
      scayt_autoStartup: true,
      scayt_inlineModeImmediateMarkup: true,
             //extraPlugins: AlloyEditor.Core.ATTRS.extraPlugins.value + ',ae_richcombobridge,scayt,menubutton,menu,panel,floatpanel',
			extraPlugins: AlloyEditor.Core.ATTRS.extraPlugins.value + ',ae_buttonbridge,undo,find,pastetext,specialchar,smiley,wsc,ae_richcombobridge,font,scayt,contextmenu,menubutton,menu,panel,floatpanel',

            toolbars: {
                add: {
                    buttons: ['image', 'table'],
                    tabIndex: 2
                },
                styles: {
                    selections: [
                        {
                            name: 'link',
                            buttons: ['linkEdit'],
                            test: AlloyEditor.SelectionTest.link
                        },
                        {
                            name: 'image',
                            buttons: ['imageLeft', 'imageRight'],
                            test: AlloyEditor.SelectionTest.image
                        },
                        {
                            name: 'text',
							 buttons: ['styles','bold', 'italic', 'underline', 'link','image','strike','paragraphLeft','paragraphCenter','paragraphRight','paragraphJustify','subscript','superscript','ol','ul','indentBlock', 'outdentBlock','table','hline','code','quote','removeFormat','Font','FontSize','Undo','Redo','Find','PasteText','Smiley','marquee','scayt'],
							 getArrowBoxClasses: AlloyEditor.SelectionGetArrowBoxClasses.text,
                            setPosition: AlloyEditor.SelectionSetPosition.text,
                            test: AlloyEditor.SelectionTest.text
                        },
						 {
                            name: 'table',
                            buttons: ['tableRow', 'tableColumn', 'tableCell', 'tableRemove'],
                            getArrowBoxClasses: AlloyEditor.SelectionGetArrowBoxClasses.table,
                            setPosition: AlloyEditor.SelectionSetPosition.table,
                            test: AlloyEditor.SelectionTest.table
                        }],
                    tabIndex: 1
                }
            }
 });

```


Let me know if you have any question about that.

Thanks.

**Comment by sharmamahesh** [comment]
Thanks  @antoniopol06 , Its working now.
