### ISSUE TITLE
Crowdin setup

### ISSUE THREAD

**Issue by antoniopol06** [liferay/alloy-editor#705]
[Crowdin](http://www.crowdin.com) app is a localization management platform that allows us:

- Define terms:
-- Upload files
-- Adding strings through the app
- Github integration (Select file or files base that contain the strings to translate). You can force sync or every 10 minutes crowd sends PR, or, adding new commits to PR that exists if there are new changes.
- Translate engines
-- Google (token required)
-- Microsoft (token required)
-- Yandex (free)
- Approvement system. You can revert changes to recover the previous.
- Words can be marked as not translate (using {})
- Define format of the files when its will be exported
- Good documentation

**Comment by jbalsas** [comment]
After analyzing both [POEditor](poeditor.com) and [Crowdin](https://crowdin.com), we've decided (as well as other teams) to go with the latter instead.

@antoniopol06, could you expand the issue to reflect your findings? 

Thanks!

**Comment by jbalsas** [comment]
Closing for now. Will reopen when the infrastructure for this is more clear :(
