### ISSUE TITLE
Http protocol is appended to the links even if "appendProtocol" is false in the config

### ISSUE THREAD

**Issue by ambrinchaudhary** [liferay/alloy-editor#710]
This is a bug we find in portal: https://issues.liferay.com/browse/LPS-71575

Even if "appendProtocol" is passed as "false" in the editor config, when a link is created with some text like "test", it appends the "http://" protocol to it, so the result is "http://test". 

But if you update the link and remove the protocol, it does not change, and we can have successfully the link "test" (in Creole this is a valid link and is translated to [[test]])

**Comment by jbalsas** [comment]
Hey @ambrinchaudhary, can you add a reproduction case for this so we can test it?

**Comment by jbalsas** [comment]
Have you tried this?

```
var editor2 = AlloyEditor.editable('editable', {
    buttonCfg: {
        link: {
            appendProtocol: false
        }
}
            });
```

**Comment by antoniopol06** [comment]
It was verified that it works with the following config:
````
var editor2 = AlloyEditor.editable('editable', {
    buttonCfg: {
        link: {
            appendProtocol: false
        },
        linkEdit: {
           appendProtocol: false
        }
    }
});
````
