### ISSUE TITLE
Error while rendering on the fly : Angular 2

### ISSUE THREAD

**Issue by madhudskumar** [liferay/alloy-editor#712]
While using with angular 2 
![image](https://cloud.githubusercontent.com/assets/8987882/24540228/dcbe4822-160f-11e7-9adc-6937ca271c12.png)

The instance I render my data and then call edit
![image](https://cloud.githubusercontent.com/assets/8987882/24540252/f624379a-160f-11e7-9a9a-e373c0d2fe69.png)
on the above div, the content flashes and immediately gets replaced with and empty editable div.
does this mean the contents should be pre-rendered as proposed to use on the website or am I doing something wrong? 
please help.

**Comment by ipeychev** [comment]
Hello,

First of all, let's comment this code  `new alloyEditor.editable(...);`. Have you wrapped the AlloyEditor and created your own class on top of it?

It should be OK to add content dynamically and then to create the instance of AlloyEditor. Why it is being replaced with an empty div, I cannot guess following the explanation you gave. I can imagine at least two reasons, but we will have to debug to verify.
Let's narrow the things down. Could you try to do the following: create AlloyEditor instance in advance, retrieve the data as you do now and add it to the content via AlloyEditor's API. Something like:
```
// 1. Move creating of AlloyEditor instance somewhere in the constructor:
let ae = new alloyEditor.editable(...);

// 2. Instead this.data = res, assign the data via the API
ae.get('nativeEditor').setData(res);
```

Let's see then. If the editable div renders only once, this should work.

**Comment by madhudskumar** [comment]
Hello,
Solution works. Thank you 💯
