### ISSUE TITLE
Resize images on IE 11 does not work 

### ISSUE THREAD

**Issue by antoniopol06** [liferay/alloy-editor#716]
Resize images on IE 11 works by default (AlloyEditor has ae_dragresize plugin as default) but if you create an AlloyEditor instance with the following config will not work.
````
var content = new AlloyEditor.editable('myContent', {extraPlugins: 'ae_dragresize'})
````

**Comment by duracell80** [comment]
This also ...
https://github.com/liferay/alloy-editor/issues/901

Image Width Is Being Set Differently Between Browsers Causing IE Resize Failing
