### ISSUE TITLE
oembed net::ERR_INSECURE_RESPONSE

### ISSUE THREAD

**Issue by macandcheese** [liferay/alloy-editor#732]
Hi - I'm using Alloy editor through Contentful editor UI - https://github.com/contentful/extensions/tree/master/samples/alloy-editor

I've changed to using the newest version of the js and css, and it works fine through Contentful. However, pasting in any embedded media (youtube link) generates a console error, and the item is empty in the editor. The GET for https://alloy.iframe.ly/api/oembed?url="link" throws a net::ERR_INSECURE_RESPONSE. Contentful's UI is served through https://, not sure what would cause this?

**Comment by ipeychev** [comment]
Hello,

The certificate if this site is invalid. It is issued to "iframe.ly", but the request is for "alloy.iframe.ly". They either have to provide a wildcard certificate or to issue another one - to "alloy.iframe.ly".

Thanks,

**Comment by jbalsas** [comment]
Hey @macandcheese, take into account as well that url is meant for demo'ing purposes only as stated [here](https://github.com/liferay/alloy-editor/blob/master/src/plugins/embed.js#L19-L26). For real usage, you should be contacting iframe.ly to get a custom domain and proper pricing.

**Comment by jbalsas** [comment]
Hey @macandcheese, could you try the following?

```javascript
const editor = AlloyEditor.editable('content', {
    embedUrlTemplate: 'http://alloy.iframe.ly/api/oembed?url={url}&callback={callback}'
})._editor
```

Again, please take into account that **this endpoint is for demo purposes only. Iframe.ly will restrict access per domain if abused**.

**Comment by jbalsas** [comment]
I've added this to the `1.4.1.` milestone demo so we switch the url to `http` by default.
