### ISSUE TITLE
Cannot read property 'replace' of undefined when Language is en-gb

### ISSUE THREAD

**Issue by antoniopol06** [liferay/alloy-editor#733]
This error occurs because of #702 does not take any language by default. Then AlloyEditor has some own keys to translate it and if object, in this case [en-gb.json](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/assets/lang/en-gb.json) is empty. AlloyEditor.Strings will not have these strings and CKEDITOR.replace will fail.

**Comment by JiriZidek** [comment]
In 1.4.1 I still get this bug in various situations - focus/defocus, writing a letter:

> alloy-editor-no-react.js:337 Uncaught TypeError: Cannot read property 'replace' of undefined
>     at new CKEDITOR.template (alloy-editor-no-react.js:337)
>     at Constructor._getAriaUpdateTemplate (alloy-editor-no-react.js:16323)
>     at Constructor._getAvailableToolbarsMessage (alloy-editor-no-react.js:16369)
>     at Constructor.componentDidUpdate (alloy-editor-no-react.js:16305)
>     at Constructor.chainedFunction [as componentDidUpdate] (react.js:4907)
>     at CallbackQueue.notifyAll (react.js:869)
>     at ReactReconcileTransaction.close (react.js:12870)
>     at ReactReconcileTransaction.closeAll (react.js:15699)
>     at ReactReconcileTransaction.perform (react.js:15646)
>     at ReactUpdatesFlushTransaction.perform (react.js:15633)

Is there something missing in localisation ?

**Comment by jbalsas** [comment]
Hey @JiriZidek, can you identify your browser's locale so we can investigate?

**Comment by JiriZidek** [comment]
Chrome via JS:
navigator.language == "cs"
navigator.userLanguage == undefined

Chrome UA:
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

Chrome in http header:
Accept-Language:cs-CZ,cs;q=0.8

IE11 via JS:
navigator.language == undefined
navigator.userLanguage == "cs-CZ"

Anything more ?
