### ISSUE TITLE
Strange symbols on toolbar buttons

### ISSUE THREAD

**Issue by derekjwhitten** [liferay/alloy-editor#735]
I have installed alloy editor and it's working fine (ie content becomes editable and I can click on toolbar buttons to successfully apply formatting) however the icons are not displaying so I see strange symbols on the toolbar (see screenshot below).

![toolbar](https://cloud.githubusercontent.com/assets/5736382/25778706/a93b2ca2-3349-11e7-9d6e-25576e1a3d8a.PNG)

There are no errors in the console. Has anyone encountered this before? Any ideas on how to solve?

**Comment by derekjwhitten** [comment]
After spending hours trying to debug this, I just rebuilt the page from scratch and it's working. I must have had a typo somewhere..Closing this issue.

**Comment by ipeychev** [comment]
It should work with the non-minified skin too, I don't see why not - the other is just not minified?
