### ISSUE TITLE
Does alloyeditor work on non-PC devices? 

### ISSUE THREAD

**Issue by bvn13** [liferay/alloy-editor#736]
I.e. live demo does not work on Android phone.

**Comment by ipeychev** [comment]
No, it doesn't. The engine we use under the hood - CKEditor doesn't work there. Maybe in v5 it will and we will be able to fix that too.

**Comment by duracell80** [comment]
It's a year on from this being raised as a concern. Are there any significant movements towards version 5 at this time?

**Comment by wincent** [comment]
#618 is the ticket about v5.

#22 is the oldest open ticket I can find for tracking mobile support, so I'm going to close this one in favor of that one.
