### ISSUE TITLE
ColorButton with Alloy Editor: Cannot read property 'focus' of undefined

### ISSUE THREAD

**Issue by jaffnae** [liferay/alloy-editor#737]
I'm trying to use the colorbutton plugin. I have added all the dependencies as [described in the documentation](http://alloyeditor.com/guides/ckeditor_plugins/ui_panel_menu_button/). I can see the Text Colour icon show up in the tool bar and am able to edit the font colours. However as soon as I edit the color, an error gets thrown in my console: "Uncaught TypeError: Cannot read property 'focus' of undefined"

The error is quite strange because I basically minimised the code to a stand-alone page which contains no additional code other than what's been specified on the page I linked above. I've also ensured I have all the dependencies in the Plugin folder (floatpanel, panel, button, panelbutton and colorbutton).

Here's the stand-alone page that I'm hosting specifically on Heroku. You can highlight a word and change it's color (and then observe the JS error getting thrown in the inspector): https://tempapp53.herokuapp.com/

**Comment by jbalsas** [comment]
Thanks a lot @jaffnae, that's extremely useful!!

I've scheduled this issue for our next milestone and will be taking a look shortly.

**Comment by jaffnae** [comment]
Thanks for  that. Can I ask if you have any timelines as to when you'll have more info on this?
