### ISSUE TITLE
Warning: ButtonBold:React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

### ISSUE THREAD

**Issue by tsusini** [liferay/alloy-editor#742]
JavaScript classes are now the preferred way to create components in React.

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass

**Comment by jbalsas** [comment]
Hey @tsusini, thanks for the reminder. We are tracking this in https://github.com/liferay/alloy-editor/issues/479 and will update for the `2.0.0` version of the Editor, which we should hopefully start working in soon.
