### ISSUE TITLE
Disable toolbar animation

### ISSUE THREAD

**Issue by obrienmd** [liferay/alloy-editor#751]
I see an API function in the WidgetPosition class for cancelAnimation, but I'm not sure how I would use it with the most basic Alloy Editor function I currently have in place. Is there a simple way to cancel the animation that occurs when a toolbar pops up or moves?

**Comment by ipeychev** [comment]
Hello,

You may try to disable it from CSS, by playing with the styles [here](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/assets/sass/components/ae-toolbar/structure.scss#L15).

Thanks,

**Comment by obrienmd** [comment]
Thanks! One of my teammates figured that out for me about 30 seconds after I asked the question :)

**Comment by czechdave** [comment]
Hi, this disables the transition of the element's position but is there a way to disable the position change altogether? (keep `top`/`left` style properties unchanged and centered over the text selection)

**Comment by ipeychev** [comment]
The Styles toolbar is designed to be always centered. Here it how it works:
1. You make a selection, then it appears centered.
2. You apply some styling to the selection, for example `h1`, or `bold`. Then it re-centers.

There is no way currently OOTB to prevent that and I don't see why it should be prevented by default. If you make an <h1> from a selection, it will move on top or on left and toolbar will appear far away from the selection. Try to select a normal text and then choose "Heading 1" to see what I mean.

**Comment by czechdave** [comment]
When you move your mouse to the edge of the editor area the toolbar jumps side to side for no reason. Here's a gif of what I mean:
https://monosnap.com/file/oSZSBCs1sPf8ginccSF9WuxAl5tkbn

**Comment by duracell80** [comment]
Can we just do this ...

![why-so-complex-keep-the-bar-static](https://user-images.githubusercontent.com/18121278/48498240-66110880-e7fb-11e8-9567-d854a7a8c188.gif)
