### ISSUE TITLE
Upgrade React

### ISSUE THREAD

**Issue by ipeychev** [liferay/alloy-editor#753]
The current version of React is outdated. We have to upgrade it to the latest one - 15.5.4

**Comment by JiriZidek** [comment]
These two warnings on pages with alloyeditor seem to be related to this problem:

> Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
> print
> Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
> print

**Comment by jbalsas** [comment]
This is being handled as #770

**Comment by jbalsas** [comment]
We actually decided not to upgrade it for a minor version because of how we are currently building our bundled version, which will suffer some behaviour changes. We'll leave that for a `2.0.0` that should be coming in soon.

**Comment by ctowler157** [comment]
Is the upgraded version going to be 15.5.4 or is it going to be v16 or greater?

**Comment by jbalsas** [comment]
We need to make significant changes to the bundle build process, so we will update to the latest release once we get to it.

**Comment by jbalsas** [comment]
Branch in progress in Hey @Minivera, @josemontiel, sorry for the late response. As it was pointed out, `AlloyEditor@1.5.1` just tried to find a way to be compatible with `React-16` without introducing backwards incompatible changes.

Indeed, to make it work, the developer needs to add the `prop-types` package either in the build process or as a global script.

We're working on a `2.0` version that should remove this dependency by directly upgrading to React16: https://github.com/liferay/alloy-editor/tree/feature/alloyeditor_2.0

**Comment by Tzaphkiel** [comment]
I see that the upgrade of React is not planned for a minor release but rather for the `2.0.0`.

Is there any timeline as to when it will be available: I see the last commit on Feb this year...?

I would like to upgrade to React 16.x.x to benefit from the numerous enhancements and code size reduction !

**Comment by matuzalemsteles** [comment]
hey @Tzaphkiel, You can use version 16.x of React with AlloyEditor currently in version 1.x, see https://github.com/liferay/alloy-editor/issues/808.

See an example using version 16.3.1: https://github.com/matuzalemsteles/alloyeditor-react

**Comment by wincent** [comment]
Closing this as the 2.x-develop branch is now on v16.7.0 (and soon on v16.8.0).
