### ISSUE TITLE
Alloy editor text selection is very faint and barely visible

### ISSUE THREAD

**Issue by sharmamahesh** [liferay/alloy-editor#756]
Hi,
Can we change the color of selection text.

**Comment by ipeychev** [comment]
Yes. In fact, we already do this. Please see [here](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection) how.

**Comment by sharmamahesh** [comment]
Yes but we need to change the selection color when we select any text only on Alloy editor.

**Comment by ipeychev** [comment]
Then apply it to the editable area on your page only?

**Comment by sharmamahesh** [comment]
I am using
 .cke_textarea_inline{overflow: auto; border: 1px solid gray;-webkit-appearance: textfield;}
can we add style for seection test here?

**Comment by ipeychev** [comment]
Yes.

**Comment by sharmamahesh** [comment]
I am adding this style to .cke_textarea_inline as 
.cke_textarea_inline{overflow: auto;border: 1px solid gray;-webkit-appearance: textfield;
	::selection {color: gold;background: red;} 
}
But the selection color is not getting changed.

**Comment by duracell80** [comment]
Is it possible to have that selection styling removed by default? Liferay DXP also does this.

![worse-in-dxp](https://user-images.githubusercontent.com/18121278/39723863-af58924a-520c-11e8-9114-ea79a2db77bc.JPG)

**Accessibility concerns**

It is advisable to not override the operating system's default selected text style for purely aesthetic reasons, especially if the user has customized them to suit their needs.
