### ISSUE TITLE
Partial Read Only Mode (for certain parts of the content)

### ISSUE THREAD

**Issue by jaffnae** [liferay/alloy-editor#757]
Hi,
I would like to make parts of the editor read only, while other parts to be editable. 
If I have the following markup:
```
<div id = "editable">
    <div class="readOnly">Don't edit me</div>
    <div class="readWrite">Edit me</div>
</div>
```

When I do `AlloyEditor.editable('editable', config);`  is it possible to make "readWrite" div to be editable but the "readOnly" div to be read-only?

I know there's `nativeEditor.setReadOnly(true);`  but it seems this will prevent editing to the entire section - I am after somethign partial.

**Comment by ipeychev** [comment]
Hey @jaffnae,

Yes, you will have to create some Widgets following CKEditor's API for that. They work fine in AlloyEditor.

Thanks,

**Comment by ipeychev** [comment]
Probably your next question will be how to register the custom Widget in AlloyEditor once you create it and add it to CKEditor's engine. Here is how - please set in the config of AlloyEditor the following:
```javascript
extraPlugins:
    AlloyEditor.Core.ATTRS.extraPlugins.value +
      ',ae_uibridge,ae_buttonbridge,undo,magicline,' +
      plugins.join(','),
```

where `plugins` is the array of your own custom widgets, added to CKEDdtor's engine.

Thanks,
