### ISSUE TITLE
Is Merge Cells broken?

### ISSUE THREAD

**Issue by andrerom** [liferay/alloy-editor#759]
Besides issue in #758 about not possible to select several cells in other browsers then Firefox, Merge cells seem to do nothing in any browsers. So given this issue and the once in #758 it might better be removed for the time.

------

Browsers:
- Safari 10.1
- Chrome 59
- Firefox 54

**Comment by wincent** [comment]
"Merge Cells" works in Firefox (just tested it now), but as you pointed out in #758, you can't select multiple cells in Chrome, which means it will have no effect. As a work around, "Merge Right", "Merge Down" do work. I'm going to close this one and keep #758 open.
