### ISSUE TITLE
On click, Twitter button should create a link so the user will be able to tweet directly

### ISSUE THREAD

**Issue by ambrinchaudhary** [liferay/alloy-editor#76]
Currently, when there is selection and user has clicked on Tweet button, editor offers him to tweet the selected content.
We have to change this behavior and instead to tweet, clicking on Twitter button should generate a special link from the selection. After that, as soon as user clicked on this link, the editor will offer him to tweet this content.
Here is an example: http://blog.invisionapp.com/inside-design-team-saatchi-saatchi-la/

**Comment by duracell80** [comment]
This doesn't work when the link already exists, let's say if you've already added a link to the tweet but haven't used the Twitter icon to do it. The link must be deleted and the text re-selected to enter the link again.

This would have more value if it was a link to "external website" that opens in a new tab.
![improve-this](https://user-images.githubusercontent.com/18121278/39719532-2368fb38-51ff-11e8-9c2b-632f21b404ed.gif)
