### ISSUE TITLE
Markdown realtime preview

### ISSUE THREAD

**Issue by javisperez** [liferay/alloy-editor#760]
Hello :)

Im working on some markdown editor with realtime inline preview (something like Dropbox Paper), the idea is that if I type something like \*\*Hello World\*\*  the text automatically get transformed to **Hello World** inline, not in any preview screen, and I'm wondering if that behavior is achievable with this editor, as seem pretty solid and customizable.

Thank you for your time.

**Comment by ipeychev** [comment]
Hello,

Yes, it is. You may use [this](http://ckeditor.com/addon/markdown) plugin, or write your own. If you want to use the one from CKEditor, download the zip file from their site and use the instructions [here](http://alloyeditor.com/guides/how_to_use_ckeditor_plugins/) to include it to AlloyEditor.

Thanks,

**Comment by javisperez** [comment]
Hey, @ipeychev thank you for your reply and for the link reference!

I haven't tried it, but that plugin doesn't seem like what I need :( what I'm needing is to transform the markdown in real time, without a "preview" button, like this: http://g.recordit.co/ysMBgHfsbI.gif I know it is hard (been trying for a while now).

Do you think it's actually possible to do with Alloy Editor?

**Comment by ipeychev** [comment]
I haven't tried, but it should be. There is API (coming from CKEditor's engine) for retrieving the content, setting the content, manipulating the selection, etc. In fact, this plugin does something in this direction. To see how does it work, please go to the [demo](http://alloyeditor.com/demo/) page and type some link, for example "http://liferay.com", then press Space or Enter. You will see this text turning into a link.
