### ISSUE TITLE
iOS: Not Able To Add Hyperlink

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#767]
In Alloy Editor on desktop/laptop it's pretty nice to be able to select a word to then make it a link or change the style and alignment of it. However running under mobile, iOS in particular double tapping a word to make the word selected in order to pull up that Alloy Menu invokes the inbuilt black iOS tooltip menu that then contains the iOS text actions [ Bold, Underline, Italic ].

This then wipes out the ability for mobile users using Alloy editor to add a hyperlink to their text. The source view is not that great on mobile either and even users who know HTML would struggle to input a hyperlink on these iOS devices. I tested with iPhone 6s, however it could be common to all iOS devices as well as Android (Marshmallow will allow the user to double tap a word to copy/paste and perform a web search of that term). 

![iphone-alloy-double-tap](https://user-images.githubusercontent.com/18121278/30496694-d5c13b76-9a15-11e7-839f-ed377836d51a.jpg)
![iphone-alloy-double-tap-2](https://user-images.githubusercontent.com/18121278/30497224-aa3363ec-9a17-11e7-9012-63e41eeec69e.jpg)

I have since found that when double tapping a word to select it, then hitting the home button and then going back into Safari, the correct menu does appear.

Steps:
1) Using Safari > Load up a screen with the editor on it
2) Type a word
3) Double Tap that word to select it
4) Note the iOS menu appears
5) Hit the home button (if you have a physical home button)
6) Now go back into Safari
7 The correct menu should now be visible however it may not always be tap-able.

**Comment by duracell80** [comment]
Has there been any movement here on making the UI of Alloy Editor work on iOS phone only devices?

**Comment by wincent** [comment]
Doing some "spring cleaning" by closing issues that were opened in 2017 — much has changed since then and there have been many releases, so there is a risk that these older issues have grown very stale and are very unlikely to be acted upon. Please feel free to commend and we can look at re-opening on a case-by-case basis.
