### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by mmwtsn** [liferay/alloy-editor#769]
There are links in the [README currently](https://github.com/liferay/alloy-editor/blob/a56c8feeaddf75e61a1172e8ac36db4cfa3e6281/README.md) for a [demo](https://alloyeditor.com/demo/) and a [screencast](https://alloyeditor.com/features/) that both 404.

**Comment by jbalsas** [comment]
Thanks @mmwtsn! I've fixed the links. The demo is currently embedded in the [landing page](https://alloyeditor.com/) and the [features](https://alloyeditor.com/docs/features/) page had been moved.
