### ISSUE TITLE
Refactor code to determine when to display placeholder text

### ISSUE THREAD

**Issue by vbence86** [liferay/alloy-editor#792]
## Prelude
Fixing issue/768 raised concerns whether there might be a more consolidated solution to determine when the editable content is regarded empty and when the predefined placeholder text must be shown. 

For further information: 
https://github.com/liferay/alloy-editor/pull/789

## User story
As a developer,
I'd like to refactor the logic that determines whether the editable content is empty and the placeholder text should be displayed
so that we can eliminate potential technical debt building up around this. 

## Acceptance criteria
- the logic is flexible to various combinations of non visual elements
- as opposed to how it is implemented now, the logic doesn't contain any hard-coded bits with respect to DOM elements such as `<p>` or `<h1>`.
- All related test cases are aligned to the refactored code
- All tests pass
- when the editable content takes in only non visual elements the `data-placeholder` attribute must be shown. 
- non visual elements are `<br>` and inline elements with no content such as `<span>`, `<p>`, `<strong>`, `<b>`, `<i>`, `<h1>`, `<h2>`, `<h3>`, `<h4>`, `<h5>`.

## BDD scenarios
GIVEN the editable content is unfocused
WHEN it incorporates only whitespace characters or non visual DOM elements
THEN the predefined placeholder text in `data-placeholder` attribute must be shown.

**Comment by wincent** [comment]
Doing some "spring cleaning" by closing issues that were opened in 2017 — much has changed since then and there have been many releases, so there is a risk that these older issues have grown very stale and are very unlikely to be acted upon. Please feel free to commend and we can look at re-opening on a case-by-case basis.
