### ISSUE TITLE
Prevent the button instance to be destroyed after selecting items from an item selector

### ISSUE THREAD

**Issue by jrodryb** [liferay/alloy-editor#796]
Hi, I am facing a problem while trying to select a liferay document from an input element inside an alloyeditor button instance (just like in button-link-edit.jsx but witho). 

WHAT I am trying to do is to select multiple liferay images to populate their urls into several input elements inside the button instance, in order to make an image gallery from that selected images.
 
 THE PROBLEM is that when I select an image from the item selector popup, the button instance is destroyed, so I cannot populate the data related whit the just selected image and due to this I cannot continue selecting more images to create the gallery. Occurs the same in button-link-edit.jsx, but in that case only a value is needed to create a link so it's ok that the instance will be updated and then destroyed. I don't know how I can control the mouse events when clicking outside the button instance to be ignored or something like that.

Thanks and sorry for my english :)

**Comment by jbalsas** [comment]
Hey @jrodryb, thanks for the detail description of the problem. However, it is very hard to try and diagnose the issue correctly without some kind of test or sample demo of your code. 

Since it also intersects (I assume) with Liferay Portal integration code, we would need to see some code and/or have some out of the box reproduction steps before we can investigate.

Could you?
- Provide a code sample and instructions to deploy it
- Add the minimal set of reproduction steps
- Record a gif with the problem that you're having?

Thanks!

**Comment by jrodryb** [comment]
Thanks @jbalsas! I forgot to attach the images to reproduce it.. 
First, in the following gif we can see the functionality of the Link browser button that comes out of the box in Liferay DXP. When I select the liferay logo from the item selector popup, just after I click in the "Add" button in the footer, the link is updated and the alloyeditor Link browser instance is removed. It is what I am trying to avoid but for the case of the Link browser it's ok.

![ootb link browser](https://user-images.githubusercontent.com/12874478/32862867-cd58e49c-ca59-11e7-86e3-058e9469bf92.gif)

On the other hand, in the next gif I show you the desired behavior in one of the buttons that we are developing. As the final result is to build an image gallery, it is necessary to be able to choose several images without the button instance of alloyeditor being deleted when an image is selected by clicking on the "Add" button (that is the key point of my question), until you manually click on the confirmation icon.

![custom image gallery](https://user-images.githubusercontent.com/12874478/32863890-5cbce7de-ca5d-11e7-8fe6-9b1eb293f683.gif)

To ensure that the instance is not deleted when it loses focus, I have been looking in the source code and I have identified where is the logic to show / hide the UI of the buttons (_setUIHidden() method of AlloyEditor.UI), adding there a piece of code as a workaround:

```
(function () {
    ...
    _setUIHidden: function _setUIHidden(target) {
        var domNode = ReactDOM.findDOMNode(this);

        //WORKAROUND START ----------------------------------------------------
        //Prevent gallery button instance to be hidden after selecting an image from item selector
        var galleryContainer = document.getElementById('gallery-edit-container');
        var hasGalleryContainer = domNode && domNode.contains(galleryContainer);
        if (hasGalleryContainer) {
            var iconOk = galleryContainer.querySelectorAll('.ae-icon-ok')[0];
            var iconBin = galleryContainer.querySelectorAll('.ae-icon-bin')[0];
            //Force show except when we click on confirmation or bin buttons
            var forceShow = ((target !== iconOk) && (target !== iconBin));
            if (forceShow) {
                return;
            }
        }
        //WORKAROUND END ----------------------------------------------------
            
        if (domNode) {
            ...
        }
    }
    ...
    AlloyEditor.UI = UI;
})();

```

I would like to know if there is a better way to do this than overriding a core function with this specific behaviour and to be extended to other buttons.

I hope that is clear! :) 
Thanks!!

**Comment by wincent** [comment]
By way of "spring cleaning", I'm closing issues tagged with "question" that haven't had any activity in > 12 months. There have been quite a few releases since then and much has changed, and these "stale" issues are extremely unlikely to be acted on. Please feel free to comment and we can re-open on a case-by-case basis.
