### ISSUE TITLE
Update 1.x CKEditor to 4.7?

### ISSUE THREAD

**Issue by andrerom** [liferay/alloy-editor#797]
We're experiencing an issue in Chrome where CKEditor 4.5 and 4.6 upon setting focus to editor will scroll to the top of the page. So wondering if it would be easy enough to update to 4.7 for 1.x branch.

It fixes among other things this issue, which is also reported in #743 and #676:
https://github.com/ckeditor/ckeditor-dev/blame/release/4.7.x/core/editable.js#L90-L96

**Comment by jbalsas** [comment]
Hey @andrerom, we'll look into it.

If I remember correctly, CKEditor 4.6 introduced a massive breaking change in how plugins are handled, which resulted in thrown errors when some plugins where not enabled. This would prevent us from easily removing plugins such as `context-menu` and many others that we need to take away for our UI to take control

I'll double-check soon to see if it is feasible or not. Hopefully we can find a way.

**Comment by andrerom** [comment]
>  if I remember correctly, CKEditor 4.6 introduced a massive 

Ok, but master, which you are about to release 1.5 from, seems to already use 4.6, or are you saying 4.7 introduced massive plugin breaking change?

**Comment by jbalsas** [comment]
Might be `4.7.0`, yeah 😂

**Comment by jbalsas** [comment]
It's probable that we won't be able to upgrade until `4.9.0` unless we find a workaround for the issue I mentioned. See https://github.com/liferay/alloy-editor/pull/801 and https://github.com/ckeditor/ckeditor-dev/issues/654

We'll take a look to see if there's some valid workaround, but CKEditor is not making it easy in this case :(

**Comment by andrerom** [comment]
Ok, pity, but good to know, at least 1.5 comes with 4.6, and in the meantime we have worked around the scrolling issue on our side in similar way as done in CKEditor.

**Comment by jbalsas** [comment]
Looks like we might be able to get this in... I've merged into `develop` so this should go out with `1.6.0` by the end of next week!

**Comment by andrerom** [comment]
Thanks a lot @jbalsas, great news :)
