### ISSUE TITLE
With CKEditor 5 still in alpha, should there be a milestone with React & CKEditor 4 update?

### ISSUE THREAD

**Issue by andrerom** [liferay/alloy-editor#798]
As in, should there be an intermediate milestone for Alloy before the major version is stable?

**Comment by jbalsas** [comment]
Hey @andrerom I'm about to release `1.5.0` with support for React16 (still bundling old react). There might be more intermediate as well, depends on how things evolve and whether we can to make changes in a backwards compatible manner or not :)

I'll answer about the CKEditor 4 update in https://github.com/liferay/alloy-editor/issues/797

**Comment by andrerom** [comment]
Thas is great, thanks :)
