### ISSUE TITLE
IE11 image resize not keeping original image ratio

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#816]
In IE the drag handles on an image to resize it don't focus. The handles briefly appear then go away (this is affecting Liferay Blogs too). However a black box appears. This box when dragged fails to keep the original image ratio causing image distortion.

# IE 11 Resize: 
![ie-resize](https://user-images.githubusercontent.com/18121278/39710752-5392adca-51e3-11e8-8bcc-af0472b5f096.gif)

# Chrome Resize: 
![chrome-resize](https://user-images.githubusercontent.com/18121278/39710759-57a8575c-51e3-11e8-8d1e-edf43648f558.gif)

**Comment by markocikos** [comment]
Closing, we no longer support IE.
