### ISSUE TITLE
Blockquote is missing as a text style

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#819]
As a user I would like to make my text selection a blockquote so that I can better use the "cite" style already provided in the drop down menu. CK Editor allows the text selection to be a blockquote. This should be enabled by default in AE.

# CK:
![can-with-ck](https://user-images.githubusercontent.com/18121278/39718352-a601a67a-51fb-11e8-90fe-0ec9b53e02b3.gif)

**Comment by jbalsas** [comment]
Hey @duracell80, thanks for reporting. I'm closing this in favour of https://github.com/liferay/alloy-editor/issues/831 where we can discuss more about the general default configuration, as the editor already has this feature: https://alloyeditor.com/docs/features/quote.html
