### ISSUE TITLE
Superscript and Subscript is missing when selecting text

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#821]
As a user I would like to be able to make use of subscript and superscript text formatting options. For example I might be entering procedure information that requires mathematical units to be subscript or dates to be superscript. This should be provided as default configuration.

**Comment by jbalsas** [comment]
Hey @duracell80, thanks for reporting. I'm closing this in favour of https://github.com/liferay/alloy-editor/issues/831 where we can discuss more about the general default configuration, as the editor already has this feature: https://alloyeditor.com/docs/features/superscript.html, https://alloyeditor.com/docs/features/subscript.html
