### ISSUE TITLE
Strikethrough is missing when selecting text

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#822]
As a user I wish to have my editor by default allow the use of the strikethrough text formatting option. CK Editor allows this by default.

# CK:
![can-with-ck](https://user-images.githubusercontent.com/18121278/39719016-9154135a-51fd-11e8-94fa-639a6576dee8.gif)

**Comment by jbalsas** [comment]
Hey @duracell80, thanks for reporting. I'm closing this in favour of https://github.com/liferay/alloy-editor/issues/831 where we can discuss more about the general default configuration, as the editor already has this feature: https://alloyeditor.com/docs/features/strike.html
