### ISSUE TITLE
Tweet Intent looks to be targeting a slightly incorrect use case

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#826]
![twitter-link-missing-link-back-to-source-site](https://user-images.githubusercontent.com/18121278/39775253-f61d3e9a-52c2-11e8-910c-4719886bea4a.gif)
The twitter icon in the editor is good (though lacking a link back to the source site). However it seems to be targeted at the wrong class of user maybe? Take that there are two kinds of users here:

**Audience:**
1) Content Editor
2) Content Reader

It's the content reader who is most likely the user who should be "selecting text to tweet". The content editor it seems in this instance is getting to decide what part of the article is going to be in the tweet. This would lead to a situation where the content creator/editor would be inserting multiple suggestions to the user to tweet the text needlessly trying to cover every readers interest. The person tweeting may then delete all the text and put in their own.

_This feature should really be on the non-editor side of this page, let the content consumer decide what text they want to have in their own tweet._

The feature that would be helpful to content editors is to tweet intent a persons name as a link to their twitter profile page? In this case I would find it helpful as a content creator to link to Neil Armstrong's twitter page.

**Here's a better use of the icon for editors**
1) Remove the link to wikipedia from Armstrongs name
2) Replace it with a tweet intent that links to his profile page (via asking user for his @handle in the text box)

![better-use-of-tweet-intent](https://user-images.githubusercontent.com/18121278/39776406-5db051fc-52c6-11e8-995a-035c15b8abaa.gif)

**Comment by duracell80** [comment]
Here's what I mean:
https://blog.hubspot.com/marketing/slack-tips

On that page, it's not an editable piece of content. However as a reader I can choose my own text selection to tweet, or send via messenger, or post to facebook.

**Better use case:**
![actual-use-of-tweet-intent-should-be-for-content-readers](https://user-images.githubusercontent.com/18121278/39775801-923af078-52c4-11e8-8337-6b5765c51f1f.gif)

**Comment by jbalsas** [comment]
Hey @duracell80, the twitter button, as confusing as it might be is working as intended. The idea behind it was to allow editors to highlight and prepare the sections in their contents that wanted tweeted in a simple way, helping focus the attention and broadcast on specific messages picked by the editor.

**Comment by wincent** [comment]
By way of "spring cleaning", I'm closing issues tagged with "question" that haven't had any activity in > 12 months. There have been quite a few releases since then and much has changed, and these "stale" issues are extremely unlikely to be acted on. Please feel free to comment and we can re-open on a case-by-case basis.
