### ISSUE TITLE
Better UX: Improve Default Configuration of AE To Include Needed Text Editing Features

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#831]
Currently the editor doesn't seem to be default configured to include all known features. It's much easier to take things away from a configuration file than it is to read and find what the configuration should be.

#821  Super and Subscript is missing
#822  Strike is missing
#819 Quote is missing
Increase / Decrease font size is missing
#838 Linking an image doesn't work correctly in demo / default configuration

#820 For text styles, both color and font selection is not available OOTB and are plugins. This is fine but those plugins should be there defaulted on and fully working with the editor. An editor that can not change text font or color doesn't seem to have value when the base editor its based on can already do that OOTB.

**Comment by duracell80** [comment]
Users will find a way:
https://stackoverflow.com/questions/46564370/how-to-enable-textcolor-fontsize-selection-option-in-wysiwyg-editor-for-web-co

In this case the user enabled font and color by disabling AE:

"I found the configuration to enable the old CKEditor in liferay 7, This might help someone so i am answering my own question. Add below properties in portal-properties file and restart the server."

```
editor.wysiwyg.default=ckeditor
editor.wysiwyg.portal-impl.portlet.ddm.text_html.ftl=ckeditor

```

**Comment by jbalsas** [comment]
Hey @duracell80, AlloyEditor goal was to provide a more streamlined and focused way of editing. The current default configuration was specifically chosen by our UX team for this reason.

All available features are listed in the [Features Section](https://alloyeditor.com/docs/features/) of the editor's site

On Liferay's side, how to change the configuration for the editor's you want is showed in the [Modifying an editor's configuration tutorial](https://dev.liferay.com/en/develop/tutorials/-/knowledge_base/7-0/modifying-an-editors-configuration)

We've never hidden the options to change wysiwyg editors. If for whatever reason another serves better your purposes, please do pick the one that better suits your needs. That's the reason we still (and will in the future) maintain them.

In [Using the Default CKEditor Plugins...](https://dev.liferay.com/en/develop/tutorials/-/knowledge_base/7-0/using-ckeditor-plugins-in-alloyeditor) you can actually find how to enable default CKEditor plugins such as fontsize as well...

**Comment by duracell80** [comment]
I understand the UX direction but I would respectfully and critically advocate for a change of direction away from reducing the feature set of the editor as part of that effort.

A solution would be to use the idea of context ... Simple, Advanced. Default the UI to simple and when as a user I require more features, let me activate them in the UI via a toggle of mode change. Don't dictate what features I do and do not need to have.

Take a car dashboard yes it has to be streamlined and easy to read at a glance, however taking away features to achieve that goal of improving UX can infact harm UX. Does the user really need a fuel gauge, isn't the speed of the car more important? Can't we just have a colored dot instead to space space or even abstract it to a verbal indicator through the smart speaker. Yes it de-clutters the UI but harms the UX.

**Comment by julien** [comment]
Hi @duracell80,

I might be wrong but it seems that this is related to issue #906 and pull request #930.

If this is the case, would you mind closing this issue and continuing our discussion in #906?

Thanks!

**Comment by wincent** [comment]
Closing this one per @julien's suggestion that #906 might be the better place for this.
