### ISSUE TITLE
Bug: Missing Padding When Left Aligning An Image

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#832]
Seen in feature showcase:
https://alloyeditor.com/docs/features/imagealignleft.html

![self-evident-padding-issue](https://user-images.githubusercontent.com/18121278/39835463-d7dac1b8-5395-11e8-9031-a91baf2f5561.gif)

**Comment by duracell80** [comment]
Issue is present in CK also ... (right align is fine and center align not possible)

![issue-present-in-ck-too](https://user-images.githubusercontent.com/18121278/40008356-bb2a85b2-5764-11e8-8359-09770a97be21.JPG)

**Comment by jbalsas** [comment]
Hey @duracell80, we don't consider this as an issue. Both CKEditor and AlloyEditor are trying to introduce minimal markup, so it's easier to style it later without coupling the content to a specific editor logic, behaviour or look and feel.

This helps generate cleaner and more interoperable markup that can be styled however the final user wants.

**Comment by duracell80** [comment]
Could this be addressed in DXP as a concern where the editor remains minimal but DXP improves the editing experience?

I understand the minimal aspect however not having the padding creates a worse UX than having it (the decision is being pre-made that users don't want padding). Users have the word processing experience prior to using these editors to expect padding around images.

Minimal in this situation does not mean easy or intuitive. Want padding? Do it yourself, is terrible UX.

**Comment by duracell80** [comment]
Affects numbered and bulleted lists when images floated left

![affects-ae-native](https://user-images.githubusercontent.com/18121278/41178578-5a2bde82-6b2d-11e8-83dd-6e4b0a145cb1.JPG)

**Comment by wincent** [comment]
By way of "spring cleaning", I'm closing issues tagged with "question" that haven't had any activity in > 12 months. There have been quite a few releases since then and much has changed, and these "stale" issues are extremely unlikely to be acted on. Please feel free to comment and we can re-open on a case-by-case basis.
