### ISSUE TITLE
Can't Link an Image in Demo / Default Configuration

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#838]
Images can't be linked by selecting the image and clicking the "plus icon" to add a link to an image. The image is replaced by the link rather than being wrapped in the link.

![cant-link-an-image-in-demo-ootb](https://user-images.githubusercontent.com/18121278/40006633-77fa8174-5760-11e8-9347-9c2f8e9d0cdf.gif)

**Comment by SpencerWoo** [comment]
Locally I was able to set up hyperlinking an image by

1. Downloading [AlloyEditor 1.5.0 source](https://github.com/liferay/alloy-editor/releases/download/1.5.0/alloy-editor-1.5.0.zip)
2. Modify index.html to import the non-minified version of alloy-editor
`<script src="alloy-editor/alloy-editor-all.js"></script>`
3. Modify alloy-editor-all.js to add 'link' button to [image toolbar](https://github.com/liferay/alloy-editor/blob/master/dist/alloy-editor/alloy-editor-core.js#L7270)
`buttons: ['imageLeft', 'imageCenter', 'imageRight', 'link']`


I believe the plus icon is intended to add / replace content (I can select text and add an image and it replaces the text) and by default hyperlinking an image isn't enabled.

**Comment by jbalsas** [comment]
Hey @duracell80, as @SpencerWoo points out, you can add the `link` button to the `image` selection toolbar to be able to wrap an image in a link.

**Comment by duracell80** [comment]
That did work, it would be helpful if the demo HTML contained all features by default. Please consider that some editing does need extensive feature sets, whereas some editing activity like commenting editors can do without icons.

Enabling all features in demo would allow better evaluation. It's also much easier to take things away than figure out how to add them.

**Comment by wincent** [comment]
By way of "spring cleaning", I'm closing issues tagged with "question" that haven't had any activity in > 12 months. There have been quite a few releases since then and much has changed, and these "stale" issues are extremely unlikely to be acted on. Please feel free to comment and we can re-open on a case-by-case basis.
