### ISSUE TITLE
Drag and Drop Doesn't Work Within the Editor

### ISSUE THREAD

**Issue by gregory-bretall** [liferay/alloy-editor#839]
## Prelude
A customer noted to us that users are unable to drag and drop text or images internally in AlloyEditor. I verified that this is not only the case in the portal but on alloyeditor.com as well.

## Issue
You cannot internally drag and drop text or images within AlloyEditor.

*Steps to Reproduce :*

1. Content -> Blogs -> Add Blog Entry
2. Upload an image to the blog post content
3. Write text to the body content
4. Attempt to drag image in between some words

Expected Results: The image is moved to the location the cursor indicates.

Actual Results: The cursor properly traces where you will 'drop' the image but on mouse up nothing happens.  The image is not moved.

## Solution
I made it so the preventDefault is only fired by AlloyEditor's dragdrop function when we need to specifically override the behavior, otherwise the default CKEditor dragDrop should be use.

## Test
Tested on Chrome, Firefox, MS Edge, and IE11.

**Comment by gregory-bretall** [comment]
Fix found here https://github.com/liferay/alloy-editor/pull/840

**Comment by jbalsas** [comment]
Merged and released to 1.x.

Thanks @gregory-bretall !
