### ISSUE TITLE
Changing table column width in editor fails randomly

### ISSUE THREAD

**Issue by mateuszbieniek** [liferay/alloy-editor#845]
After inserting a table into editor area you can change column width by dragging by column edge. But when you actually try to do this couple of times, you will encounter randomly bug, that will prevent you to do it. Instead, elements under will get selected.

You can easily reproduce this issue in Alloy live demo on homepage using newest Chrom, Firefox or Edge.

Here is screencast showing bug "in action":
![table_resize_bug_alloy](https://user-images.githubusercontent.com/38975612/40420255-1a88a24e-5e88-11e8-88bb-d2b588f3a865.gif)

**Comment by mateuszbieniek** [comment]
Hi @jbalsas, yes I have.

**Comment by jbalsas** [comment]
Thanks, we'll take a look to see if we can figure it out!

**Comment by rolandpakai** [comment]
Hi @jbalsas , i would like to ask do you think you will have to have a look on this issue? A customer also reported this issue too. See: https://issues.liferay.com/browse/LPS-86054  
Thanks, Roland
