### ISSUE TITLE
Feature Request : Provide Tweet Intent On Non-Editor Side Of Created Content

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#846]
Offer highlighted text based share feature that allows users to select their own text to share. This would ideally be network independent but would offer more than one network in isolation. Make the feature character count aware so that large amounts of text can't be selected.

**Example seen here:**
https://readwrite.com/2017/08/19/continental-self-driving-tl1/

![another-example](https://user-images.githubusercontent.com/18121278/40684374-ca4c4e1a-6356-11e8-8da0-822fbfb07fa4.gif)

**Comment by jbalsas** [comment]
Hey @duracell80, as I mentioned, this is well beyond the scope of the editor. When this feature is active, the editor is not even around. I've filed https://issues.liferay.com/browse/LPS-82279 as a feature request assuming you'd like this feature in the Liferay Portal platform.

Please, upvote and add your comments there!
