### ISSUE TITLE
Missing Feature: Can't Clear Image Alignment Once Set

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#847]
Aligning images left, right, and center on the whole works. However the streamlined UI is missing a vital feature. If the image no longer is needed to be aligned, there is no UI icon to reset or remove this alignment. The user must have knowledge of HTML to manually edit the style attribute of the image to clear the float / transform.

This could be a misinterpretation of the UI on my part, however there is no "reset alignment" icon that is made obvious and intuitive. While providing an extra icon might go against the notion of having a simple UI ... simple UI doesn't have to mean lack of features. The user can click the icon again to reset the alignment but the tooltip doesn't state this.

Providing that icon would only take up UI space that would have been used for "Justify".

**Comment by jbalsas** [comment]
Hey @duracell80, the alignment buttons act as a toggle. Clicking again on the current alignment makes it reset and lose any alignment values.
