### ISSUE TITLE
When Aligning an Image Context Bar Not Following Alignment (Internet Explorer)

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#853]
Snapping of context bar for image alignment isn't following image location in IE.

![context-bar-not-snapping-ie](https://user-images.githubusercontent.com/18121278/41253840-33b8b14c-6d87-11e8-8a58-8b54b99eb192.gif)

But is in Chrome

![context-bar-is-snapping-chrome](https://user-images.githubusercontent.com/18121278/41253842-37b7ae4c-6d87-11e8-8bf9-0c882b112747.gif)

**Comment by jbalsas** [comment]
Thanks for reporting, @duracell80. This is indeed an issue with how the selection changes and is notified to the editor. We'll need to figure out a way to make it more consistent across browsers.
