### ISSUE TITLE
When Aligning Images Float Left and Right Is Not Cleared

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#854]
Expected, floats clear correctly. Actual : floats are not being cleared when image is last item of content on page.

![overflowing-float-not-cleared](https://user-images.githubusercontent.com/18121278/41256191-7d73566e-6d8e-11e8-87da-d6fc84ed2cff.gif)

**Comment by jbalsas** [comment]
Hey @duracell80, I think this is expected from the HTML layout persepective. We are floating an image, so the container, by default, won't take its dimensions into account.

I think this should be fixable on the user-side by setting `overflow: auto` to the editable container.

**Comment by duracell80** [comment]
That did work, but why would a user need to fix a bug with the product when overflow auto could be added to that div by the product team?

**Comment by jbalsas** [comment]
I take that you're saying this happens in Liferay Portal? If so, it is indeed something that needs to be fixed, just that this repo doesn't deal with Liferay Portal. I'll verify and file an issue there.

**Comment by duracell80** [comment]
This occurs in the demo downloaded from Alloy Editor site as well as DXP. There should be an LPS already for DXP.

**Comment by wincent** [comment]
By way of "spring cleaning", I'm closing issues tagged with "question" that haven't had any activity in > 12 months. There have been quite a few releases since then and much has changed, and these "stale" issues are extremely unlikely to be acted on. Please feel free to comment and we can re-open on a case-by-case basis.
