### ISSUE TITLE
Bug when editing a image link on IE 11

### ISSUE THREAD

**Issue by linolaoj** [liferay/alloy-editor#858]
## Prelude
On alloyeditor, user cannot edit the value of image link using IE11.
https://issues.liferay.com/browse/LPS-81518

## User story
Steps to reproduce on portal:
1. Startup the portal
2. Create a web content with an image
- Click on Content
- Click on Web Content
- Click on the icon "+"
- Click on Basic Web Content
- Add a title
- In the content, insert an image (click on the "+" icon and select an image)
3. Click on the image, click on the link icon and insert the following site "http://www.globo.com"
4. click on "√" and publish the content
5. Edit the web content using Internet Explorer 11
- Click on the image, click on the link icon and change the link to the following site "http://www.uol.com.br"
- on "√" and publish the content
6. Click on the published image to access the new url

Actual results:
- link value is not updated on IE11

## Acceptance Criteria
User should be able to edit and save the image link.

**Comment by julien** [comment]
@matuzalemsteles I'll close this one for now.
