### ISSUE TITLE
Toolbar increases in size when close to right window edge

### ISSUE THREAD

**Issue by fortunatomaldonado** [liferay/alloy-editor#866]
## Prelude
When editing a text on the left side of the editor close to the window edge, the toolbar will always be a set size. When editing a text that is located close to the right window edge, the toolbar will be resized to allow all components to be viewed. This resizing can look off especially when trying to add a link.

## Reproduce
1. Go to demo at https://alloyeditor.com/
2. Resize the browser so that the right side of the browser is as close as possible to the editor.
3. Highlight a text and notice the toolbar size.
4. Click the link option and notice the toolbar size.
5. Repeat step 2, 3, and 4 but on the right side of the editor.

The toolbar will always be a consistent size until it reaches the right side of the browser.

## Acceptance Criteria
- The toolbar will be a consistent size no matter on the left or right of the browser.

## Notes
There is not resizing on the left since the [getWidgetXYPoint](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/components/base/widget-position.js#L122) makes sure the widget will be visible on the top and left of the screen. The right side is resized due to CSS.
![ae](https://user-images.githubusercontent.com/31672551/42003200-1a2f27de-7a1f-11e8-9e91-5a37a2ab971d.gif)

**Comment by jbalsas** [comment]
Fixed by https://github.com/liferay/alloy-editor/pull/867 and released with `1.5.11`

**Comment by jbalsas** [comment]
Hey @fortunatomaldonado, you should simply need to backport https://issues.liferay.com/browse/LPS-83409

**Comment by fortunatomaldonado** [comment]
Hello @jbalsas,

Thank you for the information. I was testing the fix in 7.0.x and I found it would overflow off the screen from time to time. I'm not sure if you also have seen this behavior. I tested some more and found we can subtract the document.body.offset by the offsetWidth to prevent this overflow in 7.0.x. This does not seem to be an issue in Master since the margin for the editor are further away from the browser edge. I have not yet tested this on Master. Let me know what you think about this.
Thank you.

Overflow
![overflow-toolbar](https://user-images.githubusercontent.com/31672551/42663396-30304104-85ea-11e8-93bf-6c80f229966c.gif)


Subtracting offsetWidth
![using-offsetwidth](https://user-images.githubusercontent.com/31672551/42663408-3dcbd45e-85ea-11e8-9f77-7ba559dd0af7.gif)

**Comment by fortunatomaldonado** [comment]
Hello @jbalsas,

I sent a pull request for the issue mentioned above. https://github.com/liferay/alloy-editor/pull/868
Let me know if I should create a separate issue for this or if you believe this is not required.
Thanks for the help.
