### ISSUE TITLE
My changes is not saving when i not call UI alloy-editor.

### ISSUE THREAD

**Issue by vncsms** [liferay/alloy-editor#878]
I'm using the alloy-editor to edit the text of my site, but i create a a directive in angular to change soma images class. This directive is trigger by ading a button in 

    alloyEditorGet.on('editorInteraction', function(interaction) {
              $rootScope.$broadcast('alloyInteraction', true);

              var editorSelection = interaction.data.selectionData.text,
                  imageSelection,
                  buttonId = 'newEventButton';
    if(interaction.data.selectionData.element){
                imageSelection = interaction.data.selectionData.element.$;
              }

              if(imageSelection){
                $timeout(function() {
                  var selector,
                      button,
                      html;

                  html = $('<button>').attr({
                    'id': 'extendImage',
                    'title': 'Extend image',
                    'class': 'ae-button fa fa-hand-spock-o',
                    'expand-body': '.article-body',
                    'expand-container': '#article-container',
                    'pr-expand-image': '.image-expanded',
                    'pr-expand-editor-image': interaction.data.selectionData
                                                         .element.$.dataset.uid
                  });

                  selector = '.ae-arrow-box.ae-toolbar-transition';
                  selector += '.alloy-editor-visible > div';

                  button = $compile(angular.element(html))(scope);
                  $('#extendImage').remove();
                  $(selector).append(button);
                }, 100);
              }
    ...

The directive is `pr-expand-editor-image` and will change the class of my image. But when i will save the page the changes are not saved, but if i call any UI alloy-editor the change will be saved. So i tried to edit html in console like adding text without call any UI alloy-editor, and again the changes in my scope is not changing. My theory is every time i call any UI editor the scope is saved in somewhere. My question is, is there any function to update the scope, that can i call every time i want?

**Comment by wincent** [comment]
By way of "spring cleaning", I'm closing issues tagged with "question" that haven't had any activity in > 12 months. There have been quite a few releases since then and much has changed, and these "stale" issues are extremely unlikely to be acted on. Please feel free to comment and we can re-open on a case-by-case basis.
