### ISSUE TITLE
[UX] The icon X on link view is misleading

### ISSUE THREAD

**Issue by ipeychev** [liferay/alloy-editor#88]
The icon X which appears when toolbar styles is opened in link view, is misleading. The user has the impression that clicking on it should remove the link. Instead, by design clicking on this button switches to style view of the toolbar.

**Comment by jbalsas** [comment]
This should be fixed in the ReactUI in https://github.com/liferay/alloy-editor/pull/124 that changes the link UI behaviour.

**Comment by ipeychev** [comment]
Fixed via https://github.com/jbalsas/alloy-editor/commit/10d45098d565f6dbdb48476644447771486a309e
