### ISSUE TITLE
Check published code for missing semi colons particularly in IE11

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#900]
Missing semi colons in the inline styles are causing syntax errors that are adversely affecting published content.

**Comment by SpencerWoo** [comment]
I've confirmed this issue -- https://issues.liferay.com/browse/LPS-87003

Publishing in IE11 produces missing semi-colon styles (observable in the database too) which causes our CSS selectors to miss -- giving us improper padding across browsers.

---

I've been trying to debug this however Chrome 
https://github.com/liferay/alloy-editor/blob/6aa8bc0dc15c93d6d02b06a03798c5345ad21c8c/src/plugins/imagealignment.js#L111 seems the same as IE11 https://github.com/liferay/alloy-editor/blob/2da51f895eaec032247267aefdf5d60f928f994b/src/plugins/dragresize_ie11.js#L862 however I'm assuming they deviate somewhere further down the line?

**Comment by SpencerWoo** [comment]
https://github.com/liferay/alloy-editor/pull/913
