### ISSUE TITLE
Configure linting on the project

### ISSUE THREAD

**Issue by julien** [liferay/alloy-editor#926]
At the moment several linters are used as dependency but none really seems to be used correctly:

We have `.eslintrc.js` and `.jshintrc` files but if you add a new file that doesn't match the rules defined by these linters you can still build the project.

It might be a good idea to use just one tool for the job (my vote would go for `eslint`) and make sure that if linting fails the build process should also be aborted.

**Comment by wincent** [comment]
This one is superseded by #990 (sorry, I created that one without seeing this one). Will close this one because the other one had all the PRs attached to it.
