### ISSUE TITLE
The word "Normal" in the styles drop down has become de-capitalized as "normal"

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#950]
Found in DXP but because the demo here is very limited there is no bullet list feature enabled. Simply in DE-28 making text a bullet list didn't cause the word "normal" to change to "Normal" and "N"ormal is correct. It seems that the wording has been decapitalized somwhere, and then that change if willful was not propagated. I only spotted this in DE-68 and I would think that somewhere in Alloy Editor main code the issue has occurred. 

Again though the demo is pretty terrible as features are hidden.

**Steps**
1) Add some text, see that in the content bar the word Normal is "normal"
2) Change that text to be a bullet list
3) See that the word has now changed to "Normal"

**Expected**
Wording to not change when using different text features. Hasn't been like this previously. "N"ormal was correct.

**Actual**
One or the other, "Normal" is the correct presentation "normal" was not.

DE-28
![de-28](https://user-images.githubusercontent.com/18121278/50931779-4546e700-1429-11e9-856a-027d8c4c8355.gif)

DE-64
![de-64](https://user-images.githubusercontent.com/18121278/50931777-4546e700-1429-11e9-957d-e70c18e1b316.gif)

**Comment by jbalsas** [comment]
Hey @duracell80, thanks for reporting this. For some reason, this is something affecting the key translations directly in portal, as we're not the ones providing the translations. Another instance of this is https://issues.liferay.com/browse/LPS-84770. 

We're investigating in the context of Liferay Portal to see what changed with the way the ResourceBundles are being aggregated.
